import {useEffect,useMemo,useState} from 'react';
import {streamInventory} from './streamInventory';
import {applyStreamSettings,settingsChanged,streamSettings} from './streamSettings';
import {useStream} from './useStream';
import {RelayScene} from './RelayScene';
import {top,volume} from '../geometry';
import {materialInfo} from '../materials';
import type {Scenario} from '../types';
import './relay.css';
import './studio.css';
import './flow.css';
import './twin.css';
import {TwinRunStatus,TwinPackingReadout} from './TwinPanels';
import {TwinStabilityPanel} from './TwinStabilityPanel';
import {assessPalletCom} from '../comAssessment';
import {displayBoxColor} from './twinSceneTheme';
const phaseNames={loading:'선별 · 적재',checking:'출고 검사',outbound:'AMR 반출',returning:'빈 팔레트 복귀'};
function download(value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='continuous-pallet-run.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function FlowLab({sourceScenario,active}:{sourceScenario:Scenario;active:boolean}){
 const [seed,setSeed]=useState(42),[count,setCount]=useState(96),[height,setHeight]=useState(1600),[scenario,setScenario]=useState(()=>streamInventory(42)),[notice,setNotice]=useState(''),[focus,setFocus]=useState<number|null>(null),[cameraVersion,setCameraVersion]=useState(0);
 const sim=useStream(scenario,active),w=sim.world,flow=w.stream!,pending=w.boxes.filter(b=>b.status==='pending').length,placed=w.boxes.filter(b=>b.status==='placed').length,belt=w.boxes.filter(b=>b.status==='belt').length;
 const draft={seed,count,height},dirty=settingsChanged(scenario,draft);
 const [archive,setArchive]=useState<number|null>(null);
 useEffect(()=>setArchive(null),[w.runId]);
 const viewed=useMemo(()=>{if(archive===null||!flow.dispatched[archive])return w;const saved=flow.dispatched[archive],copy=structuredClone(w);copy.cells[saved.robot].placements=saved.placements;copy.stream!.cells[saved.robot].phase='loading';copy.runId+=`-archive-${archive}`;return copy;},[w,archive]);
 // Placement versions change on commit/dispatch; avoid recomputing during belt animation.
 const stability=useMemo(()=>viewed.cells.map(c=>assessPalletCom(scenario.pallet,c.placements)),[scenario.pallet,viewed.runId,viewed.cells[0].version,viewed.cells[1].version,viewed.cells[2].version,viewed.cells[3].version]);
 const heights=w.cells.map(c=>Math.max(0,...c.placements.map(top))),known=w.boxes.filter(b=>b.flow&&b.flow.measuredAt<=w.time),allPlacements=[...w.cells.flatMap(c=>c.placements),...flow.dispatched.flatMap(c=>c.placements)],minSupport=allPlacements.length?Math.min(...allPlacements.map(p=>p.supportRatio)):1;
 useEffect(()=>{if(sourceScenario.id==='packaging-aware'){sim.setPlaying(false);setScenario(structuredClone(sourceScenario));const settings=streamSettings(sourceScenario);setSeed(settings.seed);setCount(settings.count);setHeight(settings.height);setNotice('현재 포장 규격의 회전·지지·하중·파지 제약을 유지하며 순차 계측합니다.');}},[sourceScenario]);
 const generate=(fresh=false)=>{try{const nextSeed=fresh?crypto.getRandomValues(new Uint32Array(1))[0]%1000000:seed;const next=applyStreamSettings(scenario,{...draft,seed:nextSeed});setScenario(next);setSeed(nextSeed);setArchive(null);setCameraVersion(v=>v+1);sim.reset(true);setNotice(`높이 ${height} mm · 시드 ${nextSeed} · ${count}개로 재실행했습니다. 높이만 변경하면 같은 박스 세트를 유지합니다.`);}catch(error){setNotice(String(error));}};
 const status=flow.complete?'공급분 적재·반출 완료':!sim.playing?w.time?'공정 일시정지':'연속 공정 준비':`${sim.motions.length}대 작업 중 · 입고와 벨트는 계속 이동`;
 const toggle=()=>{if(dirty||flow.complete||sim.error){generate();return;}setArchive(null);sim.setPlaying(v=>!v);};
 const exportRun=()=>download({version:6,mode:'continuous-tracking-conveyor',scenario,world:w,motions:sim.motions,peakConcurrent:sim.peak,compute:{lastMs:sim.ms,checks:sim.checks},assumptions:'균등 질량 직육면체 · 합성 포장 강도 · 계측 이후 정보만 계획 · 코너 모듈은 자세를 유지해 이송 · 전체 로봇 링크 충돌 미검증'});
 return <section className="relay-lab flow-lab" hidden={!active} aria-label="연속 컨베이어 4대 로봇 시뮬레이터">
  <div className="relay-heading"><div className="studio-title"><small>ADAPTIVE PALLETIZING <span>/ DIGITAL TWIN</span></small><h1>Mixed Palletizing</h1><p>하나의 컨베이어 · 네 작업셀 · 관측 기반 혼합 적재</p></div><TwinRunStatus playing={sim.playing} complete={flow.complete} error={sim.error} time={w.time} seed={scenario.arrival.seed}/><div className="studio-hero-actions"><span className="studio-local"><i/> LOCAL ENGINE · AI 추론 없음</span><button className="pallet-primary" onClick={toggle} >{dirty?'변경 조건으로 재실행 ↗':flow.complete||sim.error?'같은 조건으로 재실행 ↗':sim.playing?'공정 일시정지 Ⅱ':w.time?'연속 공정 계속 ↗':'연속 시뮬레이션 시작 ↗'}</button><a href="/motion/index.html">알고리즘 살펴보기 ↗</a></div></div>
  <div className="flow-lanes" aria-label="동시에 진행하는 공정"><span><i className={sim.playing&&pending?'on':''}/>인입·이동 계측 <b>{flow.measured} / {w.boxes.length}</b></span><span><i className={sim.playing&&belt?'on':''}/>벨트 순환 <b>{belt}개</b></span><span><i className={sim.playing&&sim.motions.length?'on':''}/>추적 집기·적재 <b>{sim.motions.length} / 4대</b></span><span><i className={sim.playing&&flow.cells.some(c=>c.phase!=='loading')?'on':''}/>독립 팔레트 교체 <b>{flow.dispatched.length}회</b></span></div>
  {notice&&<p className="relay-notice" role="status">{notice}</p>}
  <div className="relay-totals" aria-label="실시간 박스 수량"><span>미인입 <b>{pending}<small>개</small></b></span><span>벨트 위 <b>{belt}<small>개</small></b></span><span>집기 예약·운반 <b>{sim.motions.length}<small>개</small></b></span><span>적재 누계 <b>{placed}<small>개</small></b></span><span>재순환 누계 <b>{flow.passes}<small>바퀴</small></b></span><span>최저 바닥 지지 <b>{allPlacements.length?(minSupport*100).toFixed(0):'—'}<small>{allPlacements.length?'%':''}</small></b></span><small>수량 보존 {w.boxes.length} = {pending} + {belt} + {sim.motions.length} + {placed} · 시뮬레이션 {w.time.toFixed(1)} s · 최대 동시 {sim.peak}대 · 높이 상한 {scenario.pallet.maxHeight} mm</small></div>
  <div className="relay-workspace"><section className="flow-settings"><div className="studio-section-label"><h3>실험 조건</h3><span>INPUT</span></div><form noValidate onSubmit={e=>{e.preventDefault();generate();}}><div className="flow-inputs"><label>개별 박스 수<input aria-label="연속 입력 박스 수" type="number" min={8} max={120} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label>최대 높이 · mm<input aria-label="연속 입력 최대 높이" type="number" min={600} max={2000} step={10} value={height} onChange={e=>setHeight(Number(e.target.value))}/></label><label>랜덤 시드<input aria-label="연속 입력 시드" type="number" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label></div><button type="submit">조건 적용 · 바로 재실행</button></form>{dirty&&<p role="status">변경 대기: 최대 {height} mm · 적용하면 기존 실행을 초기화하고 바로 시작합니다.</p>}<p>넓은 평형·긴 포장·높은 포장·소형·중형·대형을 개별 mm 단위로 생성합니다. 박스마다 치수·무게·재질·허용 하중이 다릅니다.</p><dl><div><dt>팔레트 가로 × 세로</dt><dd>{scenario.pallet.width} × {scenario.pallet.depth} mm · {(scenario.pallet.width*scenario.pallet.depth/1e6).toFixed(2)} m²</dd></div><div><dt>벨트 / TCP 속도</dt><dd>{flow.speed} / {scenario.constraints.gripper.speed} mm/s</dd></div><div><dt>그리퍼 W × D × H</dt><dd>{scenario.constraints.gripper.width} × {scenario.constraints.gripper.depth} × {scenario.constraints.gripper.height} mm</dd></div><div><dt>가반하중 / 포장 하중 안전계수</dt><dd>{scenario.constraints.gripper.payload} kg / 1.5</dd></div><div><dt>로봇 외형</dt><dd>HD 현대 스타일<br/><a href="https://www.hd-hyundairobotics.com/biz/product/detail/41" target="_blank" rel="noreferrer">HDR35-20 외형 참고 ↗</a><small className="twin-model-note">가상 기구학 · 실제 기종 사양과 별도</small></dd></div><div><dt>계산 예산</dt><dd>기본 후보 64개 · 후속 표본 최대 3개</dd></div></dl><button onClick={exportRun}>입력·판단·출고 이력 JSON 저장 ↗</button></section><div className="relay-viewport"><div className="relay-status" role="status" aria-label="연속 공정 상태">{status}<span>{sim.busy?'선별 계산 중 · 벨트 이동 유지':`최근 선별 ${sim.ms.toFixed(1)} ms`}</span></div>
   {archive!==null&&flow.dispatched[archive]&&<p className="relay-notice">출고 이력 보기 · R{flow.dispatched[archive].robot+1} / 팔레트 #{flow.dispatched[archive].cycle} · 실제 공정은 일시정지 중 <button onClick={()=>setArchive(null)}>현재 공정으로</button></p>}
   {active&&<RelayScene key={w.runId} scenario={scenario} world={viewed} motions={archive===null?sim.motions:[]} focus={focus} cameraVersion={cameraVersion} phase={w.time?'packing':'ready'} processProgress={0} context="amr" clock={w.time} clockRate={sim.playing&&active&&!flow.complete?sim.speed:0}/>}
   <div className="relay-playback"><button className="pallet-primary" onClick={toggle} >{dirty?'변경 조건으로 재실행':flow.complete||sim.error?'다시 실행':sim.playing?'Ⅱ 일시정지':'▶ 연속 실행'}</button><button onClick={()=>sim.reset()}>같은 입력 초기화</button><button onClick={()=>generate(true)}>새 랜덤 입력</button><label>재생 속도 <select aria-label="연속 공정 재생 속도" value={sim.speed} onChange={e=>sim.setSpeed(Number(e.target.value))}>{[1,2,4,8,16].map(n=><option key={n} value={n}>{n}×</option>)}</select></label></div>
   <p className="flow-caption">처리량 {w.time?(placed*60/w.time).toFixed(1):'0.0'}개/min · 평균 로봇 작업 {w.records.length?(w.records.reduce((n,r)=>n+r.finished-r.started,0)/w.records.length).toFixed(1):'—'} s · 재생 배속은 화면 관찰 속도입니다.</p><div className="flow-focus" aria-label="팔레트 시점 선택"><button aria-pressed={focus===null} onClick={()=>{setFocus(null);setCameraVersion(n=>n+1);}}>전체 공정</button>{heights.map((h,i)=><button key={i} aria-pressed={focus===i} onClick={()=>{setFocus(i);setCameraVersion(n=>n+1);}}>P0{i+1} <span>{h} mm</span></button>)}</div>
   <p className="flow-caption">벨트는 집기 중에도 이동합니다. 통과한 박스는 다음 로봇이 다시 판단하며, 팔레트 교체 중에도 다른 셀은 작업합니다.</p>
  </div><aside className="relay-decision"><TwinStabilityPanel assessments={stability} pallet={scenario.pallet} focus={focus} archived={archive!==null&&focus===flow.dispatched[archive]?.robot} onFocus={i=>{setFocus(i);setCameraVersion(v=>v+1);}}/><TwinPackingReadout scenario={scenario} stacks={w.cells.map(c=>c.placements)}/><details className="twin-cell-monitor"><summary>작업셀 모니터 <span>4 ROBOTS</span></summary>{w.cells.map((cell,i)=>{const m=sim.motions.find(m=>m.action.robot===i),state=flow.cells[i];return <div className="relay-arm-task" key={i}><b className="studio-arm-heading">R0{i+1} · {m?'이동 박스 집기·적재':phaseNames[state.phase]}</b><p className="studio-arm-idle">{m?m.action.boxId:`팔레트 #${state.cycle}`}<span>{heights[i]} / {scenario.pallet.maxHeight} mm</span></p>{m?<><small>{m.action.reason}</small><progress max={1} value={m.progress}/><small className="ops-time">남은 {Math.max(0,m.action.seconds-m.elapsed).toFixed(1)} s / 총 {m.action.seconds.toFixed(1)} s</small></>:<small>{state.phase==='loading'?'계측된 박스의 지지·하중·후속 공간을 검토합니다.':'이 셀만 교체 중 · 나머지 세 로봇은 계속 작업'}</small>}<small>현재 {cell.placements.length}개 · 용적 {(100*cell.placements.reduce((n,p)=>n+volume(p.size),0)/(scenario.pallet.width*scenario.pallet.depth*scenario.pallet.maxHeight)).toFixed(1)}%</small></div>;})}</details>
   <div className="flow-rule"><b>적용 중인 제약</b><p>지지 ≥ {Math.round(scenario.constraints.supportRatio*100)}% · 무게중심 지지영역 검사<br/>누적 하중·재질·회전·전도 검사<br/>경계 돌출 금지 · 높이 {scenario.pallet.maxHeight} mm 이하</p></div>
   {sim.error&&<p role="alert">{sim.error}</p>}
  </aside></div>
  <div className="flow-bottom"><section className="flow-observations"><div className="studio-section-label"><h3>지나가는 박스의 판단</h3><span>MEASURED ONLY</span></div><p className="flow-caption">후속 막힘은 관측된 다른 박스 최대 3개의 배치 가능성 비교입니다. 통계적 확률이 아닙니다.</p><div className="flow-feed">{known.filter(b=>b.status!=='placed').slice(-12).reverse().map(b=><div key={b.observation.id}><i style={{background:displayBoxColor(scenario.types.find(t=>t.id===b.observation.typeId)?.color??'#789cb9')}}/><div><b>{b.observation.id} <span>{materialInfo(b.observation).name}</span></b><small>{b.observation.size.w} × {b.observation.size.d} × {b.observation.size.h} mm · {b.observation.weight} kg</small><p>{b.status==='reserved'?`R${b.owner+1} 집기 예약 · ${b.flow!.lastReason}`:b.flow!.lastReason}</p></div><span>{b.flow!.passes}회 순환</span></div>)}{!known.length&&<p className="flow-empty">실행하면 입고 순서대로 치수·무게·재질과 선별 결과가 표시됩니다.</p>}</div></section>
   </div>
  {flow.dispatched.length>0&&<section className="flow-history"><div className="studio-section-label"><h3>출고 팔레트 · 3D 검사</h3><span>{flow.dispatched.length} PALLETS</span></div><div>{flow.dispatched.map((p,i)=><button key={i} aria-pressed={archive===i} onClick={()=>{sim.setPlaying(false);setArchive(i);setFocus(p.robot);setCameraVersion(v=>v+1);}}>R{p.robot+1} / #{p.cycle}<b>{p.placements.length}개 · {Math.max(...p.placements.map(top))} mm</b><small>{p.at.toFixed(0)} s 반출</small></button>)}</div></section>}
  <details className="relay-scope"><summary>알고리즘과 모델링 범위</summary><p>① 이동 계측 → ② 작업셀 진입 박스만 선별 → ③ 지지·전도·누적 하중·높이 검사 → ④ 관측한 후속 박스의 공간 손실 비교 → ⑤ 집기 시점 위치를 재계산해 벨트 속도로 추적합니다. 불가 후보는 벨트에 그대로 둡니다. 로봇·박스·겹치는 운반 경로를 예약하므로 중복 집기를 막습니다. Worker의 연산 중에도 벨트와 다른 로봇은 계속 움직입니다.</p><p>팔레트는 상한의 96% 도달, 또는 마지막 적재 후 벨트 1.1바퀴에 해당하는 시간이 지나고 서로 다른 박스 6개 이상(입고 종료 후에는 남은 전부)을 배치할 수 없을 때 독립 교체합니다. 공급분의 적재가 모두 끝나면 남은 팔레트도 반출합니다. 빈 팔레트에도 놓을 수 없는 박스는 사라지지 않고 계속 순환합니다. 재생 속도가 높아 집기 구간을 놓치면 다음 구역에서 다시 판단합니다.</p><p>균등 질량 직육면체·수평 강체 접촉을 가정합니다. 강도·마찰은 합성 실험 값이며 실제 포장 인증값이 아닙니다. 모서리 이송 모듈은 박스 자세를 유지한다고 가정합니다. 그리퍼/운반체 경로와 가상 TCP 도달을 검사하며 실제 로봇 전체 링크, 흡착, 포장 변형 및 AMR 다중 경로 충돌은 검증 범위 밖입니다. 전역 최적해 또는 현장 안전 인증을 보장하지 않습니다.</p></details>
  <footer className="studio-footer"><b>PALLET LOADING LAB</b><span>연속 이송 · 관측 기반 선별 · 브라우저 로컬 연산</span><span>4 ROBOTS / 1 CONVEYOR</span></footer>
 </section>;
}
