import {CONTEXTS,PHASES,PHASE_LABELS,phaseSeconds,TRAVEL_MM} from './operations';
import type {ContextId} from './operations';
import type {useOperations} from './useOperations';
import type {useRelay} from './useRelay';
import type {Scenario} from '../types';
interface Props {flow:ReturnType<typeof useOperations>;sim:ReturnType<typeof useRelay>;scenario:Scenario;context:ContextId;setContext:(v:ContextId)=>void;thickness:number;setThickness:(n:number)=>void}
export function OperationsPanel({flow,sim,scenario,context,setContext,thickness,setThickness}:Props){
 const c=CONTEXTS[context],g=scenario.constraints.gripper,m=sim.compute,index=PHASES.indexOf(flow.phase),total=sim.world.boxes.length,placed=flow.manifest.reduce((n,p)=>n+p.boxIds.length,0),released=['returning','complete'].includes(flow.phase);
 return <section className="ops-panel" aria-label="인입부터 반출까지 공정">
  <div className="ops-head"><div><small>INFEED → PACK → DISPATCH</small><h2>적재를 넘어, 한 배치의 물류 흐름.</h2><p>{c.description} · 박스 세트와 환경을 고르면 나머지는 기본값으로 실행합니다.</p></div><label>작업 환경<select aria-label="물류 작업 환경" value={context} onChange={e=>setContext(e.target.value as ContextId)}>{Object.entries(CONTEXTS).map(([id,v])=><option value={id} key={id}>{v.name}</option>)}</select></label></div>
  <ol className="ops-flow">{PHASES.map((p,i)=><li key={p} aria-current={p===flow.phase?'step':undefined} className={flow.phase==='complete'||i<index?'done':''}><span>0{i+1}</span><b>{PHASE_LABELS[p]}</b><small>{p==='packing'?'4대 독립 실행 · 경로 예약':`${phaseSeconds(p,total,context).toFixed(1)} s · 가정`}</small>{p===flow.phase&&p!=='packing'&&<progress value={flow.progress} max={1}/>}</li>)}</ol>
  <div className="ops-controls"><button className="pallet-primary" onClick={flow.start} disabled={flow.running||flow.phase==='complete'||!!sim.error}>{flow.phase==='ready'?'▶ 인입부터 전체 실행':'▶ 공정 계속'}</button><button onClick={flow.pause} disabled={!flow.running}>공정 일시정지</button><button onClick={flow.reset}>새 배치 준비</button><label>재생 속도<select aria-label="전체 공정 재생 속도" value={sim.speed} onChange={e=>sim.setSpeed(Number(e.target.value))}>{[1,4,16,64].map(n=><option key={n} value={n}>{n}×</option>)}</select></label><strong role="status" aria-label="물류 공정 상태">{PHASE_LABELS[flow.phase]}{!flow.running&&flow.phase!=='ready'&&flow.phase!=='complete'?' · 정지':''}</strong><span>인입 {flow.phase==='ready'?0:flow.phase==='receiving'?Math.floor(flow.progress*total):total}/{total}개 · 모의 공정 {(sim.time+flow.processTime).toFixed(1)} s</span></div>
  <div className="ops-metrics"><div><small>그리퍼 · 실제 검사</small><b>{g.width} × {g.depth} × {g.height}<em> mm</em></b><span>폭 × 깊이 × 두께 · 여유 {g.margin} mm</span></div><div><small>로봇 TCP · 가정</small><b>{g.speed}<em> mm/s</em></b><span>가반 {g.payload} kg · 공구 {g.mass} kg 포함</span></div><div><small>{context==='fixed'?'컨베이어':'이송 플랫폼'} · 가정</small><b>{c.transportSpeed}<em> mm/s</em></b><span>편도 {TRAVEL_MM/1000} m + 도킹 {c.dock} s</span></div><div><small>반출 명세</small><b>{released?placed:0}<em> / {placed}개</em></b><span>{released?`${flow.manifest.length}개 팔레트 출고 · 미적재 ${total-placed}개 보존`:'모든 팔 정지 후 적재된 팔레트만 반출'}</span></div></div>
  <details className="ops-details"><summary>공구 두께 조정 · 모델 가정</summary><label>그리퍼 두께 <input aria-label="그리퍼 두께 mm" type="range" min={40} max={250} step={10} value={thickness} onChange={e=>setThickness(Number(e.target.value))}/><b>{thickness} mm</b></label><p>변경 시 새 배치로 초기화합니다. 공구 외형과 여유 공간, 자세별 운반체를 경로 검사에 사용합니다. 시간은 이동거리/속도와 회전시간 중 큰 값에 집기 {g.pickSeconds} s·놓기 {g.placeSeconds} s를 더한 추정치입니다. 가감속은 생략합니다.</p><p>이 공정은 유한 배치 입고를 먼저 완료한 뒤 탐색합니다. 단일 인입 지점에서 박스당 0.35 s 계측을 가정하며, 모든 박스 치수·무게·허용 하중은 합성 세트에서 읽습니다. 실제 센서 연결이나 알 수 없는 미래 입고 예측은 포함하지 않습니다.</p><p>AMR은 셀당 1대, 분리된 3 m 직선 통로를 가정합니다. 로봇이 모두 정지한 뒤 검사 3 s를 거쳐 이동합니다. 협동로봇은 속도·가반하중을 낮춘 실험 조건이며 사람 감지나 안전 인증 모델이 아닙니다. 빈 팔레트 복귀까지 한 배치를 실행하고 미적재 재고와 반출 명세는 보존합니다.</p></details>
  <div className="ops-edge"><div><small>LOCAL COMPUTE / EDGE-READY STRUCTURE</small><h3>상태가 바뀔 때만, 로컬에서 계산.</h3><p>Worker 1개 재사용 · 같은 셀 계산 캐시 · 높이 정책 24 → 유망 3종 64 → 실패 시 96 후보/종 · 높이 조합 상위 16개 · 동일 조합 재사용</p></div><dl><div><dt>최근 / 평균</dt><dd>{m.lastMs.toFixed(0)} / {(m.totalMs/Math.max(1,m.jobs)).toFixed(0)} ms</dd></div><div><dt>최대 · 채택된 계산</dt><dd>{m.maxMs.toFixed(0)} ms · {m.jobs}회</dd></div><div><dt>검사 / 생성 후보 누적</dt><dd>{m.checked.toLocaleString()} / {m.generated.toLocaleString()}</dd></div><div><dt>캐시 재사용</dt><dd>{m.cacheHits}회</dd></div></dl><small>현재 브라우저의 수신된 유효 Worker 결과 기준 실측입니다. 통신·렌더링·폐기된 이전 작업은 제외하며 엣지 장비의 성능 보증값이 아닙니다. 적재 판단은 서버 호출이나 AI 추론 없이 실행합니다.</small></div>
 </section>;
}
