import {CONVEYOR,hasBeltTransit} from './conveyor';
import {OperationsPanel} from './OperationsPanel';
import {useOperations} from './useOperations';
import {operationScenario,PHASE_LABELS,actionTiming} from './operations';
import type {ContextId,ProcessPhase} from './operations';
import { useState,useMemo,useEffect } from 'react';
import { RelayScene } from './RelayScene';
import { useRelay } from './useRelay';
import { relayDemo,relayStorageDemo,relayHeightDemo } from './demo';
import { ROBOT_COUNT,nextRobot,RELAY_COLORS } from './layout';
import { heterogeneousInventory,DEFAULT_FIELD } from '../inventoryGeneration';
import { ALL_ORIENTATIONS } from '../orientations';
import { materialInfo } from '../materials';
import { top,volume } from '../geometry';
import type { RelayAlgorithm } from './types';
import type { Scenario } from '../types';
import './relay.css';
import './studio.css';
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export {default} from './FlowLab';
export function BatchRelayLab({sourceScenario,active}:{sourceScenario:Scenario;active:boolean}){
 useEffect(()=>{if(sourceScenario.id==='packaging-aware'){setScenario(structuredClone(sourceScenario));setAlgorithm('height-fill');setNotice('포장별 회전·하중·지지·파지·3D 도달 제약 적용. 공장 로봇 가반하중은 기존 문맥 값을 사용합니다.');}},[sourceScenario]);
 const demo=new URLSearchParams(window.location.search).get('palletDemo')==='relay';
 const [source,setScenario]=useState(()=>demo?relayDemo():relayHeightDemo()),[algorithm,setAlgorithm]=useState<RelayAlgorithm>(demo?'bl':'height-fill'),[seed,setSeed]=useState(42),[seedDraft,setSeedDraft]=useState(42),[count,setCount]=useState(96),[heightDraft,setHeightDraft]=useState(1600),[shuffle,setShuffle]=useState(!demo),[transfers,setTransfers]=useState(true),[notice,setNotice]=useState(''),[focus,setFocus]=useState<number|null>(null),[cameraVersion,setCameraVersion]=useState(0);
 const [context,setContext]=useState<ContextId>('amr'),[thickness,setThickness]=useState(160),[phase,setPhase]=useState<ProcessPhase>('ready');
 const scenario=useMemo(()=>operationScenario(source,context,thickness),[source,context,thickness]);
 const sim=useRelay(scenario,algorithm,seed,shuffle,transfers,active,phase==='packing'),w=sim.view,total=w.boxes.length,placed=w.cells.reduce((n,c)=>n+c.placements.length,0),waiting=total-placed,passed=w.records.filter(r=>r.kind.startsWith('receive')).length,staged=w.pads.filter(p=>p.boxId).length,running=sim.motions.length;
 const flow=useOperations(sim,context,active,phase,setPhase);
 const describe=(kind:string)=>kind==='send'?'공용 벨트로 보류':kind==='receive-place'?'벨트 구역 → 팔레트 직접 적재':kind==='receive-queue'?'벨트 구역 → 자기 대기 재고':'자기 재고 → 팔레트';
 const travelling=hasBeltTransit(w);
 const now=sim.cursor===null&&phase!=='packing'?PHASE_LABELS[phase]:sim.cursor!==null?'과거 이력 · 읽기 전용':running?(sim.paused?'일시정지':`${running}대 동시 작업 중`):travelling?'공용 벨트 이송 · 다음 픽업 구역 대기':sim.busy?'빈 로봇의 다음 작업 계산 중':!waiting?'전체 재고 적재 완료':sim.decision&&!sim.decision.actions.length?'대기 재고 유지 · 가능한 적재/전달 없음':'다음 작업 준비';
 const load=(next:Scenario,isDemo=false)=>{if(next.events.length){setNotice('단계별 입고 이벤트가 없는 박스 세트를 선택해 주세요. 4대 협업은 이미 도착한 전체 재고를 나누어 처리합니다.');return;}setScenario(structuredClone({...next,supplyMode:'stock-select'}));setAlgorithm(isDemo?'bl':'height-fill');setHeightDraft(next.pallet.maxHeight);setShuffle(!isDemo);setTransfers(true);setSeed(seedDraft);setFocus(null);setNotice(isDemo?'먼저 놓으면 큰 받침을 막는 박스를 벨트 구역로 보냅니다. 받는 팔의 직접 적재 / 재고 보관 판단을 확인하세요.':'같은 박스를 네 재고에 한 번씩만 나눴습니다. 기존 한 팔레트 실행은 별도로 보존됩니다.');};
 const random=()=>{if(!Number.isInteger(seedDraft)||!Number.isInteger(count)||count<4||count>120){setNotice('시드는 정수, 전체 박스 수는 4~120개로 입력하세요.');return;}const next=structuredClone(scenario),generated=heterogeneousInventory({...DEFAULT_FIELD,seed:seedDraft,totalCount:count,typeCount:count,assortment:'individual'});next.events=[];next.types=generated.types;next.types.forEach(t=>{if(t.handling!=='upright')t.orientations=[...ALL_ORIENTATIONS];});next.generation=generated.generation;next.name=`4대 혼합 재고 · 시드 ${seedDraft}`;load(next);};
 const heightDemo=()=>{if(!Number.isInteger(heightDraft)||heightDraft<400||heightDraft>2000){setNotice('최대 높이는 400~2000 mm 정수로 입력하세요.');return;}load(relayHeightDemo(seedDraft,heightDraft));setNotice('불규칙 치수 16종 192개를 공급합니다. 낮은 빈자리·넓은 지지면부터 만들고 남은 높이에 맞는 박스를 순환시킵니다. 재질과 허용 하중은 합성 실험 값입니다.');};
 const heights=w.cells.map(c=>Math.max(0,...c.placements.map(top))),targetCount=heights.filter(h=>h>=scenario.pallet.maxHeight*.95).length;
 const exportRun=()=>download('pallet-four-robot-run.json',{version:5,operations:{context,phase,processSeconds:flow.processTime,manifest:flow.manifest,compute:sim.compute},mode:'four-robot-single-conveyor',conveyor:CONVEYOR,scenario,algorithm,seed,shuffle,transfers,world:w,motions:sim.motions,time:sim.cursor===null?sim.time:w.time,peakConcurrent:sim.peak,heightSummary:{limit:scenario.pallet.maxHeight,heights,targetCount,threshold:.95},history:sim.history.slice(0,(sim.cursor??sim.history.length-1)+1),summary:{initial:total,placed,waiting,transfers:passed,staged,palletCount:ROBOT_COUNT},scope:'네 팔 독립 동시 실행 · 동일 벨트 구역/운반 경로 배타 예약 · 가상 TCP/운반체 검사 · 실제 로봇 전체 링크 미검증'});
 return <section className="relay-lab" hidden={!active} aria-label="4대 로봇 협업 시뮬레이터">
  <div className="relay-heading"><div className="studio-title"><small>PALLETIZING STUDIO <span>/ 01</span></small><h1>하나의 컨베이어. 네 대의 로봇.</h1><p>서로 다른 박스를, 하나의 흐름으로. 배치가 어려운 박스는 다음 작업 구역으로 순환합니다.</p></div><div className="studio-hero-actions"><span className="studio-local"><i/> LOCAL ENGINE · AI 추론 없음</span><button className="pallet-primary" onClick={flow.start} disabled={flow.running||phase==='complete'||!!sim.error}>{phase==='ready'?'시뮬레이션 시작 ↗':phase==='complete'?'배치 완료':flow.running?'시뮬레이션 진행 중':'시뮬레이션 계속 ↗'}</button><a href="/motion/index.html">알고리즘 살펴보기 ↗</a></div></div>
  <div className="studio-process" aria-label="공정 진행"><span className="studio-mono">PROCESS</span>{(['receiving','packing','checking','outbound','returning'] as const).map((v,i)=><span key={v} data-current={phase===v}><i>0{i+1}</i>{PHASE_LABELS[v]}</span>)}</div>
  {notice&&<p className="relay-notice" role="status">{notice}</p>}
  <div className="relay-totals" aria-label="협업 수량 보존"><span>투입 재고 <b>{total}개</b></span><span>적재 완료 <b>{placed}개</b></span><span>대기 <b>{waiting}개</b></span><span>전달 완료 <b>{passed}회</b></span><span>벨트 순환 <b>{staged}개</b></span><span>현재 동시 작업 <b>{running}대</b></span><small>전체 {total} = 적재 {placed} + 구역별 재고 {waiting-staged} + 벨트 순환 {staged} · 재생 시계 {(sim.cursor===null?sim.time:w.time).toFixed(1)} s · 최대 동시 {sim.peak}대</small></div>
  <div className="relay-workspace"><div className="relay-viewport"><div className="relay-status" role="status" aria-label="협업 실행 상태">{now}<span>동작 {w.revision}</span></div>
   {active&&<RelayScene scenario={scenario} world={w} motions={sim.cursor===null?sim.motions:[]} focus={focus} cameraVersion={cameraVersion} phase={sim.cursor===null?phase:'packing'} processProgress={flow.progress} context={context} clock={sim.cursor===null?sim.time:w.time}/>}
   <div className="relay-playback"><button className="pallet-primary" onClick={flow.start} disabled={flow.running||phase==='complete'||!!sim.error}>▶ {phase==='ready'?'인입부터 실행':'공정 계속'}</button><button onClick={flow.pause} disabled={!flow.running&&!running}>일시정지</button><button onClick={sim.step} disabled={phase!=='packing'||sim.cursor!==null||sim.busy||!running&&!sim.decision?.actions.length}>준비된 팔 함께 시작</button><button onClick={()=>{flow.pause();sim.cancel();}} disabled={!running&&!sim.busy&&!sim.auto}>협업 동작 취소</button><button onClick={flow.reset}>협업 초기화</button><label>속도<select aria-label="협업 재생 속도" value={sim.speed} onChange={e=>sim.setSpeed(Number(e.target.value))}>{[1,4,16,64].map(n=><option key={n} value={n}>{n}×</option>)}</select></label><button onClick={()=>{setFocus(null);setCameraVersion(n=>n+1);}}>4대 전체 보기</button></div>
   <div className="relay-timeline"><label>협업 이력<input aria-label="협업 동작 이력" type="range" min={0} max={sim.history.length-1} value={sim.cursor??sim.history.length-1} disabled={!!running} onChange={e=>sim.seek(Number(e.target.value))}/>{sim.cursor??sim.history.length-1} / {sim.history.length-1}</label>{sim.cursor!==null&&<button onClick={()=>sim.seek(null)}>협업 현재로 돌아가기</button>}<button onClick={exportRun}>4대 실행 JSON 저장</button></div>
  </div><aside className="relay-decision"><div className="studio-section-label"><h3>작업셀 모니터</h3><span>04 ROBOTS</span></div>{w.cells.map((_,i)=>{const m=sim.motions.find(m=>m.action.robot===i),a=m?.action||sim.decision?.actions.find(a=>a.robot===i);return <div key={i} className="relay-arm-task" data-testid={`relay-task-${i}`}><b className="studio-arm-heading" style={{color:RELAY_COLORS[i]}}>R{i+1} · {m?sim.paused?'일시정지':'작업 중':a?'준비':'대기'}</b>{a&&<><p>{a.boxId} · {describe(a.kind)}</p><small>{a.reason}</small><small className="ops-time">이동·회전 {actionTiming(a,scenario).motion.toFixed(1)} s + 파지 {actionTiming(a,scenario).handling.toFixed(1)} s<br/>총 {a.seconds.toFixed(1)} s{m?` · 남은 ${Math.max(0,a.seconds-m.elapsed).toFixed(1)} s`:""}</small>{m&&<progress max={1} value={m.progress}/>}</>}{!a&&<p className="studio-arm-idle">대기 {w.cells[i].queue.length}개 <span>높이 {heights[i]} mm</span></p>}</div>;})}
   <h3 className="studio-belt-title">공용 벨트 · 순환 상태</h3>{w.pads.map((p,i)=><p key={i} data-testid={`relay-pad-${i}`}>R{i+1} → R{nextRobot(i)+1}: <b>{p.boxId||'비어 있음'}</b>{p.boxId&&<><br/><small>{p.arrived?'도착 · 적재 / 보관 판단 대기':`이동 / 예약 대기 · 최소 ${Math.max(0,p.readyAt-(sim.cursor===null?sim.time:w.time)).toFixed(1)} s`}</small></>}</p>)}
   <details className="studio-events"><summary>최근 회수 결과 · {passed}회</summary><ol className="relay-events">{w.records.filter(r=>r.kind.startsWith('receive')).slice(-6).reverse().map(r=><li key={r.step}><b>R{r.from+1} → R{r.to!+1} · {r.kind==='receive-place'?'바로 적재':'재고 보관'}</b><span>{r.boxId} · {r.finished.toFixed(1)} s</span><small>{r.reason}</small></li>)}</ol></details>
   {sim.decision&&!sim.decision.actions.length&&!running&&!travelling&&waiting>0&&<details open><summary>남은 재고의 대기 이유</summary>{sim.decision.reasons.map((r,i)=><p key={i}>{r}</p>)}</details>}{sim.error&&<p role="alert">{sim.error}</p>}
  </aside></div>
  <div className="relay-height-summary" aria-label="팔레트별 높이 도달률"><header><b>최대 {scenario.pallet.maxHeight} mm · 95% 이상 도달 {targetCount} / {ROBOT_COUNT}</b><span>높이와 용적 이용률을 함께 확인하세요. 95%에 도달해도 유효한 배치가 있으면 계속 채웁니다.</span></header>{heights.map((h,i)=><button key={i} onClick={()=>{setFocus(i);setCameraVersion(n=>n+1);}}><b style={{color:RELAY_COLORS[i]}}>R{i+1}</b><progress max={scenario.pallet.maxHeight} value={h}/><span>{h} / {scenario.pallet.maxHeight} mm · {(h/scenario.pallet.maxHeight*100).toFixed(1)}%</span></button>)}<small>{phase==='complete'?'이번 배치 반출 완료 · 남은 재고 보존':!waiting?'공급 재고 소진':!running&&!sim.busy&&sim.decision&&!sim.decision.actions.length?'한 순환에서 새 유효 후보 없음 · 남은 박스는 재고로 보존':'적재 가능한 동안 계속 진행'} · 높이 한도 안에서 지지·하중·균형·도달 조건을 유지합니다.</small></div>
  <details className="relay-advanced"><summary>박스 세트 · 알고리즘 상세 설정</summary><div className="studio-presets"><button onClick={heightDemo}>최대 높이 채우기 · 192개</button><button onClick={()=>load(relayDemo(),true)}>4대 전달 예제</button><button onClick={()=>load(relayStorageDemo(),true)}>회수 후 보관 예제</button><button onClick={()=>load(sourceScenario)}>현재 박스 세트 사용</button></div><div className="relay-setup"><label>높이 실험 상한<input aria-label="협업 최대 높이" type="number" min={400} max={2000} step={10} value={heightDraft} onChange={e=>setHeightDraft(Number(e.target.value))}/><small>mm · 높이 실험 생성 시 적용</small></label><label>박스 세트 시드<input aria-label="협업 박스 시드" type="number" value={seedDraft} onChange={e=>setSeedDraft(Number(e.target.value))}/></label><label>새 랜덤 박스 수<input aria-label="협업 전체 박스 수" type="number" min={4} max={120} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><button onClick={random}>랜덤 혼합 재고 생성</button><label>배치 정책<select aria-label="협업 배치 정책" value={algorithm} onChange={e=>setAlgorithm(e.target.value as RelayAlgorithm)}><option value="height-fill">높이 채우기 · 잔여 높이 조합</option><option value="bl">기본 배치 + 방해 검사</option><option value="greedy">제약 기반 Greedy</option><option value="rollout">후속 배치 Rollout</option></select></label><label><input aria-label="인접 로봇 전달 사용" type="checkbox" checked={transfers} onChange={e=>setTransfers(e.target.checked)}/> 벨트 순환</label><label><input aria-label="협업 초기 분배 셔플" type="checkbox" checked={shuffle} onChange={e=>setShuffle(e.target.checked)}/> 초기 분배 셔플</label><small>정책·전달·분배 변경 시 새 실행</small></div></details>
  <OperationsPanel flow={flow} sim={sim} scenario={scenario} context={context} setContext={setContext} thickness={thickness} setThickness={setThickness}/>
  <div className="studio-section-heading"><span>INVENTORY / 04</span><h2>재고와 적재 결과</h2><p>현재 입력: {scenario.name} · 초기 배정 {shuffle?`시드 ${seed}`:'입력 순서'}</p></div>
  <div className="relay-cells">{w.cells.map((cell,i)=><section key={i} className="relay-cell" style={{borderTopColor:RELAY_COLORS[i]}} aria-label={`로봇 ${i+1} 재고`}><header><h3>R{i+1} <small>→ R{nextRobot(i)+1}</small></h3><button onClick={()=>{setFocus(i);setCameraVersion(n=>n+1);}}>셀 보기</button></header><p>적재 완료 <b>{cell.placements.length}개</b> · 대기 <b>{cell.queue.length}개</b> · 높이 {heights[i]} / {scenario.pallet.maxHeight} mm</p><small>남은 높이 {scenario.pallet.maxHeight-heights[i]} mm · 용적 {(100*cell.placements.reduce((n,b)=>n+volume(b.size),0)/(scenario.pallet.width*scenario.pallet.depth*scenario.pallet.maxHeight)).toFixed(1)}%<br/>팔레트 {scenario.pallet.width} × {scenario.pallet.depth} mm · 적재 {(cell.placements.reduce((n,b)=>n+volume(b.size),0)/1e9).toFixed(3)} m³</small><div className="relay-queue">{cell.queue.map(id=>{const b=w.boxes.find(v=>v.observation.id===id)!;return <span key={id} className={b.visited.length>1?'received':''} title={`${b.observation.size.w} × ${b.observation.size.d} × ${b.observation.size.h} mm · ${b.observation.weight} kg`}>{id}{b.visited.length>1?' ↳':''}</span>;})}{!cell.queue.length&&<span>대기 없음</span>}</div><details><summary>박스별 담당과 전달 이력</summary>{w.boxes.filter(b=>b.owner===i).map(b=><p key={b.observation.id}><b>{b.observation.id}</b> · {b.status==='placed'?'적재 완료':b.status==='staged'?'공용 벨트에서 회수 대기':'자기 재고 대기'}<br/>{b.observation.size.w} × {b.observation.size.d} × {b.observation.size.h} mm · {b.observation.weight} kg · {materialInfo(b.observation).name}<br/>{b.visited.map(v=>`R${v+1}`).join(' → ')}</p>)}</details></section>)}</div>
  <details className="relay-scope"><summary>전달 규칙과 검증 범위</summary><p>자기 팔레트의 후속 배치를 막는 박스나 적재할 수 없는 박스는 공용 벨트에 내려놓습니다. 보내는 팔은 이탈 후 자기 다음 작업을 계속합니다. 받는 팔은 자신의 작업이 끝나면 벨트 구역 박스의 지지·하중·자세와 남은 재고를 검사합니다. 바로 적재해도 되면 벨트 구역에서 팔레트로 직접 옮기고, 그렇지 않으면 자기 대기 재고로 회수합니다. 한 바퀴를 돌고도 적재 상태가 같으면 대기합니다. 다른 박스의 적재로 받침이나 잔량이 바뀌면 방문한 로봇도 다시 검토합니다.</p><p>네 팔에는 개별 작업 시계가 있으며, 한 팔이 끝날 때 다른 팔을 멈추지 않습니다. 같은 벨트 구역와 겹치는 운반 상자/공구 경로만 배타 예약합니다. 벨트 구역은 각 1박스이고, 수량은 자기 재고·벨트 구역·적재 상태로 보존합니다. 반출 후 적재 이력은 출고 명세로 유지하며 3D에는 복귀한 빈 팔레트를 표시합니다. 동작 취소는 진행 중 미확정 작업만 되돌리며 완료된 벨트 구역 박스와 적재는 유지합니다.</p><p>유한 배치를 한 인입 지점에서 먼저 계측하고 네 픽업 구역에 배정합니다. 구역별 축적 재고를 선택 공급할 수 있다고 가정하며, 실제 FIFO 컨베이어의 전 박스 군집 이동은 모델링하지 않습니다. 대기 재고의 더미는 축약 표시이며 임의 접근 가능하다고 가정합니다. 기하·재질·하중·팔레트 경계 및 가상 TCP 도달을 검사합니다. 공용 벨트 폭은 900 mm, 반송 속도는 600 mm/s입니다. 로봇 작업 구역은 한 줄로 배치하고 반출 경로는 반대쪽으로 분리합니다. 실제 로봇 전체 링크의 연속 충돌·흡착·포장 변형은 미검증이고 전역 최적해를 보장하지 않습니다.</p></details>
 <footer className="studio-footer"><b>PALLET LOADING LAB</b><span>기하 제약 · 순환 이송 · 로컬 연산</span><a href="https://styles.refero.design/style/e31435dd-d4fc-4534-8a40-35a1e38ebae5" target="_blank" rel="noreferrer">Design reference / Agility Digit 5 ↗</a></footer>
 </section>;
}
