import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
async function exported(page:any){const d=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();return JSON.parse(readFileSync((await (await d).path())!,'utf8'));}

test('standing pose is solved, animated with the fixed grasp, exported and replayed consistently',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#pallet');await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();
 const s=JSON.parse(await page.getByRole('textbox',{name:'시나리오 JSON'}).inputValue());delete s.generation;s.constraints.standingHeight={enabled:false,maxRiseMm:100};s.events=[];s.arrival.pattern='ordered';s.pallet={width:200,depth:120,maxHeight:500};s.types=[{id:'TURN',name:'세워야 들어가는 박스',size:{w:300,d:200,h:100},weight:2,quantity:1,orientations:[0,90,'whd','hwd','hdw','dhw'],material:'plastic',maxLoadKg:100,maxLoadByAxis:{w:20,d:40,h:100},color:'#6bcab7'}];
 await page.getByRole('textbox',{name:'시나리오 JSON'}).fill(JSON.stringify(s));await page.getByRole('button',{name:'JSON 검증 · 적용'}).click();await page.getByRole('button',{name:'적재 실험',exact:true}).click();await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('1');await page.getByRole('button',{name:'한 단계',exact:true}).click();
 const canvas=page.getByTestId('pallet-scene').locator('canvas');await expect(canvas).toHaveAttribute('data-tool-pose','dhw',{timeout:20000});await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await expect(page.locator('.pallet-metrics').first()).toContainText('1개');
 const r=await exported(page),b=r.frame.placements[0];expect(b.orientation).toBe('dhw');expect(b.size).toEqual({w:200,d:100,h:300});expect(b.maxLoadByAxis).toEqual({w:20,d:40,h:100});expect(r.patternEvaluation.valid).toBe(true);expect(r.frame.records[0].path.fixedGrasp).toBe(true);expect(r.frame.records[0].path.points.some((p:any)=>p.label==='파지면 바깥으로 이탈')).toBe(true);
 expect(JSON.parse((await canvas.getAttribute('data-poses'))!)).toEqual([{id:b.id,orientation:b.orientation,size:b.size,position:b.position}]);await expect(page.getByLabel('내부 공간과 박스 자세')).toContainText('세워 놓은 박스 1개 / 1개');
 await page.getByRole('slider',{name:'배치 이력'}).fill('0');await expect(page.getByLabel('내부 공간과 박스 자세')).toContainText('0개 / 0개');await page.getByRole('button',{name:'현재로 돌아가기'}).click();expect((await exported(page)).frame.placements).toEqual(r.frame.placements);
 await page.getByText('팔레트 · 박스 편집',{exact:true}).click();await page.getByRole('combobox',{name:'TURN 취급 제한'}).selectOption('upright');await expect(page.getByRole('checkbox',{name:'TURN 가로축 세움 · 90°',exact:true})).toBeDisabled();await expect(page.getByRole('checkbox',{name:'TURN 가로축 세움 · 90°',exact:true})).not.toBeChecked();await page.getByRole('button',{name:'설정 적용 · 새 실행',exact:true}).click();await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('배치 중단');expect((await exported(page)).frame.placements).toHaveLength(0);expect(errors).toEqual([]);
});

test('standing button preserves stock data and random regeneration keeps permitted standing poses',async({page})=>{
 test.setTimeout(90000);await page.goto('/#pallet');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();const before=await exported(page);await page.getByRole('button',{name:'옆면 세우기 허용 · 새 실행',exact:true}).click();await expect(page.getByRole('button',{name:'Ⅱ 일시정지',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Ⅱ 일시정지',exact:true}).click();const six=await exported(page);
 expect(six.scenario.constraints).toEqual(before.scenario.constraints);expect(six.scenario.types.map(({orientations,...t}:any)=>t)).toEqual(before.scenario.types.map(({orientations,...t}:any)=>t));expect(six.scenario.types.filter((t:any)=>t.handling!=='upright').every((t:any)=>t.orientations.length===6)).toBe(true);
 await page.getByRole('button',{name:'랜덤 혼합 재고 실행',exact:true}).click();await expect(page.getByRole('button',{name:'Ⅱ 일시정지',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Ⅱ 일시정지',exact:true}).click();const random=await exported(page);expect(random.scenario.generation.seed).not.toBe(six.scenario.generation.seed);expect(random.scenario.constraints).toEqual(six.scenario.constraints);expect(random.scenario.types.filter((t:any)=>t.handling!=='upright').every((t:any)=>t.orientations.length===6)).toBe(true);
});
