import {describe,it,expect} from 'vitest';
import * as THREE from 'three';
import {observedProblem} from '../src/pallet/relay/streamPlanner';
import {addEndEffector} from '../src/pallet/relay/EndEffectorView';
import {applyPractical,resolvePlacement,DEFAULT_PRACTICAL} from '../src/pallet/relay/practical';
import {streamInventory} from '../src/pallet/relay/streamInventory';
import {inspectConstraints} from '../src/pallet/constraints';
import {createStream,advanceStream,assertStreamInventory} from '../src/pallet/relay/streamEngine';
import type {Placement,Observation,Scenario} from '../src/pallet/types';
const cube=(id:string,z:number,weight:number,capacity=100):Placement=>({id,typeId:'A',size:{w:400,d:400,h:100},weight,position:{x:500,y:500,z},orientation:0,supports:[],supportRatio:1,loadAbove:0,maxLoadKg:capacity,material:'plastic',strengthFactor:1});
const obs=(p:Placement):Observation=>({...p,status:'normal',orientationAllowed:[0]});
const check=(s:Scenario)=>{const base=cube('base',0,1),t=cube('top',100,5);return inspectConstraints(t,obs(t),[base],s.pallet,{...s.constraints,robotMode:'ideal'});};
describe('practical deployment policy',()=>{
 it('does not leak unscanned manifest specs through practical profile metadata',()=>{const s=applyPractical(streamInventory(42,8)),w=createStream(s),hidden=observedProblem(s,w);expect(hidden.scenario.types).toEqual([]);expect(hidden.scenario.practical!.profile.baseTypes).toEqual({});expect(Object.keys(s.practical!.profile.baseTypes)).toHaveLength(8);});

 it('keeps each rendered replacement tool inside its collision envelope',()=>{for(const tool of ['vacuum','jaw','cradle'] as const){const s=applyPractical(streamInventory(42,8),{...DEFAULT_PRACTICAL,tool}),g=s.constraints.gripper,group=new THREE.Group();addEndEffector(group,g,tool);const bounds=new THREE.Box3().setFromObject(group),epsilon=1e-7;expect(bounds.min.x).toBeGreaterThanOrEqual(-g.width/2000-epsilon);expect(bounds.max.x).toBeLessThanOrEqual(g.width/2000+epsilon);expect(bounds.min.z).toBeGreaterThanOrEqual(-g.depth/2000-epsilon);expect(bounds.max.z).toBeLessThanOrEqual(g.depth/2000+epsilon);expect(bounds.min.y).toBeGreaterThanOrEqual(-epsilon);expect(bounds.max.y).toBeLessThanOrEqual(g.height/1000+epsilon);}});

 it('reapplying tool settings is idempotent and preserves box mass',()=>{const original=streamInventory(42,8),cfg={...DEFAULT_PRACTICAL,tool:'jaw' as const},a=applyPractical(original,cfg),b=applyPractical(a,cfg);expect(a.constraints.gripper).toEqual(b.constraints.gripper);expect(a.types).toEqual(b.types);expect(a.types.map(t=>t.weight)).toEqual(original.types.map(t=>t.weight));const back=applyPractical(a,{...cfg,tool:'vacuum',weightPolicy:'legacy'});expect(back.constraints.gripper).toEqual(original.constraints.gripper);expect(back.constraints.heavyRule).toBe('each');});
 it('XYZ rotations require directional data and obey original permissions',()=>{const original=streamInventory(42,8);original.types[0].handling=undefined;original.types[0].orientations=[0,90,'whd'];const a=applyPractical(original);expect(a.types[0].orientations).toEqual([0,90,'whd']);expect(a.types[0].maxLoadByAxis!.d).toBeCloseTo(a.types[0].maxLoadKg!*.6);const b=applyPractical(a,{...DEFAULT_PRACTICAL,assumeAxisLoads:false});expect(b.types[0].orientations).toEqual([0,90]);expect(b.types[0].maxLoadByAxis).toBeUndefined();original.types[0].handling='upright';expect(applyPractical(original).types[0].orientations).toEqual([0,90]);});
 it('heavy-on-light passes capacity checks but fails legacy weight order',()=>{const original=streamInventory(42,8);expect(check(original).reasons.join()).toContain('무게 규칙');expect(check(applyPractical(original)).reasons).toEqual([]);const base=cube('weak',0,1,2),top=cube('heavy',100,5),s=applyPractical(original),r=inspectConstraints(top,obs(top),[base],s.pallet,{...s.constraints,robotMode:'ideal'});expect(r.reasons.join()).toContain('허용 지지하중 초과');});
 it('seeded errors are repeatable and correction obeys jig limits',()=>{const s=streamInventory(42,8),p={x:500,y:500,z:100},a=resolvePlacement(s,'box',p);expect(a).toEqual(resolvePlacement(s,'box',p));expect(a.actual).toEqual(p);expect(a.corrected).toBe(true);expect(a.rawOffsetMm).toBeGreaterThan(0);const b=resolvePlacement(s,'box',p,{...DEFAULT_PRACTICAL,jig:false});expect(b.corrected).toBe(false);expect(b.reasons.join()).toContain('잔류 회전 오차');const c=resolvePlacement(s,'box',p,{...DEFAULT_PRACTICAL,jigTravelMm:0,jigAngleDeg:0});expect(c.actual).not.toEqual(p);});
 it('failed actual pose is held and is never committed as a successful placement',()=>{const s=applyPractical(streamInventory(42,8),{...DEFAULT_PRACTICAL,jig:false,yawErrorDeg:15});s.pallet.robotLayout={count:1,architecture:'floor',floorCount:1};const w=createStream(s),b=w.boxes[0],placement={...cube(b.observation.id,0,b.observation.weight),typeId:b.observation.typeId,size:b.observation.size};b.status='reserved';b.owner=0;b.flow={enteredAt:0,measuredAt:0,passes:0,lastReason:'',checks:{}};const a={runId:w.runId,revision:0,cellVersion:0,robot:0,kind:'place' as const,boxId:b.observation.id,from:0,reason:'test',candidate:{placement} as any,seconds:1,initialCenter:{x:0,y:0,z:0}};const r=advanceStream(s,w,[{action:a,started:0,elapsed:0,progress:0}],2);expect(r.world.boxes[0].status).toBe('outfeed');expect(r.world.cells[0].placements).toHaveLength(0);expect(r.world.records).toHaveLength(0);expect(r.world.boxes[0].execution!.reasons.length).toBeGreaterThan(0);expect(assertStreamInventory(r.world,r.motions)).toBe(true);});
});
