import { test,expect } from '@playwright/test';
import { readFileSync,writeFileSync } from 'node:fs';
async function exported(page:any){const d=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();return JSON.parse(readFileSync((await (await d).path())!,'utf8'));}
async function arm(page:any){return JSON.parse((await page.getByTestId('pallet-scene').locator('canvas').getAttribute('data-arm'))!);}

test('articulated arm follows, pauses and tilts with the tool; visualization controls never rewrite packing results',async({page})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#pallet');await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();const s=JSON.parse(await page.getByRole('textbox',{name:'시나리오 JSON'}).inputValue());delete s.generation;s.constraints.standingHeight={enabled:false,maxRiseMm:100};s.arrival.pattern='ordered';s.events=[];s.pallet={width:200,depth:120,maxHeight:500};s.types=[{id:'TURN',name:'세움 동작',size:{w:300,d:200,h:100},weight:2,quantity:1,orientations:[0,90,'whd','hwd','hdw','dhw'],material:'plastic',maxLoadKg:100,color:'#6bcab7'}];await page.getByRole('textbox',{name:'시나리오 JSON'}).fill(JSON.stringify(s));await page.getByRole('button',{name:'JSON 검증 · 적용'}).click();await page.getByRole('button',{name:'적재 실험',exact:true}).click();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('1');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();
 const canvas=page.getByTestId('pallet-scene').locator('canvas');await expect(canvas).toHaveAttribute('data-arm-visible','true');const initial=await arm(page);expect(initial.errorMm).toBeLessThan(.01);await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect.poll(async()=>Math.abs((await arm(page)).target.z-initial.target.z)).toBeGreaterThan(25);
 await page.getByRole('button',{name:'Ⅱ 일시정지',exact:true}).click();const paused=await arm(page);await page.waitForTimeout(250);expect((await arm(page)).elbow).toEqual(paused.elbow);await page.getByRole('button',{name:'계속 재생',exact:true}).click();await expect(canvas).toHaveAttribute('data-tool-pose','dhw',{timeout:20000});await expect.poll(async()=>Math.abs((await arm(page)).normal[1])).toBeLessThan(.5);await page.getByRole('button',{name:'Ⅱ 일시정지',exact:true}).click();const tilted=await arm(page);expect(tilted.reachable).toBe(true);expect(tilted.errorMm).toBeLessThan(.01);expect(tilted.elbow).not.toEqual(initial.elbow);await page.getByLabel('후보',{exact:true}).uncheck();await page.getByTestId('pallet-scene').screenshot({path:'docs/pallet-robot-arm-tilt.png'});
 await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'계속 재생',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료');const r=await exported(page);expect(r.frame.placements[0].orientation).toBe('dhw');
 await page.getByLabel('로봇팔',{exact:true}).uncheck();await expect(canvas).toHaveAttribute('data-arm-visible','false');await expect(page.getByLabel('로봇팔 표시 상태')).toHaveCount(0);await page.getByLabel('로봇팔',{exact:true}).check();await page.getByText('가상 로봇팔 · 길이와 설치 위치',{exact:true}).click();await page.getByRole('spinbutton',{name:'표시 로봇팔 상완 길이 mm'}).fill('200');await page.getByRole('spinbutton',{name:'표시 로봇팔 전완 길이 mm'}).fill('200');await expect(page.getByLabel('로봇팔 표시 상태')).toContainText('도달 불가');const short=await arm(page);expect(short.errorMm).toBeGreaterThan(100);const length=(a:any,b:any)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);expect(length(short.shoulder,short.elbow)).toBeCloseTo(200);expect(length(short.elbow,short.wrist)).toBeCloseTo(200);expect((await exported(page)).frame.placements).toEqual(r.frame.placements);await page.getByRole('button',{name:'표시 로봇팔 기본값'}).click();await expect.poll(async()=>(await arm(page)).reachable).toBe(true);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await page.getByRole('button',{name:'로봇 작업셀',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByTestId('pallet-scene').screenshot({path:`docs/pallet-robot-arm-${width}.png`});}
 await page.getByText('적재 제약 · 환경',{exact:true}).click();await page.getByRole('combobox',{name:'적재 환경',exact:true}).selectOption('ideal');await page.getByRole('button',{name:'설정 적용 · 새 실행',exact:true}).click();await expect(canvas).toHaveAttribute('data-arm-visible','false');await expect(page.getByLabel('로봇팔 표시 상태')).toHaveCount(0);expect(errors).toEqual([]);
});

test('the robot cell shows the same real mixed packing result with articulated geometry',async({page})=>{
 test.setTimeout(150000);await page.goto('/?palletDemo=robot#pallet');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await expect(page.locator('.pallet-status')).toContainText('남은 재고 배치 불가',{timeout:120000});const r=await exported(page);expect(r.metrics.count).toBe(16);expect(r.metrics.height).toBe(964);expect(r.patternEvaluation.valid).toBe(true);const pose=await arm(page);expect(pose.reachable).toBe(true);await page.getByLabel('후보',{exact:true}).uncheck();await page.getByRole('button',{name:'로봇 작업셀',exact:true}).click();await page.getByTestId('pallet-scene').screenshot({path:'docs/pallet-robot-arm-mixed.png'});writeFileSync('docs/pallet-robot-arm-browser.json',JSON.stringify({verifiedAt:new Date().toISOString(),metrics:r.metrics,pose,patternEvaluation:r.patternEvaluation},null,2));
});
