import { openResearch } from './pallet-research';
import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
async function readRun(page:any){const wait=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();return JSON.parse(readFileSync((await (await wait).path())!,'utf8'));}
test('chooses the base before the unstable arrival and preserves stock across pause, cancel and replay',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await openResearch(page);await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();const s=JSON.parse(await page.getByRole('textbox',{name:'시나리오 JSON'}).inputValue());delete s.generation;s.id='stock-fixture';s.name='받침 선행 검사';s.supplyMode='arrival';s.pallet={width:503,depth:407,maxHeight:900};s.arrival.pattern='ordered';s.types=[
 {id:'tall',name:'긴 박스',size:{w:177,d:211,h:417},weight:7,quantity:1,orientations:[0,90],material:'plastic',maxLoadKg:10,color:'#e8b86a'},
 {id:'base',name:'넓고 강한 종이 받침',size:{w:503,d:407,h:97},weight:4,quantity:1,orientations:[0],material:'paper',maxLoadKg:100,color:'#6bcab7'}];await page.getByRole('textbox',{name:'시나리오 JSON'}).fill(JSON.stringify(s));await page.getByRole('button',{name:'JSON 검증 · 적용'}).click();await page.getByRole('button',{name:'적재 실험',exact:true}).click();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.getByRole('alert')).toContainText('1번째 박스 배치 실패');
 await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('stock-select');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await expect(page.locator('.pallet-current h3')).toHaveText('base-01');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('1');await page.getByRole('button',{name:'한 단계',exact:true}).click();await page.getByRole('button',{name:'Ⅱ 일시정지'}).click();await page.waitForTimeout(200);await expect(page.locator('.pallet-metrics').first()).toContainText('0개');await page.getByRole('button',{name:'실행 취소',exact:true}).click();expect((await readRun(page)).frame.placements).toHaveLength(0);
 await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await expect(page.locator('.pallet-current h3')).toHaveText('tall-01');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료');const run=await readRun(page);expect(run.metrics.complete).toBe(true);expect(run.frame.records.map((r:any)=>r.observation.typeId)).toEqual(['base','tall']);expect(run.frame.placements[1].supports[0].id).toBe('base-01');expect(run.frame.placements[1].position.z).toBe(97);expect(run.scenario.types).toEqual(s.types);expect(run.metrics.loadUtilization).toBeLessThan(1);
 await page.getByRole('button',{name:'이전 프레임'}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await page.getByRole('button',{name:'현재로 돌아가기'}).click();expect((await readRun(page)).frame.placements).toEqual(run.frame.placements);await page.screenshot({path:'docs/pallet-stock-base-first.png',fullPage:true});expect(errors).toEqual([]);
});
test('default mixed stock continues past the old failure, inspects every deferred type and conserves quantity',async({page})=>{
 test.setTimeout(180000);await openResearch(page);await expect(page.getByRole('combobox',{name:'박스 공급 방식'})).toHaveValue('stock-select');await expect(page.locator('.pallet-heading')).toContainText('이전 방식 비교');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('남은 재고 배치 불가',{timeout:150000});await expect(page.locator('.pallet-metrics').first()).toContainText('14개');await expect(page.getByRole('alert')).toContainText('16개 남은 재고');const run=await readRun(page);expect(run.scenario.supplyMode).toBe('stock-select');expect(run.frame.records.at(-1).analysis.stockSelection.checkedTypes).toBe(16);expect(Object.values(run.frame.records.at(-1).remaining).reduce((a:any,b:any)=>a+b,0)).toBe(16);expect(new Set(run.frame.placements.map((b:any)=>b.id)).size).toBe(14);expect(run.frame.records.slice(0,-1).every((r:any)=>r.analysis.selectedBoxId===r.observation.id)).toBe(true);expect(run.frame.placements[0].handling).not.toBe('no-top-load');await page.getByText('선택한 적재 순서 · 프레임 선택',{exact:true}).click();await expect(page.locator('.pallet-arrival-list button')).toHaveCount(15);
 for(const width of [320,1366]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/pallet-stock-${width}.png`,fullPage:true});}
});
test('regenerating random stock retains selectable mode and reproduces the chosen order',async({page})=>{
 await openResearch(page);await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await expect(page.getByRole('button',{name:'새 재고 무작위 생성'})).toBeVisible();
 await expect(page.getByRole('button',{name:'입고 순서만 랜덤',exact:true})).toBeDisabled();await page.getByRole('spinbutton',{name:'세트 생성 시드',exact:true}).fill('913');await page.getByRole('spinbutton',{name:'랜덤 전체 수량',exact:true}).fill('7');await page.getByRole('spinbutton',{name:'랜덤 가로 최소 mm'}).fill('217');await page.getByRole('spinbutton',{name:'랜덤 가로 최대 mm'}).fill('419');await page.getByRole('spinbutton',{name:'랜덤 깊이 최소 mm'}).fill('173');await page.getByRole('spinbutton',{name:'랜덤 깊이 최대 mm'}).fill('347');await page.getByRole('spinbutton',{name:'랜덤 높이 최대 mm'}).fill('191');await page.getByRole('button',{name:'이 시드로 세트 생성',exact:true}).click();await expect(page.getByRole('combobox',{name:'박스 공급 방식'})).toHaveValue('stock-select');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toHaveText(/입고 처리 완료|남은 재고 배치 불가/,{timeout:30000});const first=await readRun(page);expect(first.frame.placements.length).toBeGreaterThan(0);expect(first.frame.placements.length+Object.values(first.frame.records.at(-1).remaining).reduce((a:any,b:any)=>a+b,0)).toBe(7);await page.getByRole('button',{name:'초기화',exact:true}).click();await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toHaveText(/입고 처리 완료|남은 재고 배치 불가/,{timeout:30000});const second=await readRun(page);expect(second.frame.records.map((r:any)=>r.observation.id)).toEqual(first.frame.records.map((r:any)=>r.observation.id));expect(second.frame.placements).toEqual(first.frame.placements);
});
