import { describe,it,expect } from 'vitest';
import { sampleSpecs,packagingScenario,boxType,permittedOrientations,localMassCenter,type BoxSpec } from '../src/pallet/packaging/spec';
import { PACKAGE_SETTINGS,planPackaging,virtualSequences,robustStatistics,futureSpace,type PackageInput } from '../src/pallet/packaging/planner';
import { newSession,preview,commit,applyEvent,remainingInventory } from '../src/pallet/packaging/session';
import { inspectConstraints } from '../src/pallet/constraints';
import { virtualObservation } from '../src/pallet/remainingSites';
import { calculateLoads,oriented,contactsFor } from '../src/pallet/geometry';
import { reachability } from '../src/pallet/packaging/robot';
import type { Placement,Orientation } from '../src/pallet/types';
const spec=(extra:Partial<BoxSpec>={}):BoxSpec=>({...sampleSpecs()[1],id:'T',length:200,width:200,height:200,grossWeight:2,quantity:1,maxTopLoad:100,centerOfGravity:{x:100,y:100,z:100},...extra});
const placed=(s:BoxSpec,id:string,x=0,y=0,z=0,o:Orientation=0):Placement=>({id,typeId:s.id,size:oriented(boxType(s).size,o),weight:s.grossWeight,packaging:s,position:{x,y,z},orientation:o,supports:[],supportRatio:1,loadAbove:0});
function inspect(s:BoxSpec,b:Placement,others:Placement[]=[],scenario=packagingScenario([s])){return inspectConstraints(b,virtualObservation(boxType(s),b.id),others,scenario.pallet,scenario.constraints);}
describe('BoxSpec hard constraints and causal planner',()=>{
 it('filters pitch/roll before generation and rejects injected upright pose',()=>{const s=spec({allowedOrientations:['XYZ','YXZ','XZY']});expect(permittedOrientations(s)).toEqual([0,90]);expect(inspect(s,placed(s,'x',0,0,0,'whd')).reasons.join()).toMatch(/Orientation/);});
 it('does not stack on nonstackable supports',()=>{const bottom=placed(spec({stackable:false}),'bottom');expect(inspect(spec(),placed(spec(),'top',0,0,200),[bottom]).reasons.join()).toMatch(/위 적재 금지/);});
 it('rejects cumulative top load above rating',()=>{const bottom=placed(spec({maxTopLoad:1}),'bottom');expect(inspect(spec(),placed(spec(),'top',0,0,200),[bottom]).reasons.join()).toMatch(/하중 초과/);});
 it('uses per-box minimum support instead of global default',()=>{const bottom=placed(spec(),'bottom'),s=spec({minSupportRatio:.9});const result=inspect(s,placed(s,'top',40,0,200),[bottom]);expect(result.placement.supportRatio).toBeCloseTo(.8);expect(result.reasons.join()).toMatch(/80.0%.*90.0%/);});
 it('rejects pallet boundary overhang and below-floor coordinates',()=>{expect(inspect(spec(),placed(spec(),'x',1190)).reasons.join()).toMatch(/경계/);expect(inspect(spec(),placed(spec(),'x',0,0,-2)).reasons.join()).toMatch(/바닥 아래/);});
 it('rejects overlapping boxes',()=>{expect(inspect(spec(),placed(spec(),'x',100),[placed(spec(),'bottom')]).reasons.join()).toMatch(/겹침/);});
 it('uses 3D reach including height',()=>{expect(reachability({x:0,y:0,z:1500},{base:{x:0,y:0,z:0},minReach:0,maxReach:1000,approach:100}).valid).toBe(false);const s=packagingScenario([spec()]);s.constraints.packagingRobot!.maxReach=100;expect(inspect(spec(),placed(spec(),'x'),[],s).reasons.join()).toMatch(/거리|도달/);});
 it('transmits own plus accumulated load recursively by contact area',()=>{const left=placed(spec({length:100,centerOfGravity:{x:50,y:100,z:100}}),'L'),right=placed(spec({length:300,centerOfGravity:{x:150,y:100,z:100}}),'R',100),bridge=placed(spec({length:400,grossWeight:8,centerOfGravity:{x:200,y:100,z:100}}),'bridge',0,0,200),upper=placed(spec({grossWeight:4}),'upper',0,0,400);bridge.supports=contactsFor(bridge,[left,right],.01);upper.supports=contactsFor(upper,[bridge],.01);const loads=calculateLoads([left,right,bridge,upper]);expect(loads.bridge).toBe(4);expect(loads.L).toBe(3);expect(loads.R).toBe(9);});
 it('transforms asymmetric CoG for yaw',()=>{const s=spec({centerOfGravity:{x:140,y:70,z:90}});expect(localMassCenter(s,90)).toEqual({x:70,y:60,z:90});});
 it('rejects a CoG outside the support polygon even with enough area',()=>{const s=spec({centerOfGravity:{x:195,y:100,z:100},minSupportRatio:.7}),bottom=placed(spec(),'base');expect(inspect(s,placed(s,'top',50,0,200),[bottom]).reasons.join()).toMatch(/평형|지지/);});
 it('rejects a blocked side grasp corridor',()=>{const s=spec({graspableFaces:['RIGHT']}),obstacle=placed(spec(),'wall',210);expect(inspect(s,placed(s,'incoming'),[obstacle]).reasons.join()).toMatch(/corridor|경로 간섭/);});
 it('rejects maximum stack layers',()=>{const bottom=placed(spec({maxStackLayers:1}),'bottom');expect(inspect(spec(),placed(spec(),'top',0,0,200),[bottom]).reasons.join()).toMatch(/적층 2/);});
 it('preserves an XL free region more effectively than greedy on a blocking fixture',()=>{
  const small=spec({id:'S'}),large=spec({id:'XL',length:400,width:400,height:200,grossWeight:10,centerOfGravity:{x:200,y:200,z:100}}),s=packagingScenario([small,large]);s.pallet={width:600,depth:400,maxHeight:200};
  const input:PackageInput={scenario:s,placements:[placed(small,'base')],current:virtualObservation(boxType(small),'incoming'),remaining:{XL:1},method:'greedy',step:1,settings:structuredClone(PACKAGE_SETTINGS)};
  const greedy=planPackaging(input),future=planPackaging({...input,method:'future'}),g=greedy.candidates.find(c=>c.id===greedy.selectedId)!,f=future.candidates.find(c=>c.id===future.selectedId)!;
  expect(g).toBeDefined();expect(f).toBeDefined();expect(futureSpace(f.stack,input).value).toBeGreaterThan(futureSpace(g.stack,input).value);
 });
 it('keeps confirmed placements when a damaged box triggers replanning',()=>{let s=newSession(packagingScenario([spec({quantity:3})]));s=commit(s,preview(s,'greedy',PACKAGE_SETTINGS));expect(s.placements.length).toBe(1);const before=JSON.stringify(s.placements),next=applyEvent(s,{kind:'damaged'});expect(JSON.stringify(next.placements)).toBe(before);expect(next.replanCount).toBe(1);expect(preview(next,'robust',PACKAGE_SETTINGS).selectedId).toBeNull();expect(commit(next,preview(next,'greedy',PACKAGE_SETTINGS)).records.at(-1)?.status).toBe('damaged');});
 it('replans wrong weight, dimensions, and incoming type without changing placed boxes',()=>{let s=newSession(packagingScenario([spec({quantity:3}),spec({id:'U'})]));s=commit(s,preview(s,'greedy',PACKAGE_SETTINGS));const before=JSON.stringify(s.placements);for(const event of [{kind:'weight',weight:19},{kind:'dimensions',length:240,width:230,height:150},{kind:'type',typeId:'U'},{kind:'missing'}] as const){s=applyEvent(s,event);expect(JSON.stringify(s.placements)).toBe(before);}expect(s.replanCount).toBe(4);});
 it('produces same decisions for identical seeds without passing future queue to planner',()=>{const s=newSession(packagingScenario([spec({quantity:3})]));const a=preview(s,'robust',PACKAGE_SETTINGS),b=preview(s,'robust',PACKAGE_SETTINGS);expect(a.selectedId).toBe(b.selectedId);expect(a.sequences).toEqual(b.sequences);expect(a.candidates.map(c=>c.score)).toEqual(b.candidates.map(c=>c.score));});
 it('samples only remaining inventory with requested counts and depth',()=>{const ss={...PACKAGE_SETTINGS,samples:50 as const,depth:10 as const};const samples=virtualSequences({A:2,B:1},ss);expect(samples).toHaveLength(50);for(const seq of samples){expect(seq).toHaveLength(3);expect(seq.filter(v=>v==='A')).toHaveLength(2);}const s=newSession(packagingScenario());expect(Object.values(remainingInventory(s)).reduce((a,b)=>a+b,0)).toBe(s.items.length-1);});
 it('scores bottom decile and reports signed contributions summing to total',()=>{const stats=robustStatistics([0,1,1,1,1,1,1,1,1,1]);expect(stats.worst).toBe(0);expect(stats.robust).toBeCloseTo(.63);const plan=preview(newSession(packagingScenario([spec({quantity:2})])),'robust',PACKAGE_SETTINGS);for(const c of plan.candidates){if(c.valid)expect(Object.values(c.terms).reduce((a,b)=>a+b,0)).toBeCloseTo(c.score!);else {expect(c.score).toBeNull();expect(c.terms).toEqual({});}}});
});
