import { openResearch } from './pallet-research';
import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
test.describe.configure({mode:'parallel'});
test('pallet scene, full run, inspection, replay, physics and exports',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await expect(page.getByTestId('pallet-scene')).toHaveAttribute('data-renderer','webgl');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();
 await page.getByRole('combobox',{name:'입고 시나리오'}).selectOption('identical');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');
 const c=page.locator('.pallet-scene canvas').first(),r=(await c.boundingBox())!;await expect(c).toHaveAttribute('data-boxes',/A-/);const point=JSON.parse((await c.getAttribute('data-boxes'))!)[0];await c.click({position:{x:point.x,y:point.y}});await expect(page.getByRole('heading',{name:'확정 박스 검사'})).toBeVisible();await page.getByRole('button',{name:'판단으로 돌아가기'}).click();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+60,r.y+r.height/2+20,{steps:6});await page.mouse.up();await expect(c).toHaveAttribute('data-camera',/.+/);
 await page.getByRole('button',{name:'평면',exact:true}).click();await page.waitForTimeout(350);await page.screenshot({path:'docs/pallet-first-box.png',fullPage:true});
 await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료',{timeout:30000});await expect(page.locator('.pallet-metrics').first()).toContainText('12개');
 await page.getByRole('button',{name:'물리 검증 실행',exact:true}).click();await expect(page.locator('.pallet-physics-result')).toContainText('설정한 조건에서 안정',{timeout:20000});
 await page.getByRole('slider',{name:'배치 이력'}).fill('5');await expect(page.locator('.pallet-metrics').first()).toContainText('5개');await page.getByRole('button',{name:'현재로 돌아가기'}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('12개');
 for(const [button,suffix] of [['실행 JSON 저장','.json'],['화면 PNG 저장','.png']] as const){const pending=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const saved=await pending;expect(saved.suggestedFilename()).toContain(suffix);const bytes=readFileSync((await saved.path())!);if(suffix==='.json')expect(JSON.parse(bytes.toString()).metrics.count).toBe(12);else expect([...bytes.subarray(0,8)]).toEqual([137,80,78,71,13,10,26,10]);}
 await page.getByRole('button',{name:'초기화',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('0개');expect(await page.getByRole('combobox',{name:'보관 실행'}).locator('option').count()).toBeGreaterThan(1);expect(errors).toEqual([]);
});
test('comparison runs on common inputs and exports CSV',async({page})=>{await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByRole('combobox',{name:'입고 시나리오'}).selectOption('identical');await page.getByRole('button',{name:'알고리즘 비교',exact:true}).click();await page.getByRole('spinbutton',{name:'반복 시드 수'}).fill('1');await page.getByRole('button',{name:'같은 입력으로 비교'}).click();await expect(page.getByText('비교 완료',{exact:true})).toBeVisible({timeout:60000});await expect(page.getByTestId('pallet-scene')).toHaveCount(3);await expect(page.locator('.pallet-results tbody tr')).toHaveCount(3);const d=page.waitForEvent('download');await page.getByRole('button',{name:'비교 CSV 저장'}).click();const saved=await d;expect(saved.suggestedFilename()).toBe('pallet-comparison.csv');const contents=readFileSync((await saved.path())!,'utf8');expect(contents.trim().split(/\r?\n/)).toHaveLength(4);expect(contents).toContain('work_s');});
test('invalid imports, blocked state and stale worker reset',async({page})=>{await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByRole('combobox',{name:'선택 알고리즘'}).selectOption('rollout');await page.getByRole('button',{name:'초기화',exact:true}).click();await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled({timeout:45000});await expect(page.locator('.pallet-metrics').first()).toContainText('0개');await page.getByRole('combobox',{name:'입고 시나리오'}).selectOption('impossible');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'▶ 자동 적재'}).click();await expect(page.getByRole('alert')).toContainText('2번째 박스 배치 실패');await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();await page.getByRole('textbox',{name:'시나리오 JSON'}).fill('{"version":1}');await page.getByRole('button',{name:'JSON 검증 · 적용'}).click();await expect(page.locator('.pallet-notice')).toContainText('단위');});
test('responsive layout preserves accessible controls',async({page})=>{await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');for(const width of [320,375,414,768,1366]){await page.setViewportSize({width,height:width===1366?768:900});await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/pallet-${width}.png`,fullPage:width!==1366});}});
test('pause freezes motion, cancel preserves confirmed state and rapid clicks cannot double commit',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByRole('combobox',{name:'입고 시나리오'}).selectOption('identical');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('1');await page.getByRole('button',{name:'한 단계',exact:true}).click();await page.getByRole('button',{name:'Ⅱ 일시정지'}).click();await page.waitForTimeout(350);await expect(page.locator('.pallet-metrics').first()).toContainText('0개');await expect(page.locator('.pallet-status')).toContainText('동작 일시정지');await page.getByRole('button',{name:'실행 취소',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('0개');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await page.getByRole('button',{name:'한 단계',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await expect(page.locator('.pallet-metrics').first()).toContainText('2개');await page.waitForTimeout(300);await expect(page.locator('.pallet-metrics').first()).toContainText('2개');expect(errors).toEqual([]);});
test('comparison cancellation keeps completed results and mobile comparison stays contained',async({page})=>{await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByRole('button',{name:'알고리즘 비교',exact:true}).click();await page.getByRole('button',{name:'같은 입력으로 비교'}).click();await expect(page.locator('.pallet-results tbody tr')).toHaveCount(2,{timeout:15000});await page.getByRole('button',{name:'비교 취소',exact:true}).click();await expect(page.getByText('취소됨 · 완료된 실행은 보존했습니다.',{exact:true})).toBeVisible();await expect(page.locator('.pallet-results tbody tr')).toHaveCount(2);await page.setViewportSize({width:320,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('materials, cumulative load and always-on inventory are applied to real placements and exports',async({page})=>{
 await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await expect(page.getByRole('combobox',{name:'선택 알고리즘'})).toHaveValue('greedy');await expect(page.getByLabel('현재 적용된 과제 검사')).toContainText('이전 잔량 평가 · 연구용');
 await page.getByRole('combobox',{name:'입고 시나리오'}).selectOption('materials');await page.getByRole('combobox',{name:'선택 알고리즘'}).selectOption('greedy');
 await page.getByText('팔레트 · 박스 편집',{exact:true}).click();await expect(page.getByRole('combobox',{name:'P 재질',exact:true})).toHaveValue('plastic');await page.getByRole('spinbutton',{name:'P 허용 지지하중 kg'}).fill('100');await page.getByRole('spinbutton',{name:'P 강도 보정 비율'}).fill('0.8');await page.getByRole('spinbutton',{name:'P 마찰 계수'}).fill('0.7');await expect(page.locator('.pallet-material-fields').first()).toContainText('입력값');await expect(page.locator('.pallet-material-fields').first()).toContainText('64.0 kg');
 await page.getByRole('button',{name:'설정 적용 · 새 실행'}).click();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'▶ 자동 적재'}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료',{timeout:30000});await expect(page.locator('.pallet-metrics').first()).toContainText('16개');await expect(page.locator('.pallet-metrics').first()).toContainText('400mm');await expect(page.locator('.pallet-safety-summary')).toContainText('0개');
 await page.getByRole('button',{name:'물리 검증 실행',exact:true}).click();await expect(page.locator('.pallet-physics-result')).not.toHaveText('아직 실행하지 않음');await expect(page.locator('.pallet-physics-result')).not.toHaveText('복제 장면 계산 중…',{timeout:20000});
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();const saved=await pending,data=JSON.parse(readFileSync((await saved.path())!,'utf8'));expect(data.metrics.complete).toBe(true);expect(data.metrics.unknownCapacity).toBe(0);expect(data.metrics.loadUtilization).toBeLessThan(1);const placements=data.frame.placements;expect(placements.filter((b:any)=>b.material==='paper').every((b:any)=>b.supports.length&&b.supports.every((s:any)=>placements.find((p:any)=>p.id===s.id).material==='plastic'))).toBe(true);expect(data.physics.poses.filter((p:any)=>p.id.startsWith('P-')).every((p:any)=>p.friction===.7)).toBe(true);
 await page.screenshot({path:'docs/pallet-materials.png',fullPage:true});
});

test('ideal 30-box reference exposes saved frames, reactions and display-only layer separation',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await expect(page.getByRole('combobox',{name:'입고 시나리오'})).toHaveValue('field');await page.getByRole('combobox',{name:'입고 시나리오'}).selectOption('reference');await expect(page.getByTestId('pallet-scene')).toHaveAttribute('data-model','ideal');
 await page.getByRole('combobox',{name:'선택 알고리즘'}).selectOption('greedy');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료',{timeout:30000});await expect(page.locator('.pallet-metrics').first()).toContainText('30개');await expect(page.locator('.pallet-metrics').first()).toContainText('600mm');
 const downloadRun=async()=>{const wait=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();return JSON.parse(readFileSync((await (await wait).path())!,'utf8'));};
 const original=await downloadRun();expect(original.scenario.constraints.robotMode).toBe('ideal');expect(original.metrics.workSeconds).toBe(0);const top=original.frame.placements.find((b:any)=>b.supports.length&&b.supports[0].forcePoint);expect(top).toBeTruthy();await page.getByText('단계별 관측 · 기록',{exact:true}).click();await page.getByRole('button',{name:top.id,exact:true}).click();await expect(page.locator('.pallet-inspector')).toContainText('반력 비중');await expect(page.locator('.pallet-inspector')).toContainText('작용점');
 await page.getByRole('checkbox',{name:'층 분리',exact:true}).check();await expect(page.getByTestId('pallet-scene')).toHaveAttribute('data-exploded','true');const separated=await downloadRun();expect(separated.frame.placements).toEqual(original.frame.placements);await page.getByRole('checkbox',{name:'층 분리',exact:true}).uncheck();
 await page.getByRole('button',{name:'이전 프레임',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('29개');await page.getByRole('button',{name:'다음 프레임',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('30개');await page.getByText('관측된 도착 순서 · 프레임 선택',{exact:true}).click();await expect(page.locator('.pallet-arrival-list button')).toHaveCount(30);await page.getByRole('button',{name:/^7번째 프레임 /}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('7개');await expect(page.getByRole('slider',{name:'배치 이력'})).toHaveValue('7');await expect(page.locator('.pallet-arrival-list button[aria-pressed=true]')).toContainText('7');await page.getByRole('button',{name:'현재로 돌아가기'}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('30개');
 await page.setViewportSize({width:1366,height:900});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'docs/pallet-ideal-30.png',fullPage:true});expect(errors).toEqual([]);
});
test('random box-set seed and arrival seed are independent, reproducible and validated',async({page})=>{
 await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('spinbutton',{name:'세트 생성 시드',exact:true}).fill('123');await page.getByRole('combobox',{name:'랜덤 박스 구성'}).selectOption('repeated');await page.getByRole('spinbutton',{name:'랜덤 종류 수',exact:true}).fill('3');await page.getByRole('spinbutton',{name:'랜덤 전체 수량',exact:true}).fill('12');await page.getByRole('spinbutton',{name:'랜덤 가로 최소 mm'}).fill('200');await page.getByRole('spinbutton',{name:'랜덤 깊이 최소 mm'}).fill('200');await page.getByRole('spinbutton',{name:'랜덤 높이 최대 mm'}).fill('180');await page.getByRole('button',{name:'이 시드로 세트 생성',exact:true}).click();await expect(page.locator('.pallet-random-controls')).toHaveAttribute('data-state','success');
 const readScenario=async()=>{await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();const wait=page.waitForEvent('download');await page.getByRole('button',{name:'시나리오 JSON 저장',exact:true}).click();const result=JSON.parse(readFileSync((await (await wait).path())!,'utf8'));await page.getByRole('button',{name:'적재 실험',exact:true}).click();return result;};
 const first=await readScenario();expect(first.generation.seed).toBe(123);expect(first.types.reduce((a:number,b:any)=>a+b.quantity,0)).toBe(12);await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('button',{name:'입고 순서만 랜덤',exact:true}).click();const reordered=await readScenario();expect(reordered.types).toEqual(first.types);expect(reordered.arrival.seed).not.toBe(first.arrival.seed);
 await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('button',{name:'이 시드로 세트 생성',exact:true}).click();const again=await readScenario();expect(again.types).toEqual(first.types);expect(again.arrival.seed).toBe(reordered.arrival.seed);
 await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('spinbutton',{name:'랜덤 전체 수량',exact:true}).fill('2');await page.getByRole('button',{name:'이 시드로 세트 생성',exact:true}).click();await expect(page.locator('.pallet-random-controls')).toHaveAttribute('data-state','error');await expect(page.locator('.pallet-random-controls [role=alert]')).toBeVisible();const afterError=await readScenario();expect(afterError.types).toEqual(first.types);
});
test('expanded random controls and frames stay usable at supported viewport widths',async({page})=>{
 await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('combobox',{name:'선택 알고리즘'}).selectOption('greedy');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await page.getByText('관측된 도착 순서 · 프레임 선택',{exact:true}).click();
 for(const width of [320,375,414,768,1366]){await page.setViewportSize({width,height:width===1366?768:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole('button',{name:'랜덤 세트 생성',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/^1번째 프레임 /})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/pallet-ideal-expanded-${width}.png`,fullPage:width!==1366});}
 await page.goto('/docs/RandomControls.preview.html');await page.setViewportSize({width:1366,height:900});await expect(page.locator('.states>section')).toHaveCount(8);await page.screenshot({path:'docs/pallet-random-states.png',fullPage:true});
});

test('finite random inventory draws the next box per step, displays probabilities and replays exactly',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByRole('combobox',{name:'선택 알고리즘'}).selectOption('greedy');await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('combobox',{name:'입고 추첨 방식'}).selectOption('random-draw');await page.getByRole('spinbutton',{name:'세트 생성 시드',exact:true}).fill('123');await page.getByRole('spinbutton',{name:'무작위 입고 시드',exact:true}).fill('999');await page.getByRole('combobox',{name:'랜덤 박스 구성'}).selectOption('repeated');await page.getByRole('spinbutton',{name:'랜덤 종류 수',exact:true}).fill('3');await page.getByRole('spinbutton',{name:'랜덤 전체 수량',exact:true}).fill('12');await page.getByRole('spinbutton',{name:'랜덤 가로 최소 mm'}).fill('200');await page.getByRole('spinbutton',{name:'랜덤 깊이 최소 mm'}).fill('200');await page.getByRole('spinbutton',{name:'랜덤 높이 최대 mm'}).fill('180');await page.getByRole('button',{name:'이 시드로 세트 생성',exact:true}).click();await expect(page.locator('.pallet-policy-note')).toContainText('매 단계 무작위 입고');await expect(page.locator('.pallet-inventory thead th')).toHaveText(['종류','잔량','다음 추첨']);
 const counts=()=>page.locator('.pallet-inventory tbody tr td:first-of-type').allTextContents();const quantities=await counts();expect(quantities.reduce((n,t)=>n+parseInt(t),0)).toBe(11);const chance=await page.locator('.pallet-inventory td[aria-label$="다음 추첨 확률"]').allTextContents();expect(Math.abs(chance.reduce((n,t)=>n+parseFloat(t),0)-100)).toBeLessThan(.2);const first=(await page.locator('.pallet-current h3').textContent())!;await page.getByRole('checkbox',{name:'층 분리',exact:true}).check();await page.getByRole('checkbox',{name:'층 분리',exact:true}).uncheck();await expect(page.locator('.pallet-current h3')).toHaveText(first);
 await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await expect(page.locator('.pallet-current h3')).not.toHaveText(first);await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toHaveText(/입고 처리 완료|배치 중단/,{timeout:30000});
 const readRun=async()=>{const wait=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();return JSON.parse(readFileSync((await (await wait).path())!,'utf8'));};const run=await readRun();expect(run.scenario.arrival).toEqual({seed:999,pattern:'random-draw'});expect(run.scenario.generation.seed).toBe(123);expect(run.frame.records[0].observation.id).toBe(first);expect(run.metrics.workSeconds).toBe(0);expect(run.frame.records.at(-1).remaining).toBeTruthy();
 const order=run.frame.records.map((r:any)=>r.observation.id);await page.getByText('관측된 도착 순서 · 프레임 선택',{exact:true}).click();await page.getByRole('button',{name:/^1번째 프레임 /}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await page.getByRole('button',{name:'현재로 돌아가기'}).click();expect((await readRun()).frame.records.map((r:any)=>r.observation.id)).toEqual(order);
 await page.getByRole('button',{name:'초기화',exact:true}).click();await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toHaveText(/입고 처리 완료|배치 중단/,{timeout:30000});expect((await readRun()).frame.records.map((r:any)=>r.observation.id)).toEqual(order);expect(errors).toEqual([]);
});
test('one click randomizes inventory and arrivals, resets active state and remains contained on mobile',async({page})=>{
 await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByRole('combobox',{name:'선택 알고리즘'}).selectOption('greedy');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('spinbutton',{name:'랜덤 전체 수량',exact:true}).fill('18');await page.getByRole('button',{name:'재고·입고 모두 랜덤',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('0개');await expect(page.getByRole('combobox',{name:'입고 추첨 방식'})).toHaveValue('random-draw');await expect(page.locator('.pallet-inventory tbody tr')).toHaveCount(18);expect((await page.locator('.pallet-inventory tbody tr td:first-of-type').allTextContents()).reduce((n,t)=>n+parseInt(t),0)).toBe(17);
 await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-status')).toHaveText(/다음 배치 준비|배치 중단/,{timeout:30000});expect(await page.locator('.pallet-metrics').first().textContent()).toMatch(/적재 박스[01]개/);for(const width of [320,375,414,768,1366]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole('button',{name:'재고·입고 모두 랜덤',exact:true})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/pallet-random-arrival-${width}.png`,fullPage:width!==1366});}
});


test('default stock has unrelated per-item dimensions and ratings, and records honest blocked results',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await expect(page.locator('.pallet-brand')).toContainText('PALLET LOADING LAB');await expect(page.getByRole('combobox',{name:'입고 시나리오'})).toHaveValue('field');await expect(page.getByRole('combobox',{name:'선택 알고리즘'})).toHaveValue('greedy');await expect(page.locator('.pallet-inventory tbody tr')).toHaveCount(30);
 await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await expect(page.getByRole('combobox',{name:'랜덤 박스 구성'})).toHaveValue('individual');await expect(page.getByRole('spinbutton',{name:'치수 단위 mm'})).toHaveCount(0);await expect(page.getByRole('spinbutton',{name:'예제 밀도 kg/m³'})).toHaveCount(0);await expect(page.locator('.pallet-random-controls')).toContainText('실측 자료가 아닙니다');
 await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('배치 중단',{timeout:30000});await expect(page.locator('.pallet-metrics').first()).toContainText('8개');await expect(page.getByRole('alert')).toContainText('9번째 박스 배치 실패');
 const wait=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();const run=JSON.parse(readFileSync((await (await wait).path())!,'utf8'));expect(run.scenario.generation.model).toBe('heterogeneous');expect(run.scenario.types.every((t:any)=>t.quantity===1)).toBe(true);expect(new Set(run.scenario.types.map((t:any)=>Object.values(t.size).join('/'))).size).toBe(30);expect(run.scenario.types.filter((t:any)=>Object.values(t.size).some((n:any)=>n%10!==0)).length).toBeGreaterThan(25);expect(new Set(run.scenario.types.map((t:any)=>t.material)).size).toBe(3);expect(run.metrics.complete).toBe(false);expect(run.frame.placements.every((b:any)=>b.maxLoadSource==='synthetic')).toBe(true);expect(run.metrics.loadUtilization).toBeLessThanOrEqual(1);
 await page.getByRole('checkbox',{name:'재질 색상',exact:true}).check();await page.getByRole('checkbox',{name:'지지 면',exact:true}).check();for(const width of [320,1366]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/pallet-field-${width}.png`,fullPage:true});}expect(errors).toEqual([]);
});

test('custom irregular ranges preserve applied pallet limits and manual strength overrides',async({page})=>{
 await openResearch(page);await page.getByRole('combobox',{name:'박스 공급 방식'}).selectOption('arrival');await page.getByText('팔레트 · 박스 편집',{exact:true}).click();await page.getByRole('spinbutton',{name:'너비 mm',exact:true}).fill('1103');await page.getByRole('spinbutton',{name:'깊이 mm',exact:true}).fill('977');await page.getByRole('button',{name:'설정 적용 · 새 실행'}).click();await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('spinbutton',{name:'세트 생성 시드',exact:true}).fill('913');await page.getByRole('spinbutton',{name:'랜덤 전체 수량',exact:true}).fill('7');await page.getByRole('spinbutton',{name:'랜덤 가로 최소 mm'}).fill('217');await page.getByRole('spinbutton',{name:'랜덤 가로 최대 mm'}).fill('419');await page.getByRole('spinbutton',{name:'랜덤 깊이 최소 mm'}).fill('173');await page.getByRole('spinbutton',{name:'랜덤 깊이 최대 mm'}).fill('347');await page.getByRole('spinbutton',{name:'랜덤 높이 최소 mm'}).fill('83');await page.getByRole('spinbutton',{name:'랜덤 높이 최대 mm'}).fill('191');await page.getByRole('button',{name:'이 시드로 세트 생성',exact:true}).click();await expect(page.locator('.pallet-inventory tbody tr')).toHaveCount(7);
 const readScenario=async()=>{await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();const wait=page.waitForEvent('download');await page.getByRole('button',{name:'시나리오 JSON 저장',exact:true}).click();const result=JSON.parse(readFileSync((await (await wait).path())!,'utf8'));await page.getByRole('button',{name:'적재 실험',exact:true}).click();return result;};const first=await readScenario();expect(first.pallet.width).toBe(1103);expect(first.pallet.depth).toBe(977);expect(first.types.every((t:any)=>t.size.w>=217&&t.size.w<=419&&t.size.d>=173&&t.size.d<=347&&t.size.h>=83&&t.size.h<=191)).toBe(true);
 await page.getByText('랜덤 박스 세트 · 순서',{exact:true}).click();await page.getByRole('button',{name:'이 시드로 세트 생성',exact:true}).click();expect((await readScenario()).types).toEqual(first.types);await page.getByText('팔레트 · 박스 편집',{exact:true}).click();await page.getByRole('spinbutton',{name:'B1 허용 지지하중 kg'}).fill('87');await page.getByRole('spinbutton',{name:'B1 강도 보정 비율'}).fill('1');await expect(page.locator('.pallet-material-fields').first()).toContainText('입력값');await page.getByRole('button',{name:'설정 적용 · 새 실행'}).click();const changed=await readScenario();expect(changed.types[0].maxLoadKg).toBe(87);expect(changed.types[0].maxLoadSource).toBeUndefined();expect(changed.types[1].maxLoadSource).toBe('synthetic');
 await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');
});
