import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
async function readRun(page:any){const d=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();return JSON.parse(readFileSync((await (await d).path())!,'utf8'));}
async function input(page:any,types:any[],pallet={width:600,depth:400,maxHeight:100},events:any[]=[]){await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();const s=JSON.parse(await page.getByRole('textbox',{name:'시나리오 JSON'}).inputValue());delete s.generation;s.id='online-ui';s.name='온라인 요구사항 검증';s.types=types;s.pallet=pallet;s.events=events;s.arrival.pattern='ordered';s.supplyMode='arrival';await page.getByRole('textbox',{name:'시나리오 JSON'}).fill(JSON.stringify(s));await page.getByRole('button',{name:'JSON 검증 · 적용'}).click();await page.getByRole('button',{name:'적재 실험',exact:true}).click();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');return s;}
const box=(id:string,w:number,d:number,h:number,weight:number,quantity=1)=>({id,name:id,size:{w,d,h},weight,quantity,orientations:[0],material:'plastic',maxLoadKg:200,color:'#6bcab7'});

test('task defaults preserve actual unknown arrival order and enforce all enabled constraints on the mixed inventory',async({page})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#pallet');await expect(page.getByRole('combobox',{name:'입고 시나리오',exact:true})).toHaveValue('online-task');await expect(page.getByRole('combobox',{name:'평가 정책',exact:true})).toHaveValue('online');await expect(page.getByRole('combobox',{name:'박스 공급 방식',exact:true})).toHaveValue('arrival');await expect(page.getByTestId('pallet-scene')).toHaveAttribute('data-model','gripper');const contract=page.getByLabel('현재 적용된 과제 검사');await expect(contract).toContainText('현재 도착 박스만');await expect(contract).toContainText('가반');await expect(contract).toContainText('무거운 박스');await expect(contract.locator('[data-active=false]')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('배치 중단',{timeout:60000});const blocked=await readRun(page);expect(blocked.frame.placements).toHaveLength(0);expect(blocked.scenario.constraints.standingHeight.enabled).toBe(true);expect(blocked.frame.reason).toContain('세로 박스');expect(blocked.frame.excluded).toHaveLength(0);
 // Preserve the historical online comparison with only the added skyline policy disabled.
 await page.getByText('적재 제약 · 환경',{exact:true}).click();await page.getByRole('checkbox',{name:'세로 박스 주변 높이 맞춤',exact:true}).uncheck();await page.getByRole('button',{name:'설정 적용 · 새 실행',exact:true}).click();await expect(page.getByRole('button',{name:'▶ 자동 적재',exact:true})).toBeEnabled();await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('배치 중단',{timeout:60000});
 const r=await readRun(page),m=JSON.parse(readFileSync('docs/pallet-online-measurements.json','utf8')).results.find((r:any)=>r.scenario.generation.seed===20261004&&r.algorithm==='greedy');expect(r.settings.policy).toBe('online');expect(r.scenario.constraints.heavyRule).toBe('each');expect(r.scenario.constraints.robotMode).toBe('gripper');expect(r.frame.placements).toHaveLength(m.metrics.count);expect(r.frame.records.map((r:any)=>r.observation.id)).toEqual(m.records.map((r:any)=>r.observation.id));expect(r.frame.records.every((r:any)=>r.analysis?.stockSelection===undefined)).toBe(true);expect(r.frame.records.slice(0,-1).every((r:any)=>r.analysis.online.currentOnly&&r.analysis.selectedBoxId===r.observation.id&&r.path.model==='gripper')).toBe(true);expect(r.metrics.workSeconds).toBeGreaterThan(0);expect(r.frame.excluded).toHaveLength(0);
 for(const b of r.frame.placements)for(const c of b.supports)expect(b.weight).toBeLessThanOrEqual(r.frame.placements.find((p:any)=>p.id===c.id).weight);await expect(page.getByRole('alert')).toContainText(`${r.metrics.count+1}번째 박스 배치 실패`);await expect(page.locator('.pallet-current h3')).toHaveText(r.frame.records.at(-1).observation.id);
 for(const width of [1366,320]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/pallet-online-${width}.png`,fullPage:true});}expect(errors).toEqual([]);
});

test('virtual future is clearly labelled, a central blocking candidate loses its remaining space, and the causal chosen order packs both',async({page})=>{
 await page.goto('/#pallet');await input(page,[box('light',100,400,100,2),box('large',300,400,100,10)]);await page.getByRole('combobox',{name:'선택 알고리즘',exact:true}).selectOption('rollout');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await expect(page.locator('.pallet-inspector')).toContainText('현재 관측 light-01만 배치');await expect(page.locator('.pallet-inspector')).toContainText('실제 다음 입고의 예측값이 아닙니다');const options=await page.getByRole('combobox',{name:'후보 선택'}).locator('option').allTextContents(),center=options.find(t=>t.includes('(250,0,0)'))!;await page.getByRole('combobox',{name:'후보 선택'}).selectOption({label:center});await expect(page.locator('.pallet-candidate-facts')).toContainText('100.0%');await page.getByText('후속 박스의 실제 제약 검사',{exact:true}).click();await expect(page.getByRole('region',{name:'미입고 박스 위치 검사'})).toContainText('large · 1개');await expect(page.getByRole('region',{name:'미입고 박스 위치 검사'})).toContainText('유효 위치 0/');
 await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료');const r=await readRun(page);expect(r.metrics.complete).toBe(true);expect(r.frame.records.map((r:any)=>r.observation.id)).toEqual(['light-01','large-01']);expect(r.frame.placements[0].position.x).not.toBe(250);expect(r.frame.placements.every((b:any)=>b.position.z===0)).toBe(true);expect(r.frame.records[0].analysis.virtualSequences).toHaveLength(4);expect(r.frame.records[0].analysis.candidates.filter((c:any)=>c.future).every((c:any)=>c.future.policies.length===1)).toBe(true);
});

test('observed resize, damaged and missing events replan the uncommitted pattern, conserve quantities and keep physics separate',async({page})=>{
 await page.goto('/#pallet');await input(page,[box('A',100,100,100,2,4)],{width:600,depth:400,maxHeight:500},[{step:1,kind:'resize',size:{w:180,d:147,h:131}},{step:2,kind:'damaged'},{step:3,kind:'missing'}]);await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await expect(page.locator('.pallet-current')).toContainText('180 × 147 × 131');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료');const r=await readRun(page);expect(r.frame.records.map((r:any)=>r.disposition)).toEqual(['placed','excluded','missing','placed']);expect(r.frame.placements[0].size).toEqual({w:180,d:147,h:131});expect(r.metrics.excluded).toBe(1);expect(r.metrics.missing).toBe(1);expect(r.frame.records[0].analysis.explanation.join()).toContain('규격 수정 관측');await page.getByRole('button',{name:'물리 검증 실행',exact:true}).click();await expect(page.locator('.pallet-physics-result')).toContainText('설정한 조건에서 안정',{timeout:20000});expect((await readRun(page)).frame.placements).toEqual(r.frame.placements);
 await page.getByRole('slider',{name:'배치 이력'}).fill('1');await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await page.getByRole('button',{name:'현재로 돌아가기'}).click();expect((await readRun(page)).frame.placements).toEqual(r.frame.placements);
});

test('research mode is explicitly different, returning to task constraints keeps box and pallet input and rejects payload',async({page})=>{
 await page.goto('/#pallet');for(const id of ['materials','reference','gripper','events']){await page.getByRole('combobox',{name:'입고 시나리오',exact:true}).selectOption(id);const r=await readRun(page);expect(r.settings.policy).toBe('online');expect(r.scenario.constraints.heavyRule).toBe('each');expect(r.scenario.constraints.robotMode).toBe('gripper');expect(r.scenario.supplyMode).toBe('arrival');await expect(page.getByLabel('현재 적용된 과제 검사').locator('[data-active=false]')).toHaveCount(0);if(id==='gripper')expect(r.scenario.constraints.gripper.width).toBe(650);}await page.getByRole('combobox',{name:'입고 시나리오',exact:true}).selectOption('field');await expect(page.getByLabel('현재 적용된 과제 검사')).toContainText('전체 재고 재정렬');await expect(page.getByLabel('현재 적용된 과제 검사')).toContainText('무게 순서 규칙 꺼짐');const before=await readRun(page);await page.getByRole('button',{name:'이 입력에 과제 조건 적용',exact:true}).click();const after=await readRun(page);expect(after.scenario.types).toEqual(before.scenario.types);expect(after.scenario.pallet).toEqual(before.scenario.pallet);expect(after.scenario.constraints.heavyRule).toBe('each');expect(after.scenario.constraints.robotMode).toBe('gripper');expect(after.scenario.supplyMode).toBe('arrival');expect(after.settings.policy).toBe('online');await expect(page.getByLabel('현재 적용된 과제 검사').locator('[data-active=false]')).toHaveCount(0);
 await input(page,[box('payload',100,100,100,33)]);await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.getByRole('alert')).toContainText('가반하중 초과');expect((await readRun(page)).frame.placements).toHaveLength(0);
});
