import {it,expect} from 'vitest';
import {readFileSync,writeFileSync} from 'node:fs';
import {studyReport,studyRanking} from '../src/pallet/benchmark/singleStudy';
it('audits saved measured trials and exports reproducible ranking without rerunning simulation',()=>{
 const saved=JSON.parse(readFileSync('docs/single-pallet-benchmark.json','utf8')),report=studyReport(saved.rows,saved.config);
 const total=saved.config.algorithms.length*saved.config.cases.length*saved.config.repeats;expect(report.rows).toHaveLength(total);expect(new Set(report.rows.map(r=>r.id)).size).toBe(total);
 expect(report.rows.every(r=>r.finalReasons?.length===0)).toBe(true);expect(report.rows.every(r=>Object.values(r.proposalViolations).every(n=>(n??0)===0))).toBe(true);
 expect(report.summary.every((r,i)=>!i||(r.score??-1)<=(report.summary[i-1].score??-1))).toBe(true);expect(report.summary.every(r=>r.scoreDistribution.n===saved.config.repeats)).toBe(true);
 const changed=report.rows.map(r=>({...r,values:{...r.values,p95Ms:99999,totalMs:99999}}));expect(studyRanking(changed,saved.config).map(r=>[r.algorithm,r.score,r.rank])).toEqual(report.summary.map(r=>[r.algorithm,r.score,r.rank]));
 for(const caseId of saved.config.cases)for(let e=0;e<saved.config.repeats;e++){const group=report.rows.filter(r=>r.caseId===caseId&&r.episode===e);expect(group).toHaveLength(saved.config.algorithms.length);expect(group.every(r=>JSON.stringify(r.arrivalIds)===JSON.stringify(group[0].arrivalIds))).toBe(true);}
 writeFileSync('docs/single-pallet-benchmark.json',JSON.stringify(report,null,2));writeFileSync('public/single-pallet-benchmark.json',JSON.stringify(report));
 const csv=['rank,algorithm,name,score_100,identical_score,mixed_score,completion_percent,utilization_percent,mean_count,mean_work_seconds,mean_trial_p95_ms'];
 for(const r of report.summary)csv.push([r.rank,r.algorithm,r.name,r.score,report.byCase.identical.find(s=>s.algorithm===r.algorithm)?.score,report.byCase.random.find(s=>s.algorithm===r.algorithm)?.score,r.completion.mean,r.utilization.mean,r.placed.mean,r.workSeconds.mean,r.p95Ms.mean].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(','));
 writeFileSync('docs/single-pallet-ranking.csv','\ufeff'+csv.join('\r\n'));
 const table=['| 순위 | 알고리즘 | 종합 /100 | 동일 규격 | 혼합 규격 | 평균 완료율 |','|---:|---|---:|---:|---:|---:|',...report.summary.map(r=>`| ${r.rank} | ${r.name} | ${r.score?.toFixed(2)} | ${report.byCase.identical.find(s=>s.algorithm===r.algorithm)?.score?.toFixed(2)} | ${report.byCase.random.find(s=>s.algorithm===r.algorithm)?.score?.toFixed(2)} | ${r.completion.mean?.toFixed(1)}% |`)];
 writeFileSync('docs/SINGLE-PALLET-STUDY.md',['# ALPS 단일 팔레트 알고리즘 비교','',`실측 완료: ${new Date().toISOString()}`,'','로봇팔 1개 · 팔레트 1개 · 1000×800×1400 mm · 그리퍼 TCP 근사 · 입고 버퍼 없음 · 순서대로 도착한 박스를 배치. 18개 알고리즘 × 동일 규격(12개)·혼합 규격(18개) × 시드 42~46 = 180회. 후보 상한 48개. 가반하중 35 kg(상자+그리퍼); 특정 현대 기종 모델이 아님.','',report.formula,'','두 조건을 50:50으로 평균. 점수가 소수 둘째 자리까지 같으면 공동 순위. 동일 시드의 두 규격 평균을 하나의 표본으로 취급해 95% CI를 구함. 소표본 근사이며 알고리즘 간 유의성 검정은 수행하지 않음.','',...table,'',`현대 기준선: ${report.baseline.assumption}`,'',`공개 근거: [HRPal 공식 설명](${report.baseline.source})`,'','혼합 규격 시드 43에서는 첫 박스가 세로형 Tall(357 mm)이며, 기준선은 0°/90°만 허용하므로 standingHeight 최대 상승 240 mm 조건에서 시작하지 못해 0점을 기록함. 이 회전 가정의 민감도이며 실제 HRPal의 제약으로 확인된 사실이 아님.','',report.verification,'','현재 코드의 논문 아이디어 전략 6개를 시험했으며, 사용자 추출 자료와 논문별 대응은 추가 확인이 필요함. 일반 Greedy와 현재 박스만 보는 Strategy Greedy는 서로 다른 구현. 계산 P95는 같은 기기의 trial별 P95 평균이며 점수에 포함하지 않음.','',`재생: https://pallet-loading-lab.eon3602.chatgpt.site/?palletView=single-study&v=39#pallet`].join('\n'));
});
