import { test,expect } from '@playwright/test';
import { readFileSync,writeFileSync } from 'node:fs';
import { standingHeight,isTallBox } from '../src/pallet/standingHeight';
async function exported(page:any){const d=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();return JSON.parse(readFileSync((await (await d).path())!,'utf8'));}
test('builds horizontal layers before the upright gap filler, shows local heights and preserves the policy on export',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#pallet');await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();const s=JSON.parse(await page.getByRole('textbox',{name:'시나리오 JSON'}).inputValue());delete s.generation;s.supplyMode='stock-select';s.events=[];s.pallet={width:600,depth:400,maxHeight:900};s.constraints.heavyRule='off';s.types=[{id:'T',name:'세로',size:{w:500,d:180,h:160},weight:1,quantity:1,orientations:['dhw'],material:'plastic',maxLoadKg:100,color:'#6bcab7'},{id:'F',name:'눕힌 층',size:{w:400,d:400,h:250},weight:5,quantity:2,orientations:[0],material:'plastic',maxLoadKg:200,color:'#e8b86a'}];
 await page.getByRole('textbox',{name:'시나리오 JSON'}).fill(JSON.stringify(s));await page.getByRole('button',{name:'JSON 검증 · 적용'}).click();await page.getByRole('button',{name:'적재 실험',exact:true}).click();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await expect(page.getByRole('button',{name:'▶ 자동 적재',exact:true})).toBeEnabled();await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료',{timeout:30000});
 const r=await exported(page);expect(r.frame.records.map((v:any)=>v.observation.typeId)).toEqual(['F','F','T']);expect(r.frame.placements.at(-1).position.z).toBe(0);expect(r.frame.placements.at(-1).orientation).toBe('dhw');expect(r.scenario.constraints.standingHeight).toEqual({enabled:true,maxRiseMm:100});expect(r.patternEvaluation.valid).toBe(true);
 await expect(page.getByLabel('세로 박스 높이 맞춤 결과')).toContainText('높이 조건 위반 0개');await page.getByText('세로 박스 · 주변 층 높이 비교',{exact:true}).click();await expect(page.getByLabel('세로 박스 높이 맞춤 결과')).toContainText('돌출 0 / 100 mm');await page.getByLabel('후보',{exact:true}).uncheck();await page.getByRole('button',{name:'입체',exact:true}).click();await page.getByTestId('pallet-scene').screenshot({path:'docs/pallet-standing-height-layers.png'});
 await page.getByRole('slider',{name:'배치 이력'}).fill('1');await expect(page.getByLabel('세로 박스 높이 맞춤 결과')).toContainText('긴 세로 박스 0개');await page.getByRole('button',{name:'현재로 돌아가기'}).click();expect((await exported(page)).frame.placements).toEqual(r.frame.placements);
 await page.getByText('적재 제약 · 환경',{exact:true}).click();await expect(page.getByRole('checkbox',{name:'세로 박스 주변 높이 맞춤',exact:true})).toBeChecked();await page.getByRole('spinbutton',{name:'세로 박스 최대 돌출 mm'}).fill('60');
 // Edits remain a draft until applied; the completed run keeps its original constraints.
 expect((await exported(page)).scenario.constraints.standingHeight.maxRiseMm).toBe(100);await page.getByRole('button',{name:'설정 적용 · 새 실행',exact:true}).click();expect((await exported(page)).scenario.constraints.standingHeight.maxRiseMm).toBe(60);
 await page.getByRole('checkbox',{name:'세로 박스 주변 높이 맞춤',exact:true}).uncheck();await page.getByRole('button',{name:'설정 적용 · 새 실행',exact:true}).click();await expect(page.getByLabel('세로 박스 높이 맞춤 결과')).toContainText('주변 높이 맞춤 꺼짐');expect((await exported(page)).scenario.constraints.standingHeight.enabled).toBe(false);expect(errors).toEqual([]);
});
test('mixed random packing has no isolated tall boxes and keeps all original constraints and robot motion',async({page})=>{
 test.setTimeout(150000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?palletDemo=compact#pallet');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await expect(page.locator('.pallet-status')).toContainText('남은 재고 배치 불가',{timeout:120000});const r=await exported(page);
 expect(r.metrics.count).toBe(16);expect(r.metrics.height).toBe(964);expect(r.patternEvaluation.valid).toBe(true);expect(r.scenario.constraints.supportRatio).toBe(.95);expect(r.scenario.constraints.heavyRule).toBe('each');const tall=r.frame.placements.filter(isTallBox);expect(tall.length).toBeGreaterThan(0);for(const rec of r.frame.records)if(rec.placement)expect(standingHeight(rec.placement,rec.before,r.scenario.constraints).valid).toBe(true);
 await expect(page.getByLabel('세로 박스 높이 맞춤 결과')).toContainText('높이 조건 위반 0개');await expect(page.getByTestId('pallet-scene').locator('canvas')).toHaveAttribute('data-arm-visible','true');await page.getByLabel('후보',{exact:true}).uncheck();await page.getByRole('button',{name:'로봇 작업셀',exact:true}).click();await page.getByTestId('pallet-scene').screenshot({path:'docs/pallet-standing-height-robot.png'});await page.getByLabel('로봇팔',{exact:true}).uncheck();await page.getByRole('button',{name:'입체',exact:true}).click();await page.getByTestId('pallet-scene').screenshot({path:'docs/pallet-standing-height-mixed.png'});
 for(const width of [1440,320]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/pallet-standing-height-${width}.png`,fullPage:true});}
 writeFileSync('docs/pallet-standing-height-browser.json',JSON.stringify({verifiedAt:new Date().toISOString(),scenario:r.scenario,metrics:r.metrics,placements:r.frame.placements,details:tall.map((b:any)=>({id:b.id,...standingHeight(b,r.frame.placements.filter((o:any)=>o.id!==b.id),r.scenario.constraints)}))},null,2));expect(errors).toEqual([]);
});
