import {describe,it,expect} from 'vitest';
import {DEFAULT_CONFIG,type Box,type Config} from '../src/pallet/adaptive/types';
import {initialFrame,Session} from '../src/pallet/adaptive/runtime';
import {shape} from '../src/pallet/adaptive/shape';
import {analyzeFrame,captureRecord,latency,percentile,pairedBaseline,robustness,diagnostics,type TraceRecord} from '../src/pallet/adaptive/performance';
const config=():Config=>({...structuredClone(DEFAULT_CONFIG),pallet:{width:1000,depth:1000,maxHeight:1400},timeBudgetMs:30000,maxCandidates:16});
const box=(id='a'):Box=>({id,nominal:{w:200,d:200,h:100},parts:shape({w:200,d:200,h:100},'normal',0),mass:5,com:{x:100,y:100,z:50},rotations:[0,90],friction:.5,strength:{topLoadKg:100,residual:1,source:'assumption',note:'test'},damage:'normal',masks:[],arrival:0,color:'#80b7b0',suction:{seal:'unknown',maxMassKg:35,maxMomentNm:20}});
function frame(){const f=initialFrame();f.tick=1;f.arrived=1;f.placed=[{box:box(),position:{x:0,y:0,z:0},rotation:0}];return f;}
describe('performance dashboard model and trace',()=>{
 it('empty is unverified; valid geometry never implies verified real robot',()=>{expect(analyzeFrame(initialFrame(),config(),1).geometryStatus).toBe('미검증');const a=analyzeFrame(frame(),config(),1);expect(a.geometryStatus).toBe('통과');expect(a.overallStatus).toBe('미검증');});
 it('independently fails collision even with high completion',()=>{const f=frame();f.placed.push({...f.placed[0],box:box('b')});const a=analyzeFrame(f,config(),2);expect(a.completion).toBe(1);expect(a.overallStatus).toBe('실패');expect(a.reasons).toContain('collision');});
 it('uses actual CoM and support polygon for signed margins and 8 directional limits',()=>{const a=analyzeFrame(frame(),config(),1);expect(a.center).toEqual({x:100,y:100,z:50});expect(a.globalMarginMm).toBe(100);expect(a.tippingG).toBe(2);expect(a.directions[0].g).toBe(2);expect(a.directions[1].g).toBeCloseTo(2*Math.SQRT2);const f=frame();f.placed[0].box.com.x=250;const b=analyzeFrame(f,config(),1);expect(b.globalMarginMm).toBe(-50);expect(b.tippingG).toBe(0);expect(b.reasons).toContain('tipping');});
 it('missing capacity remains unknown instead of 0% safe',()=>{const f=frame();f.placed[0].box.strength={topLoadKg:null,residual:1,source:'unknown',note:'unknown'};const a=analyzeFrame(f,config(),1);expect(a.boxes[0].loadRatio).toBeNull();expect(a.unknownStrength).toBe(1);});
 it('nearest-rank latency handles tails and excludes fast invalid results from deadline success',()=>{expect(percentile([], .99)).toBeNull();expect(percentile([1,2,3,100],.99)).toBe(100);const c=config(),r=captureRecord(frame(),undefined,c,1),rows=[{...r,planMs:2,validCandidates:0},{...r,planMs:20,validCandidates:1},{...r,planMs:4,validCandidates:1}];const l=latency(rows,10);expect(l.validOnTime).toBeCloseTo(1/3);expect(l.onTime).toBeCloseTo(2/3);expect(l.p99).toBe(20);});
 it('captures immutable placement stages and actual time deltas without changing choices',()=>{const c=config(),boxes=[box('a'),box('b'),box('c')],run=new Session(c,boxes),history:TraceRecord[]=[captureRecord(run.frame,undefined,c,boxes.length)];run.run(f=>history.push(captureRecord(f,history.at(-1),c,boxes.length)));expect(run.frame.placed.length).toBe(3);expect(history[0].frame.placed.length).toBe(0);expect(history[1].frame.placed.length).toBe(1);expect(history.reduce((n,r)=>n+r.planMs,0)).toBeCloseTo(run.frame.planningMs);expect(history.reduce((n,r)=>n+r.workSeconds,0)).toBeCloseTo(run.frame.executionSeconds);expect(history.filter(r=>r.placedId).every(r=>r.pathMm!==null&&r.pathMm>0)).toBe(true);expect(new Session(c,boxes).run().placed).toEqual(run.frame.placed);expect(diagnostics(history,c).every(d=>history.some(r=>r.frame.tick===d.tick))).toBe(true);});
 it('baseline comparison rejects mismatched geometry, order and configuration',()=>{const c=config(),a={config:{...c,mode:'A' as const},boxes:[box('a'),box('b')],frame:frame()},b={...a,config:{...c,mode:'C' as const}};expect(pairedBaseline(b,[a])).toBe(a);expect(pairedBaseline({...b,boxes:[box('b'),box('a')]},[a])).toBeUndefined();expect(pairedBaseline({...b,config:{...b.config,seed:99}},[a])).toBeUndefined();});
 it('robustness requires complete runs, all boxes and no model violation',()=>{const c=config(),good=frame();good.done=true;const bad=structuredClone(good);bad.placed[0].position.z=100;const rows=[{config:c,boxes:[box()],frame:good},{config:c,boxes:[box()],frame:bad},{config:c,boxes:[box(),box('b')],frame:good},{config:c,boxes:[box()],frame:initialFrame()}];const r=robustness(rows,'C');expect(r.count).toBe(3);expect(r.success).toBeCloseTo(1/3);expect(r.worst).toBe(.5);});
});
