import { openResearch } from './pallet-research';
import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
test('large base first, cumulative lower resultants, 3D markers, inspection and replay match the exported plan',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await openResearch(page);await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();const s=JSON.parse(await page.getByRole('textbox',{name:'시나리오 JSON'}).inputValue());delete s.generation;s.id='lower-balance';s.name='하단 누적 중심 검증';s.supplyMode='stock-select';s.pallet={width:503,depth:407,maxHeight:900};s.types=[
 {id:'small1',name:'상부1',size:{w:177,d:211,h:107},weight:7,quantity:1,orientations:[0],material:'plastic',maxLoadKg:30,color:'#e8b86a'},
 {id:'base',name:'큰 종이 받침',size:{w:503,d:407,h:97},weight:4,quantity:1,orientations:[0],material:'paper',maxLoadKg:100,color:'#6bcab7'},
 {id:'small2',name:'상부2',size:{w:177,d:211,h:107},weight:5,quantity:1,orientations:[0],material:'paper',maxLoadKg:20,color:'#b8a3e8'}];
 await page.getByRole('textbox',{name:'시나리오 JSON'}).fill(JSON.stringify(s));await page.getByRole('button',{name:'JSON 검증 · 적용'}).click();await page.getByRole('button',{name:'적재 실험',exact:true}).click();await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await expect(page.locator('.pallet-current h3')).toHaveText('base-01');await expect(page.locator('.pallet-inspector')).toContainText('바닥 면적이 큰 순서');await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료',{timeout:30000});
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();const run=JSON.parse(readFileSync((await (await download).path())!,'utf8'));expect(run.frame.placements).toHaveLength(3);expect(run.frame.records[0].observation.id).toBe('base-01');expect(run.frame.records.every((r:any)=>r.analysis.stockSelection.sizePriority==='footprint-volume')).toBe(true);const base=run.metrics.supportBalances.find((b:any)=>b.id==='base-01');expect(base.mass).toBeCloseTo(16);expect(base.center.x).toBeCloseTo(251.5);expect(base.center.y).toBeCloseTo(203.5);expect(base.offsetMm).toBeCloseTo(0);expect(base.reserve).toBeGreaterThan(0);
 await page.getByText(/아랫단별 누적 하중 중심 \(/).click();const table=page.getByRole('table',{name:'아랫단별 하중 분석'});await expect(table).toContainText('base-01');await expect(table).toContainText('16.00');await expect(table).toContainText('251.5 / 203.5');await expect(page.locator('.pallet-center-legend')).toContainText('청록 점');const canvas=page.locator('.pallet-scene canvas').first();await expect(canvas).toHaveAttribute('data-support-centers',/base-01/);const markers=JSON.parse((await canvas.getAttribute('data-support-centers'))!);expect(markers.find((m:any)=>m.id==='base-01').center.x).toBe(base.center.x);
 await page.getByRole('button',{name:'평면',exact:true}).click();await expect(canvas).toHaveAttribute('data-boxes',/base-01/);const hit=JSON.parse((await canvas.getAttribute('data-boxes'))!).find((b:any)=>b.id==='base-01');await canvas.click({position:{x:hit.x,y:hit.y}});await expect(page.getByRole('heading',{name:'확정 박스 검사'})).toBeVisible();await expect(page.locator('.pallet-inspector')).toContainText('아랫단 하중 중심 x / y');await expect(page.locator('.pallet-inspector')).toContainText('전도 여유');
 await page.getByRole('slider',{name:'배치 이력'}).fill('1');await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await expect(table).not.toBeVisible();await expect(canvas).toHaveAttribute('data-support-centers','[]');await page.getByRole('button',{name:'현재로 돌아가기'}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('3개');await expect(table).toContainText('16.00');
 for(const width of [1366,320]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/pallet-lower-balance-${width}.png`,fullPage:true});}expect(errors).toEqual([]);
});
