import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
async function run(page:any){const d=page.waitForEvent('download');await page.getByRole('button',{name:'실행 JSON 저장',exact:true}).click();return JSON.parse(readFileSync((await (await d).path())!,'utf8'));}
const box=(id:string,w=100,d=100,weight=2,quantity=1)=>({id,name:id,size:{w,d,h:100},weight,quantity,orientations:[0],material:'plastic',maxLoadKg:100,color:'#6bcab7'});
async function input(page:any,types:any[],pallet={width:600,depth:400,maxHeight:600},radius=2400){await page.goto('/#pallet');await page.getByRole('button',{name:'설정 · 데이터',exact:true}).click();const s=JSON.parse(await page.getByRole('textbox',{name:'시나리오 JSON'}).inputValue());delete s.generation;s.types=types;s.pallet=pallet;s.events=[];s.arrival.pattern='ordered';s.constraints.reach.maxRadius=radius;await page.getByRole('textbox',{name:'시나리오 JSON'}).fill(JSON.stringify(s));await page.getByRole('button',{name:'JSON 검증 · 적용'}).click();await page.getByRole('button',{name:'적재 실험',exact:true}).click();await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();}

test('a blocked normal box resumes after changing pallet conditions, preserving the base and historical frame conditions',async({page})=>{
 await input(page,[box('A',200,400,5),box('B',300,400)],{width:200,depth:400,maxHeight:100});await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('배치 중단');const before=await run(page);expect(before.frame.placements).toHaveLength(1);
 await page.getByText('팔레트 · 박스 편집',{exact:true}).click();await page.getByRole('spinbutton',{name:'너비 mm',exact:true}).fill('600');await page.getByRole('button',{name:'확정 적재 유지 · 조건 재계획',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'확정 적재 1개를 유지'})).toBeVisible();await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();const revised=await run(page);expect(revised.runId).not.toBe(before.runId);expect(revised.frame.records).toHaveLength(1);expect(revised.frame.placements[0].position).toEqual(before.frame.placements[0].position);expect(revised.frame.blocked).toBe(false);
 await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료');const after=await run(page);expect(after.frame.placements).toHaveLength(2);expect(after.frame.records.map((r:any)=>r.observation.id)).toEqual(['A-01','B-01']);expect(after.frame.records.map((r:any)=>r.context.pallet.width)).toEqual([200,600]);expect(after.patternEvaluation.valid).toBe(true);
 await page.getByRole('slider',{name:'배치 이력'}).fill('1');expect(JSON.parse((await page.getByTestId('pallet-scene').getAttribute('data-pallet'))!).width).toBe(200);await page.getByRole('button',{name:'현재로 돌아가기'}).click();expect(JSON.parse((await page.getByTestId('pallet-scene').getAttribute('data-pallet'))!).width).toBe(600);expect((await run(page)).frame.placements[0].position).toEqual(before.frame.placements[0].position);
});

test('live resize, damage and missing observations cancel the uncommitted motion and conserve confirmed stock',async({page})=>{
 await input(page,[box('A',100,100,2,4)]);await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();const first=await run(page);
 await page.getByRole('combobox',{name:'재생 속도'}).selectOption('1');await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('접근');await page.getByText('현재 관측 수정 · 부분 재계획',{exact:true}).click();await page.getByRole('spinbutton',{name:'관측 가로 mm'}).fill('185');await page.getByRole('spinbutton',{name:'관측 깊이 mm'}).fill('147');await page.getByRole('spinbutton',{name:'관측 높이 mm'}).fill('131');await page.getByRole('button',{name:'관측 치수로 재계획'}).click();await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();let r=await run(page);expect(r.frame.placements).toHaveLength(1);expect(r.frame.placements[0]).toEqual(first.frame.placements[0]);expect(r.scenario.events[0]).toEqual({kind:'resize',size:{w:185,d:147,h:131},step:2});
 await page.getByRole('combobox',{name:'재생 속도'}).selectOption('64');await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('2개');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();r=await run(page);expect(r.frame.placements[1].size).toEqual({w:185,d:147,h:131});
 await page.getByRole('button',{name:'손상 관측 · 격리'}).click();await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-current h3')).toHaveText('A-04');await page.getByRole('button',{name:'누락 관측',exact:true}).click();await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료');r=await run(page);expect(r.frame.records.map((r:any)=>r.disposition)).toEqual(['placed','placed','excluded','missing']);expect(r.frame.placements.length+r.frame.excluded.length+r.frame.missing.length).toBe(4);expect(r.frame.placements[0].position).toEqual(first.frame.placements[0].position);
});

test('reach settings reject the path and can be corrected, while pattern scores are consistent in comparison JSON and CSV',async({page})=>{
 await input(page,[box('A',100,100,2,2)],undefined,500);await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.getByRole('alert')).toContainText('도달 반경');await page.getByText('적재 제약 · 환경',{exact:true}).click();await page.getByRole('spinbutton',{name:'최대 도달 반경 mm'}).fill('2400');await page.getByRole('button',{name:'확정 적재 유지 · 조건 재계획',exact:true}).click();await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();await page.getByRole('button',{name:'▶ 자동 적재',exact:true}).click();await expect(page.locator('.pallet-status')).toContainText('입고 처리 완료');const r=await run(page);expect(r.patternEvaluation.coverage).toBe(1);expect(r.patternEvaluation.score).toBeGreaterThan(0);await expect(page.getByLabel('적재 패턴 평가')).toContainText('관절·IK');
 for(const width of [1366,320]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/pallet-requirements-${width}.png`,fullPage:true});}
 await page.getByRole('button',{name:'알고리즘 비교',exact:true}).click();await page.getByRole('spinbutton',{name:'반복 시드 수'}).fill('1');await page.getByRole('button',{name:'같은 입력으로 비교'}).click();await expect(page.locator('.pallet-results tbody tr')).toHaveCount(3);await expect(page.locator('.pallet-results')).toContainText('종합 점수');let d=page.waitForEvent('download');await page.getByRole('button',{name:'비교 실행 JSON 저장'}).click();const batch=JSON.parse(readFileSync((await (await d).path())!,'utf8'));expect(Object.keys(batch.evaluations)).toHaveLength(3);for(const evaluation of Object.values(batch.evaluations) as any[]){expect(evaluation.valid).toBe(true);expect(evaluation.score).toBeGreaterThan(0);expect(evaluation.score).toBeLessThanOrEqual(100);expect(evaluation.ik).toContain('미검증');}
 d=page.waitForEvent('download');await page.getByRole('button',{name:'비교 CSV 저장',exact:true}).click();expect(readFileSync((await (await d).path())!,'utf8')).toContain('patternScore,coverage');
 await expect(page.locator('.pallet-condition-results tbody tr')).toHaveCount(3);await page.getByRole('button',{name:'적재 실험',exact:true}).click();await page.getByText('팔레트 · 박스 편집',{exact:true}).click();await page.getByRole('spinbutton',{name:'너비 mm',exact:true}).fill('700');await page.getByRole('button',{name:'확정 적재 유지 · 조건 재계획'}).click();await page.getByRole('button',{name:'알고리즘 비교',exact:true}).click();await page.getByRole('button',{name:'같은 입력으로 비교'}).click();await expect(page.locator('.pallet-condition-results tbody tr')).toHaveCount(6);d=page.waitForEvent('download');await page.getByRole('button',{name:'조건별 비교 JSON 저장'}).click();const history=JSON.parse(readFileSync((await (await d).path())!,'utf8'));expect(history.batches.map((b:any)=>b.scenario.pallet.width)).toEqual([700,600]);expect(history.batches.every((b:any)=>b.results.length===3)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'적재 실험',exact:true}).click();const snapshot=await run(page);expect(snapshot.scenario.pallet.width).toBe(700);await page.getByText('팔레트 · 박스 편집',{exact:true}).click();await page.getByRole('spinbutton',{name:'너비 mm',exact:true}).fill('800');await page.getByText('적재 제약 · 환경',{exact:true}).click();await page.getByRole('combobox',{name:'적재 환경',exact:true}).selectOption('ideal');await page.getByRole('button',{name:'확정 적재 유지 · 조건 재계획'}).click();await expect(page.getByTestId('pallet-scene')).toHaveAttribute('data-model','ideal');await page.getByRole('combobox',{name:'보관 실행',exact:true}).selectOption(snapshot.runId);await expect(page.getByTestId('pallet-scene')).toHaveAttribute('data-model','gripper');expect(JSON.parse((await page.getByTestId('pallet-scene').getAttribute('data-pallet'))!).width).toBe(700);await expect(page.getByLabel('현재 적용된 과제 검사').locator('[data-active=false]')).toHaveCount(0);await expect(page.locator('.pallet-policy-note')).toContainText('가반·작업공간');const saved=await run(page);expect(saved.scenario.pallet.width).toBe(700);expect(saved.scenario.constraints.robotMode).toBe('gripper');await page.getByRole('combobox',{name:'보관 실행',exact:true}).selectOption('');await expect(page.getByTestId('pallet-scene')).toHaveAttribute('data-model','ideal');expect(JSON.parse((await page.getByTestId('pallet-scene').getAttribute('data-pallet'))!).width).toBe(800);
});

test('an invalid condition change or search budget is rejected without erasing the confirmed frame',async({page})=>{
 await input(page,[box('A',100,100,2,2)]);await page.getByRole('button',{name:'한 단계',exact:true}).click();await expect(page.locator('.pallet-metrics').first()).toContainText('1개');await expect(page.getByRole('button',{name:'한 단계',exact:true})).toBeEnabled();const before=await run(page);await page.getByText('팔레트 · 박스 편집',{exact:true}).click();await page.getByRole('spinbutton',{name:'높이 한계 mm',exact:true}).fill('50');await page.getByRole('button',{name:'확정 적재 유지 · 조건 재계획'}).click();await expect(page.locator('.pallet-notice')).toContainText('확정 적재');expect((await run(page)).frame).toEqual(before.frame);await page.getByRole('spinbutton',{name:'높이 한계 mm',exact:true}).fill('600');await page.getByText('탐색 범위 · 점수 가중치',{exact:true}).click();await page.getByRole('spinbutton',{name:'잔량 종류별 검사 상한'}).fill('0');await page.getByRole('button',{name:'설정 적용 · 새 실행'}).click();await expect(page.locator('.pallet-notice')).toContainText('잔량 검사 1~64');expect((await run(page)).frame).toEqual(before.frame);
});
