import {describe,it,expect} from 'vitest';
import {streamInventory} from '../src/pallet/relay/streamInventory';
import {withFleet} from '../src/pallet/relay/fleet';
import {createStream,advanceStream,assertStreamInventory} from '../src/pallet/relay/streamEngine';
import {beltBounds,beltStation,CONVEYOR} from '../src/pallet/relay/conveyor';
import {loopLength} from '../src/pallet/relay/streamGeometry';
import {rejectLayout,rejectStation,rejectCenter,rejectMotion} from '../src/pallet/relay/rejectPallet';
import {intakeSettings} from '../src/pallet/relay/intake';
const scenario=()=>{const s=withFleet(streamInventory(42,8),{count:1,architecture:'floor',floorCount:1});s.pallet.conveyorMode='straight';return s;};
describe('longer conveyor and dedicated reject pallets',()=>{
 it('extends upstream feed without moving the roller stop or altering loop defaults',()=>{const s=scenario(),base=beltBounds(s.pallet),station=beltStation(0,s.pallet);expect(base.right-base.left).toBe(4600);s.pallet.conveyorExtensionMm=1500;const extended=beltBounds(s.pallet);expect(extended.left).toBe(base.left-3000);expect(extended.right).toBe(base.right);expect(loopLength(s.pallet)).toBe(7600);expect(beltStation(0,s.pallet)).toEqual(station);s.pallet.conveyorMode='loop';const L=loopLength(s.pallet);delete s.pallet.conveyorExtensionMm;expect(L-loopLength(s.pallet)).toBe(6000);});
 it('rejects invalid extension values',()=>{const s=scenario();for(const v of [-1,4001,NaN,1.5]){s.pallet.conveyorExtensionMm=v;expect(()=>beltBounds(s.pallet)).toThrow();}});
 it('puts all 8 actual dented boxes on bounded, non-overlapping floor slots and preserves IDs',()=>{const s=scenario();s.pallet.conveyorExtensionMm=1500;s.intake=intakeSettings(1);let w=createStream(s);for(let t=1;t<=150;t++)w=advanceStream(s,w,[],t).world;expect(w.boxes.every(b=>b.status==='quarantined'&&b.deformation)).toBe(true);expect(assertStreamInventory(w,[])).toBe(true);const layout=rejectLayout(s.pallet,w.boxes);expect(layout.overflow).toEqual([]);expect(layout.pallets.flatMap(p=>p.placements).map(p=>p.boxId).sort()).toEqual(w.boxes.map(b=>b.observation.id).sort());for(const p of layout.pallets)for(const q of p.placements){expect(q.position.z).toBe(0);expect(q.position.x).toBeGreaterThanOrEqual(0);expect(q.position.y).toBeGreaterThanOrEqual(0);expect(q.position.x+q.size.w).toBeLessThanOrEqual(s.pallet.width);expect(q.position.y+q.size.d).toBeLessThanOrEqual(s.pallet.depth);for(const other of p.placements.filter(r=>r!==q))expect(q.position.x+q.size.w<=other.position.x||other.position.x+other.size.w<=q.position.x||q.position.y+q.size.d<=other.position.y||other.position.y+other.size.d<=q.position.y).toBe(true);}expect(w.records).toHaveLength(0);expect(w.cells[0].placements).toHaveLength(0);});
 it('keeps prior slots when more damaged boxes arrive and uses another pallet instead of stacking',()=>{const s=scenario(),boxes=createStream(s).boxes;boxes.forEach(b=>b.observation.size={w:1000,d:900,h:200});const before=rejectLayout(s.pallet,boxes.slice(0,2)),after=rejectLayout(s.pallet,boxes);expect(before.pallets).toEqual(after.pallets.slice(0,2));expect(after.pallets).toHaveLength(8);expect(rejectLayout(s.pallet,boxes)).toEqual(after);});
 it('reports oversized cartons rather than shrinking or dropping them',()=>{const s=scenario(),b=createStream(s).boxes[0];b.observation.size.w=s.pallet.width+1;const r=rejectLayout(s.pallet,[b]);expect(r.pallets).toEqual([]);expect(r.overflow[0].boxId).toBe(b.observation.id);expect(b.observation.size.w).toBe(s.pallet.width+1);});
 it('locates reject pallets outside the loop and animates toward the reserved floor position',()=>{const s=scenario(),b=createStream(s).boxes[0],q=rejectLayout(s.pallet,[b]).pallets[0].placements[0],station=rejectStation(s.pallet),target=rejectCenter(s.pallet,0,q),from={...beltStation(0,s.pallet),z:CONVEYOR.deck+b.observation.size.h/2};expect(station.y+s.pallet.depth/2).toBeLessThan(CONVEYOR.back-CONVEYOR.width/2);expect(rejectMotion(from,target,0)).toEqual(from);expect(rejectMotion(from,target,1)).toEqual(target);expect(rejectMotion(from,target,.5).z).toBeGreaterThan(from.z);expect(target.z-q.size.h/2).toBe(-290);});
});
