import { useMemo } from 'react';
import { evaluatePattern } from './patternEvaluation';
import { ALGORITHM_NAMES } from './types';
import type { Scenario,SearchSettings,RunResult } from './types';
export interface ComparisonBatch { id:string;scenario:Scenario;settings:SearchSettings;results:RunResult[] }
export function ConditionComparison({batches}:{batches:ComparisonBatch[]}){
 const rows=useMemo(()=>batches.flatMap((b,i)=>[...new Set(b.results.map(r=>r.algorithm))].flatMap(algorithm=>{const results=b.results.filter(r=>r.algorithm===algorithm);if(!results.length)return [];const e=results.map(r=>evaluatePattern(r.frame,b.scenario));return [{batch:b,index:batches.length-i,algorithm,count:results.reduce((n,r)=>n+r.metrics.count,0)/results.length,complete:results.filter(r=>r.metrics.complete).length,runs:results.length,score:e.every(e=>e.score!==null)?e.reduce((n,e)=>n+e.score!,0)/e.length:null,compute:results.reduce((n,r)=>n+r.metrics.medianMs,0)/results.length,work:b.scenario.constraints.robotMode==='ideal'?null:results.reduce((n,r)=>n+r.metrics.workSeconds,0)/results.length}];})),[batches]);
 if(!rows.length)return null;
 return <section className="pallet-panel"><h2>조건별 비교 기록</h2><p className="pallet-note">완료된 비교의 입력·제약·탐색 설정을 함께 보관합니다. 서로 다른 조건의 결과를 같은 문제의 우열로 해석하지 않습니다. 관절·IK는 미검증입니다.</p><div className="pallet-table-scroll"><table className="pallet-condition-results" aria-label="조건별 패턴 비교"><thead><tr>{['조건 / 팔레트 / 제약','알고리즘','평균 적재','전체 성공','평균 점수','결정 ms','작업 s'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={`${r.batch.id}-${r.algorithm}`}><th>조건 {r.index} · {r.batch.scenario.pallet.width}×{r.batch.scenario.pallet.depth}×{r.batch.scenario.pallet.maxHeight} mm<small>{r.batch.scenario.types.reduce((n,t)=>n+t.quantity,0)}개 · 무게 규칙 {r.batch.scenario.constraints.heavyRule} · {r.batch.scenario.constraints.robotMode==='ideal'?'이상적 연구':`그리퍼 근사 ${r.batch.scenario.constraints.gripper.payload}kg / 반경 ${r.batch.scenario.constraints.reach?.maxRadius??'제외'}mm`} · K {r.batch.settings.topK}</small></th><td>{ALGORITHM_NAMES[r.algorithm]}</td><td>{r.count.toFixed(1)}</td><td>{r.complete}/{r.runs}</td><td>{r.score===null?'미검증':r.score.toFixed(1)}</td><td>{r.compute.toFixed(1)}</td><td>{r.work===null?'미평가':r.work.toFixed(1)}</td></tr>)}</tbody></table></div></section>;
}
