import { DEFAULT_STRATEGY,type StrategyDebug,type StrategyConfig } from './strategies/PackingStrategy';
import { approachVolume } from './strategies/feasibility';
import { BUFFER_SOURCE,BUFFER_SIZE } from './temporaryBuffer';
import { poseQuaternion,movingHeight } from './poseRendering';
import { createRobotArmView } from './RobotArmView';
import { DEFAULT_ROBOT_ARM,type RobotArmModel } from './robotArm';
import { useEffect,useRef,useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { engineToRender,renderSize,centerOf } from './coordinates';
import { incomingPosition } from './constraints';
import { balance } from './features';
import { stability } from './stability';
import type { Scenario,Placement,Observation,Candidate,GripPath,Vec3,PhysicsResult,Orientation,DeferredBox } from './types';
export interface ViewOptions { candidateLimit?:number;tool?:boolean; strategyDebug?:boolean; opacity:number;outlines:boolean;slice:number;weight:boolean;supports:boolean;center:boolean;candidates:boolean;path:boolean;material?:boolean;explode?:boolean;arm?:boolean;armModel?:RobotArmModel }
export type CameraPose={position:number[];target:number[]};
interface Props { strategyDebug?:StrategyDebug;strategyConfig?:StrategyConfig; buffer?:DeferredBox[];bufferEnabled?:boolean;scenario:Scenario;placements:Placement[];current?:Observation|null;candidate?:Pick<Candidate,'id'|'placement'|'valid'>|null;others?:Candidate[];path?:GripPath|null;motion?:boolean;progress?:number;options:ViewOptions;selection?:string|null;onSelect?:(id:string)=>void;camera:string;cameraVersion:number;cameraPose?:CameraPose|null;onCamera?:(pose:CameraPose)=>void;physics?:PhysicsResult|null;onCanvas?:(canvas:HTMLCanvasElement)=>void }
function color(name:string){const c=document.createElement('canvas'),ctx=c.getContext('2d')!;c.width=c.height=1;ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue(name).trim();ctx.fillRect(0,0,1,1);const d=ctx.getImageData(0,0,1,1).data;return new THREE.Color((d[0]<<16)|(d[1]<<8)|d[2]);}
const pointPose=(p:GripPath['points'][number]):Orientation=>p.pose??(p.yaw===90?90:0);
export function pathPosition(path:GripPath,p:number){let seconds=p*path.seconds;for(let i=0;i<path.segmentSeconds.length;i++){const duration=path.segmentSeconds[i];if(seconds<=duration||i===path.segmentSeconds.length-1){const a=path.points[i],b=path.points[i+1],travel=duration-b.hold,t=travel>0?Math.min(1,seconds/travel):1;return {tcp:{x:a.tcp.x+(b.tcp.x-a.tcp.x)*t,y:a.tcp.y+(b.tcp.y-a.tcp.y)*t,z:a.tcp.z+(b.tcp.z-a.tcp.z)*t},yaw:(a.yaw||0)+((b.yaw||0)-(a.yaw||0))*t,fromPose:pointPose(a),toPose:pointPose(b),blend:t,carrying:b.carrying,index:i+1,label:b.label};}seconds-=duration;}return {tcp:path.points[0].tcp,yaw:path.points[0].yaw||0,fromPose:0 as Orientation,toPose:0 as Orientation,blend:0,carrying:false,index:0,label:''};}
export default function PalletScene(props:Props){
 const host=useRef<HTMLDivElement>(null),armStatus=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;const stage=useRef<any>(null),[unavailable,setUnavailable]=useState(false);
 useEffect(()=>{const el=host.current!;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,powerPreference:'low-power'});}catch{setUnavailable(true);return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(color('--color-board'));renderer.domElement.setAttribute('aria-label','회전 가능한 팔레트 3D 시뮬레이터');renderer.domElement.setAttribute('role','img');renderer.domElement.tabIndex=0;el.appendChild(renderer.domElement);props.onCanvas?.(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.01,60),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=true;controls.minDistance=.7;controls.maxDistance=9;controls.maxPolarAngle=Math.PI*.49;
 scene.add(new THREE.HemisphereLight(color('--color-ink'),color('--color-panel'),2.5));const light=new THREE.DirectionalLight(color('--color-ink'),3);light.position.set(1,4,2);scene.add(light);const objects=new THREE.Group(),moving=new THREE.Group(),grip=new THREE.Group();const arm=createRobotArmView();scene.add(objects,moving,grip,arm.group);stage.current={renderer,scene,camera,controls,objects,moving,grip,arm};
 let applying=false;const change=()=>{renderer.domElement.dataset.camera=camera.position.toArray().map(n=>n.toFixed(3)).join(',');if(!applying)latest.current.onCamera?.({position:camera.position.toArray(),target:controls.target.toArray()});};controls.addEventListener('end',change);stage.current.applyCamera=(pose:CameraPose)=>{applying=true;camera.position.fromArray(pose.position);controls.target.fromArray(pose.target);controls.update();applying=false;};
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down={x:0,y:0};const pointerDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};};const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(objects.children,true).find(h=>h.object.userData.boxId||h.object.userData.candidateId);if(hit)latest.current.onSelect?.(hit.object.userData.candidateId||hit.object.userData.boxId);};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);
 const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/Math.max(1,el.clientHeight);camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();let raf=0;let lastTcp:Vec3={x:DEFAULT_ROBOT_ARM.baseX+350,y:DEFAULT_ROBOT_ARM.baseY+300,z:1000};const lastRotation=new THREE.Quaternion();
 const tick=()=>{const p=latest.current;const armVisible=p.options.arm!==false&&p.scenario.constraints.robotMode!=='ideal';arm.group.visible=armVisible;if(p.path){const state=pathPosition(p.path,p.motion?p.progress||0:0);grip.visible=p.options.tool!==false&&p.scenario.constraints.robotMode!=='ideal';grip.position.fromArray(engineToRender(state.tcp,p.scenario.pallet));const rotation=poseQuaternion(state.fromPose).slerp(poseQuaternion(state.toPose),state.blend);grip.quaternion.copy(rotation);lastTcp={...state.tcp};lastRotation.copy(rotation);renderer.domElement.dataset.toolPose=String(state.toPose);renderer.domElement.dataset.toolYaw=state.yaw.toFixed(2);if(moving.children.length&&p.current){
 const observation=p.current!,size=p.candidate?.placement.size||observation.size,source=observation.pickupPosition??incomingPosition();
 const release=p.path.points.findIndex(point=>point.label==='내려놓기'),released=p.motion&&!state.carrying&&release>=0&&state.index>release;
 moving.quaternion.copy(p.motion?(released?poseQuaternion(p.candidate?.placement.orientation??0):rotation):poseQuaternion(0));
 const offset=new THREE.Vector3(0,-observation.size.h/2,0).applyQuaternion(rotation);const center=p.motion&&state.carrying?(p.path.fixedGrasp?{x:state.tcp.x+offset.x,y:state.tcp.y+offset.z,z:state.tcp.z+offset.y}:{x:state.tcp.x,y:state.tcp.y,z:state.tcp.z-movingHeight(observation.size,rotation)/2}):released&&p.candidate?centerOf(p.candidate.placement.position,size):centerOf(source,observation.size);
 moving.position.fromArray(engineToRender(center,p.scenario.pallet));}}
 if(!p.path){grip.position.fromArray(engineToRender(lastTcp,p.scenario.pallet));grip.quaternion.copy(lastRotation);grip.visible=p.options.tool!==false&&p.scenario.constraints.robotMode!=='ideal';}
 if(armVisible){const result=arm.update(lastTcp,lastRotation,p.scenario.constraints.gripper.height,p.options.armModel||DEFAULT_ROBOT_ARM,p.scenario.pallet,p.placements);const contacts=[...new Set(result.hits.filter(Boolean))],state=!result.pose.reachable?'unreachable':contacts.length?'interference':'following';renderer.domElement.dataset.arm=JSON.stringify({...result.pose,hits:contacts,state,model:p.options.armModel||DEFAULT_ROBOT_ARM,normal:new THREE.Vector3(0,1,0).applyQuaternion(lastRotation).toArray()});if(armStatus.current){armStatus.current.dataset.state=state;armStatus.current.textContent=!result.pose.reachable?`가상 팔 도달 불가 · 그리퍼 오차 ${result.pose.errorMm.toFixed(0)} mm`:contacts.length?`가상 팔 간섭 근사 · ${contacts.join(', ')} · 계획 미반영`:`가상 로봇팔 · ${p.motion?'경로 추적':'대기'} · 실제 기종 검증 별도`;}}
 renderer.domElement.dataset.armVisible=String(armVisible);controls.update();renderer.render(scene,camera);renderer.domElement.dataset.boxes=JSON.stringify(objects.children.filter((o:THREE.Object3D)=>o.userData.boxId).map((o:THREE.Object3D)=>{const v=o.position.clone().project(camera);return {id:o.userData.boxId,x:(v.x+1)*el.clientWidth/2,y:(1-v.y)*el.clientHeight/2};}));raf=requestAnimationFrame(tick);};tick();
 return()=>{cancelAnimationFrame(raf);observer.disconnect();controls.dispose();scene.traverse(o=>{const v=o as THREE.Mesh;if(v.userData.texture)v.userData.texture.dispose();v.geometry?.dispose();if(v.material){for(const m of Array.isArray(v.material)?v.material:[v.material])m.dispose();}});renderer.dispose();renderer.domElement.remove();stage.current=null;};
 },[]);
 useEffect(()=>{const s=stage.current;if(!s)return;const p=props.scenario.pallet,H=p.maxHeight/1000;s.controls.target.set(-.25,Math.min(.55,H*.35),0);if(props.camera==='cell'){const m=props.options.armModel||DEFAULT_ROBOT_ARM;const x=(m.baseX-p.width/2)/1000,z=(m.baseY-p.depth/2)/1000,maxY=(m.shoulderHeight+m.upperArm)/1000;const box=new THREE.Box3(new THREE.Vector3(Math.min(x-.35,-1.8,(BUFFER_SOURCE.x-p.width/2)/1000-.1),-.15,Math.min(z-.35,-p.depth/2000)),new THREE.Vector3(Math.max(x+.35,p.width/2000+.35),Math.max(H+.4,maxY),Math.max(z+.35,p.depth/2000+.35,(BUFFER_SOURCE.y+BUFFER_SIZE.d-p.depth/2)/1000+.15)));const sphere=box.getBoundingSphere(new THREE.Sphere()),half=Math.min(21*Math.PI/180,Math.atan(Math.tan(21*Math.PI/180)*s.camera.aspect)),distance=sphere.radius/Math.sin(half)*1.06;s.controls.maxDistance=Math.max(9,distance*1.5);s.controls.target.copy(sphere.center);s.camera.position.copy(sphere.center).add(new THREE.Vector3(-1,.7,1.1).normalize().multiplyScalar(distance));}else if(props.camera==='top')s.camera.position.set(-.25,4,.001);else if(props.camera==='front')s.camera.position.set(-.25,.8,3.8);else if(props.camera==='side')s.camera.position.set(3.8,.8,0);else s.camera.position.set(2.3,2.1,3);s.controls.update();},[props.camera,props.cameraVersion,props.scenario.pallet,props.options.armModel]);
 useEffect(()=>{if(props.cameraPose)stage.current?.applyCamera(props.cameraPose);},[props.cameraPose]);
 useEffect(()=>{const s=stage.current;if(!s)return;const {objects,moving,grip}=s;for(const g of [objects,moving,grip]){g.traverse((o:THREE.Mesh)=>{o.geometry?.dispose();if(o.userData.texture)o.userData.texture.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});g.clear();}
 const levels=[...new Set(props.placements.map(b=>b.position.z))].sort((a,b)=>a-b);const shifted=(position:Vec3)=>({...position,z:position.z+(props.options.explode?Math.max(0,levels.filter(h=>h<=position.z+1).length-1)*140:0)});
 const p=props.scenario.pallet,opt=props.options,accent=color('--color-accent'),gold=color('--color-gold'),rule=color('--color-rule'),ink=color('--color-ink'),danger=color('--color-danger');
 const cube=(group:THREE.Group,size:number[],position:number[],paint:THREE.Color,opacity=1,id?:string,wire=false)=>{const geo=new THREE.BoxGeometry(...size as [number,number,number]);const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:paint,roughness:.65,transparent:opacity<1,opacity,depthWrite:opacity>.8,wireframe:wire}));mesh.position.fromArray(position);if(id?.startsWith('candidate:'))mesh.userData.candidateId=id;else if(id)mesh.userData.boxId=id;group.add(mesh);if(opt.outlines&&!wire){const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:id===props.selection?gold:rule,transparent:true,opacity:.9}));edge.position.copy(mesh.position);group.add(edge);}return mesh;};
 const line=(positions:Vec3[],paint:THREE.Color,overlay=false)=>{const g=new THREE.BufferGeometry().setFromPoints(positions.map(v=>new THREE.Vector3(...engineToRender(v,p))));const l=new THREE.Line(g,new THREE.LineBasicMaterial({color:paint,transparent:true,opacity:.7,depthTest:!overlay,depthWrite:!overlay}));if(overlay)l.renderOrder=1000;objects.add(l);};
 cube(objects,[p.width/1000,.14,p.depth/1000],[0,-.07,0],rule);const grid=new THREE.GridHelper(6,30,rule,rule);grid.position.y=-.145;objects.add(grid);const bound=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(p.width/1000,p.maxHeight/1000,p.depth/1000)),new THREE.LineBasicMaterial({color:rule,transparent:true,opacity:.65}));bound.position.y=p.maxHeight/2000;objects.add(bound);
 const label=(text:string,position:number[],paint:THREE.Color)=>{const c=document.createElement('canvas');c.width=512;c.height=64;const ctx=c.getContext('2d')!;ctx.fillStyle=paint.getStyle();ctx.font='28px '+getComputedStyle(document.documentElement).getPropertyValue('--font-mono');ctx.textAlign='center';ctx.fillText(text,256,44);const texture=new THREE.CanvasTexture(c),sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false}));sprite.scale.set(1,.125,1);sprite.position.fromArray(position);sprite.userData.texture=texture;objects.add(sprite);};
 label(`${p.width} × ${p.depth} mm`,[0,-.12,p.depth/2000+.13],ink);label(`높이 한계 ${p.maxHeight} mm`,[0,p.maxHeight/1000+.12,0],gold);label('입고 · 현재 박스',[-1.35,.06,.05],accent);const axes=new THREE.AxesHelper(.4);axes.position.set(-p.width/2000,0,-p.depth/2000);objects.add(axes);
 cube(objects,[.85,.1,.65],[-1.2,-.05,.02],rule);
 if(props.bufferEnabled||props.buffer?.length){
  cube(objects,[BUFFER_SIZE.w/1000,.08,BUFFER_SIZE.d/1000],engineToRender({x:BUFFER_SOURCE.x+BUFFER_SIZE.w/2,y:BUFFER_SOURCE.y+BUFFER_SIZE.d/2,z:-40},p),accent,.6);
  label('임시 대기 · 상단 복귀',engineToRender({x:BUFFER_SOURCE.x+BUFFER_SIZE.w/2,y:BUFFER_SOURCE.y+BUFFER_SIZE.d/2,z:90},p),gold);
  for(const h of props.buffer||[]){if(h.observation.id===props.current?.id)continue;const type=props.scenario.types.find(t=>t.id===h.observation.typeId);cube(objects,renderSize(h.observation.size),engineToRender(centerOf(h.source,h.observation.size),p),type?new THREE.Color(type.color):gold,.9);}
 }
 s.renderer.domElement.dataset.buffer=JSON.stringify((props.buffer||[]).map(h=>({id:h.observation.id,source:h.source,reservedTop:h.reservedTop.position})));
 s.renderer.domElement.dataset.pickup=JSON.stringify(props.current?.pickupPosition??incomingPosition());

 for(const b of props.placements){if(b.position.z>opt.slice)continue;const type=props.scenario.types.find(t=>t.id===b.typeId),materialTokens={paper:'--color-gold',plastic:'--color-accent',wood:'--color-L',unknown:'--color-existing'},paint=opt.material?color(materialTokens[b.material||'unknown']):opt.weight?new THREE.Color().lerpColors(accent,gold,Math.min(1,b.weight/12)):type?new THREE.Color(type.color):ink;const pose=props.physics?.poses.find(v=>v.id===b.id),position=pose?.actual||b.position;const mesh=cube(objects,renderSize(b.size),engineToRender(centerOf(shifted(position),b.size),p),paint,opt.opacity,b.id);if(pose){mesh.quaternion.fromArray(pose.rotation);cube(objects,renderSize(b.size),engineToRender(centerOf(shifted(b.position),b.size),p),rule,.5,undefined,true);}
  if(opt.supports)for(const support of b.supports){const r=support.rect;cube(objects,[r.w/1000,.003,r.d/1000],engineToRender({...shifted(b.position),x:r.x+r.w/2,y:r.y+r.d/2,z:shifted(b.position).z+2},p),accent,.75);}
 }
 if(props.current){const size=props.candidate?.placement.size||props.current.size,type=props.scenario.types.find(t=>t.id===props.current!.typeId);cube(moving,renderSize(props.current.size),[0,0,0],opt.material?color(props.current.material==='plastic'?'--color-accent':props.current.material==='paper'?'--color-gold':props.current.material==='wood'?'--color-L':'--color-existing'):type?new THREE.Color(type.color):ink);moving.position.fromArray(engineToRender(centerOf(props.current.pickupPosition??incomingPosition(),props.current.size),p));}
 if(opt.candidates){for(const c of [...(props.others||[]).filter(v=>v.id!==props.candidate?.id).slice(0,opt.candidateLimit??8),...(props.candidate?[props.candidate]:[])])cube(objects,renderSize(c.placement.size),engineToRender(centerOf(shifted(c.placement.position),c.placement.size),p),c.valid?accent:danger,c.id===props.candidate?.id ? .38 : .10,`candidate:${c.id}`,false);}
 if(opt.strategyDebug&&props.strategyDebug){
   const cfg=props.strategyConfig||DEFAULT_STRATEGY,slots=props.strategyDebug.reservedSlots;
   for(const slot of slots){const b=slot.placement,paint=new THREE.Color(props.scenario.types.find(t=>t.id===slot.typeId)?.color||'#bbaaff');if(b.position.z>opt.slice)continue;
    cube(objects,renderSize(b.size),engineToRender(centerOf(shifted(b.position),b.size),p),paint,.3,undefined,true);
    if(cfg.approach){const a=approachVolume(b,cfg);cube(objects,renderSize(a.size),engineToRender(centerOf(shifted(a.position),a.size),p),paint,.07);}
   }
   s.renderer.domElement.dataset.reservedSlots=String(slots.length);
 }else s.renderer.domElement.dataset.reservedSlots='0';
 if(opt.path&&props.path)line(props.path.points.map(v=>v.tcp),gold);
 if(props.scenario.constraints.robotMode!=='ideal'){const g=props.scenario.constraints.gripper;cube(grip,[g.width/1000,g.height/1000,g.depth/1000],[0,g.height/2000,0],ink,.65);for(const x of [-1,1])for(const y of [-1,1]){const cup=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.025,12),new THREE.MeshStandardMaterial({color:accent}));cup.position.set(x*g.width/4000,.012,y*g.depth/4000);grip.add(cup);}}else grip.visible=false;
 if(opt.center&&props.placements.length){const c=balance(props.placements,p).center,mark=new THREE.Mesh(new THREE.SphereGeometry(.04,16,12),new THREE.MeshBasicMaterial({color:gold}));mark.position.fromArray(engineToRender(c,p));objects.add(mark);line([{...c,z:0},c],gold);}
 const lower=stability(props.placements,props.scenario.constraints.stability).supports.filter(b=>b.loadAbove>1e-6&&(b.isBase||b.id===props.selection)&&b.planeZ<=opt.slice);
 s.renderer.domElement.dataset.poses=JSON.stringify(props.placements.map(b=>({id:b.id,orientation:b.orientation,size:b.size,position:b.position})));
 s.renderer.domElement.dataset.supportCenters=JSON.stringify(lower.map(b=>({id:b.id,center:b.center,supportCenter:b.supportCenter,offsetMm:b.offsetMm,reserve:b.reserve})));
 if(opt.center)for(const b of lower){const projection=shifted({x:b.center.x,y:b.center.y,z:b.planeZ+8}),anchor=shifted({...b.supportCenter,z:b.planeZ+8}),paint=b.reserve<0?danger:accent,mark=new THREE.Mesh(new THREE.SphereGeometry(.018,12,8),new THREE.MeshBasicMaterial({color:paint,depthTest:false,depthWrite:false,transparent:true}));mark.renderOrder=1000;mark.position.fromArray(engineToRender(projection,p));objects.add(mark);line([anchor,projection],paint,true);line([{...anchor,x:anchor.x-22},{...anchor,x:anchor.x+22}],paint,true);line([{...anchor,y:anchor.y-22},{...anchor,y:anchor.y+22}],paint,true);}
 },[props.strategyDebug,props.strategyConfig,props.buffer,props.bufferEnabled,props.scenario,props.placements,props.current,props.candidate,props.others,props.path,props.options,props.selection,props.physics]);
 return <div className="pallet-scene" ref={host} data-testid="pallet-scene" data-renderer={unavailable?'unavailable':'webgl'} data-pallet={JSON.stringify(props.scenario.pallet)} data-model={props.scenario.constraints.robotMode||'gripper'} data-exploded={props.options.explode?'true':'false'}>{unavailable&&<p className="pallet-fallback">WebGL을 사용할 수 없습니다. 적재 기록과 계산 결과는 아래 표에서 확인할 수 있습니다.</p>}{props.options.arm!==false&&props.scenario.constraints.robotMode!=='ideal'&&<div ref={armStatus} className="pallet-arm-status" aria-label="로봇팔 표시 상태">가상 로봇팔 · 경로 대기</div>}<span className="pallet-scene-hint">{props.options.explode?'층 분리 표시 · 수치/계획 좌표는 원래 값':'드래그 회전 · 우클릭 이동 · 휠 확대'}</span>{props.options.center&&<span className="pallet-center-legend">금색: 전체 무게중심 · 청록 점: 아랫단 하중 중심 · 십자: 받침 중심{props.physics?' · 계획 기준':''}</span>}<span className="pallet-axis">엔진 x · y 바닥 / z 높이 · mm</span></div>;
}
