import {useEffect,useMemo,useRef,useState} from 'react';
import type {Scenario} from '../types';
import type {Box,Config,Frame,Candidate} from './types';
import {DEFAULT_CONFIG,damageLabels,labels} from './types';
import {makeBoxes,volumes} from './shape';
import {initialFrame,metrics,validateConfig,validateBoxes} from './runtime';
import {assess} from './mechanics';
import {suctionCandidates} from './grasp';
import AdaptiveScene,{type Layers} from './AdaptiveScene';
import './adaptive.css';
import {captureRecord,type TraceRecord,type Topic,type Trial} from './performance';
import {PerformanceKpis,PerformanceDetails,PerformanceTimeline,PerformanceDiagnostics} from './PerformancePanel';
const pct=(n:number)=>Number.isFinite(n)?(n*100).toFixed(1)+'%':'—',num=(n:number,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';
function download(name:string,data:string,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Field({label,value,onChange,min=0,max=10000,step=1}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number}){return <label className="adaptive-field"><span>{label}</span><input aria-label={label} type="number" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></label>;}
type Comparison=Trial&{metrics:ReturnType<typeof metrics>};
export default function AdaptiveLab({active,sourceScenario}:{active:boolean;sourceScenario:Scenario}){
 const [config,setConfig]=useState<Config>(()=>({...structuredClone(DEFAULT_CONFIG),pallet:{...sourceScenario.pallet}})),[draft,setDraft]=useState(config),[liveFrame,setFrame]=useState(initialFrame),[running,setRunning]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('설정을 확인한 뒤 실행하세요.'),[selected,setSelected]=useState(''),[candidateId,setCandidateId]=useState(''),[rows,setRows]=useState<Comparison[]>([]),[json,setJson]=useState(''),[customBoxes,setCustomBoxes]=useState<Box[]|null>(null);
 const [history,setHistory]=useState<TraceRecord[]>([]),[cursor,setCursor]=useState<number|null>(null),[topic,setTopic]=useState<Topic>('stability');
 const frame=cursor===null?liveFrame:history.find(r=>r.frame.tick===cursor)?.frame||liveFrame;
 const [layers,setLayers]=useState<Layers>({transparent:false,nominal:true,observed:false,contacts:true,risk:false,suction:false,path:true,candidates:false}),worker=useRef<Worker|null>(null),pendingAction=useRef('init');
 const boxes=useMemo(()=>customBoxes||makeBoxes(config),[config,customBoxes]),mechanics=useMemo(()=>assess(frame.placed,config),[frame.placed,config]);
 const startWorker=(c:Config,input:Box[]|null=customBoxes)=>{worker.current?.terminate();setCursor(null);setHistory([]);setFrame(initialFrame());const w=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});worker.current=w;w.onmessage=e=>{const {type,data}=e.data;if(type==='frame'){setFrame(data.frame);setHistory(h=>data.frame.tick===0?[data.record]:[...h.filter(r=>r.frame.tick!==data.frame.tick),data.record]);if(pendingAction.current==='step'&&!data.frame.done)setStatus('한 단계 완료 · 후보와 실행 판정 확인');if(data.frame.done){setRunning(false);setStatus('실행 완료 · 미배치 이유와 비교 결과를 확인하세요.');}}if(type==='error'){setStatus(data);setRunning(false);setBusy(false);}if(type==='progress')setStatus(`비교 ${data.job}/${data.total} · ${data.mode} · 시드 ${data.seed} · 판단 ${data.tick}`);if(type==='comparison'){setRows(data);setBusy(false);setStatus('3개 시드 × A/B/C 비교 완료 · 동일 입력·동일 실행 판정');}};w.onerror=e=>{setStatus(e.message);setRunning(false);setBusy(false);};w.postMessage({type:'init',config:c,boxes:input||undefined});};
 useEffect(()=>{if(!active){worker.current?.terminate();worker.current=null;setRunning(false);setBusy(false);return;}startWorker(config);return()=>{worker.current?.terminate();worker.current=null;};},[active]);
 const update=(fn:(c:Config)=>void)=>setDraft(old=>{const c=structuredClone(old);fn(c);return c;});
 const apply=()=>{try{validateConfig(draft);setConfig(structuredClone(draft));setCustomBoxes(null);setFrame(initialFrame());setRunning(false);setBusy(false);setCandidateId('');setSelected('');setRows([]);startWorker(draft,null);setStatus('새 조건 적용 완료 · 실행 또는 한 단계 실행');}catch(e){setStatus(String(e));}};
 const action=(type:string)=>{setCursor(null);pendingAction.current=type;if(!worker.current)startWorker(config);if(liveFrame.done&&(type==='play'||type==='step')){startWorker(config);setFrame(initialFrame());}worker.current?.postMessage({type,config});setRunning(type==='play');setStatus(type==='play'?'온라인 계획·실행 중 · 계획에는 도착한 버퍼만 전달합니다.':type==='pause'?'일시정지 요청 · 현재 후보 검사 이후 정지':'한 단계 계산 중');};
 const chosen=frame.candidates.find(v=>v.id===candidateId)||frame.selected,selectedId=selected||frame.placed.at(-1)?.box.id||frame.buffer[0]?.id||'',box=boxes.find(v=>v.id===selectedId),placed=frame.placed.find(v=>v.box.id===selectedId),load=mechanics.loads[selectedId],grasps=useMemo(()=>box?suctionCandidates(box,config):[],[box,config]),observed=frame.observed.find(v=>v.box.id===selectedId);
 const currentRecord=useMemo(()=>history.find(r=>r.frame.tick===frame.tick)||captureRecord(frame,undefined,config,boxes.length),[history,frame,config,boxes.length]);
 const visibleHistory=useMemo(()=>history.filter(r=>r.frame.tick<=frame.tick),[history,frame.tick]);
 const jump=(tick:number,id:string,t?:Topic)=>{if(busy){worker.current?.terminate();worker.current=null;setBusy(false);}else worker.current?.postMessage({type:'pause'});setRunning(false);setCursor(tick);setSelected(id);setCandidateId('');setStatus('기록 재생 · 판단 '+tick+' · 실행 일시정지');if(t)setTopic(t);};
 const loadTrial=(r:Trial)=>{worker.current?.terminate();worker.current=null;setConfig(r.config);setDraft(r.config);setCustomBoxes(r.boxes);setFrame(r.frame);setHistory(r.history||[]);setCursor(null);setSelected('');setCandidateId('');setRunning(false);setBusy(false);setStatus(r.config.mode+' / 시드 '+r.config.seed+' 저장 결과 · 단계 재생 가능');};
 if(!active)return null;
 return <section className="adaptive-lab" aria-label="변형·관측 적재 실험">
 <header className="adaptive-heading"><div><small>PERFORMANCE / 모델 제약을 먼저 검증</small><h1>3D Mixed Palletizing · 성능 대시보드</h1></div><span>기존 계획기 보존 · mm / kg / s</span></header>
 <div className="adaptive-toolbar"><button className="primary" disabled={running||busy} onClick={()=>action('play')}>실행</button><button disabled={!running||busy} onClick={()=>action('pause')}>일시정지</button><button disabled={running||busy} onClick={()=>action('step')}>한 단계 실행</button><button onClick={()=>{setRunning(false);setBusy(false);setFrame(initialFrame());setRows([]);setCandidateId('');startWorker(config);setStatus('초기화 완료');}}>초기화</button><span role="status">{status}</span><button disabled={busy||running} onClick={()=>{setBusy(true);if(!worker.current)startWorker(config);worker.current?.postMessage({type:'compare',config,boxes:customBoxes||undefined});}}>A/B/C · 3개 시드 비교</button>{busy&&<button onClick={()=>{setBusy(false);startWorker(config);setStatus('비교 취소됨');}}>비교 취소</button>}</div>
 <p className="performance-condition"><b>시험 조건</b> · {config.pallet.width} × {config.pallet.depth} × {config.pallet.maxHeight} mm · {boxes.length}개 · 시드 {config.seed} · {config.mode} / 기준 A · 입력 순서 온라인 · 추상 수직 운반체 · 브라우저 Worker 1개</p>
 <PerformanceKpis record={currentRecord} history={visibleHistory} config={config} rows={rows} topic={topic} onTopic={t=>{setTopic(t);requestAnimationFrame(()=>document.querySelector('.performance-details')?.scrollIntoView({behavior:'smooth',block:'start'}));}}/>
 <div className="adaptive-grid">
 <aside className="adaptive-panel adaptive-controls"><h2>실험 조건 <small>01</small></h2>
 <label>알고리즘 모드<select aria-label="변형 알고리즘 모드" value={draft.mode} onChange={e=>update(c=>{c.mode=e.target.value as Config['mode'];})}><option value="A">A · 기존 Greedy 계획기</option><option value="B">B · 변형·EMS·정적 지지</option><option value="C">C · 하중·흡착·경로·재계획</option></select></label>
 <label>환경<select aria-label="적재 환경" value={draft.environment} onChange={e=>update(c=>{c.environment=e.target.value as Config['environment'];})}><option value="pallet">사방 개방 팔레트</option><option value="roll">앞쪽 개방 롤테이너</option></select></label>
 <Field label="난수 시드" value={draft.seed} onChange={v=>update(c=>{c.seed=Math.round(v);})}/>
 <Field label="박스 수" value={draft.count} min={1} max={96} onChange={v=>update(c=>{c.count=v;})}/>
 <Field label="버퍼 크기" value={draft.bufferSize} min={1} max={12} onChange={v=>update(c=>{c.bufferSize=v;})}/>
 <Field label="최대 높이 mm" value={draft.pallet.maxHeight} min={200} max={2000} onChange={v=>update(c=>{c.pallet.maxHeight=v;})}/>
 <Field label="변형 크기 mm" value={draft.deformation} max={60} onChange={v=>update(c=>{c.deformation=v;})}/>
 <Field label="손상 재료 잔여강도" value={draft.materialResidual} max={1} step={.05} onChange={v=>update(c=>{c.materialResidual=v;})}/>
 <details><summary>합성 손상 종류</summary>{Object.entries(damageLabels).map(([key,label])=><label className="adaptive-check" key={key}><input type="checkbox" checked={draft.damageKinds.includes(key as Box['damage'])} onChange={e=>update(c=>{c.damageKinds=e.target.checked?[...c.damageKinds,key as Box['damage']]:c.damageKinds.filter(v=>v!==key);})}/>{label}</label>)}</details>
 <p className="adaptive-note">형상과 독립된 합성 가정값. 4개 중 1개에 적용하며 개별 강도는 입력 JSON에서 수정합니다.</p>
 <details><summary>관측 오차 · 각 항목 ±범위</summary>{([['dimensionMm','치수 mm'],['positionMm','위치 mm'],['surfaceMm','표면 mm'],['yawDeg','각도 °']] as const).map(([key,label])=><Field key={key} label={label} value={draft.noise[key]} max={30} step={.1} onChange={v=>update(c=>{c.noise[key]=v;})}/>)}<p>실제 형상은 유지됩니다. 관측 회전은 보수적 AABB로 근사합니다.</p></details>
 <details><summary>제약·기능·가중치 설정</summary>
 {Object.entries(draft.features).map(([key,on])=><label className="adaptive-check" key={key}><input type="checkbox" checked={on} onChange={e=>update(c=>{c.features[key as keyof Config['features']]=e.target.checked;})}/>{{load:'누적 하중',suction:'흡착 기하',path:'경로 검사',buffer:'버퍼 선택',replan:'실패 후 재계획',alignment:'기하 정렬 실험 · 접촉력 미검증'}[key]}</label>)}
 <p>기능 해제는 계획기 비교용입니다. 모든 모드의 실행 판정에는 전체 제약을 유지합니다.</p>
 <Field label="최소 지지율" value={draft.supportRatio} min={.1} max={1} step={.05} onChange={v=>update(c=>{c.supportRatio=v;})}/>
 <Field label="접촉 허용오차 mm" value={draft.contactMm} step={.1} onChange={v=>update(c=>{c.contactMm=v;})}/>
 <Field label="관통 허용오차 mm" value={draft.penetrationMm} step={.01} onChange={v=>update(c=>{c.penetrationMm=v;})}/>
 <Field label="흡착컵 지름 mm" value={draft.cup.diameterMm} min={10} onChange={v=>update(c=>{c.cup.diameterMm=v;})}/>
 <Field label="무지지 간격 한도 mm" value={draft.maxBridgeMm} onChange={v=>update(c=>{c.maxBridgeMm=v;})}/>
 <Field label="재시도 상한" value={draft.maxRetries} max={5} onChange={v=>update(c=>{c.maxRetries=v;})}/>
 {Object.entries(draft.weights).map(([key,value])=><Field key={key} label={'가중치 · '+({height:'높이',space:'빈 공간',support:'지지',load:'하중',path:'경로',suction:'흡착',waiting:'대기',retry:'재시도 비용',foundation:'후속 받침'}[key])} value={value} max={20} step={.5} onChange={v=>update(c=>{c.weights[key as keyof Config['weights']]=v;})}/>)}
 {draft.environment==='roll'&&<>{(['left','right','back'] as const).map(key=><label className="adaptive-check" key={key}><input type="checkbox" checked={draft.walls[key]} onChange={e=>update(c=>{c.walls[key]=e.target.checked;})}/>{{left:'왼쪽',right:'오른쪽',back:'뒤쪽'}[key]} 벽</label>)}<label className="adaptive-check"><input type="checkbox" checked={draft.frontFill} onChange={e=>update(c=>{c.frontFill=e.target.checked;})}/>앞쪽 채우기 선호</label></>}
 </details><button className="primary" onClick={apply}>조건 적용 · 새 실행 준비</button>
 <details><summary>입력 JSON · 개별 형상·강도</summary><button onClick={()=>setJson(JSON.stringify({config,boxes},null,2))}>현재 입력 불러오기</button><textarea aria-label="변형 실험 입력 JSON" value={json} onChange={e=>setJson(e.target.value)}/><button onClick={()=>{try{const v=JSON.parse(json);validateConfig(v.config);validateBoxes(v.boxes);if(!Array.isArray(v.boxes)||!v.boxes.length||v.boxes.length>96||new Set(v.boxes.map((b:Box)=>b.id)).size!==v.boxes.length)throw Error('박스 ID·수량을 확인하세요.');setConfig(v.config);setDraft(v.config);setCustomBoxes(v.boxes);setRows([]);setFrame(initialFrame());setRunning(false);startWorker(v.config,v.boxes);setStatus('개별 입력 적용');}catch(e){setStatus(String(e));}}}>입력 적용</button></details>
 </aside>
 <div className="adaptive-stage"><div className="adaptive-stage-title"><b>형상·접촉 디지털 실험</b><span>판단 {frame.tick} · 도착 {frame.arrived}/{boxes.length} · {config.mode} 모드</span></div>
 <AdaptiveScene analysis={currentRecord.analysis} config={config} frame={frame} boxes={boxes} selected={selectedId} candidate={chosen} layers={layers} onSelect={setSelected}/>
 <PerformanceTimeline history={history} cursor={cursor} onJump={jump} onLive={()=>setCursor(null)}/>
 <div className="adaptive-layer-controls">{Object.entries(layers).map(([key,on])=><label key={key}><input type="checkbox" checked={on} onChange={e=>setLayers(l=>({...l,[key]:e.target.checked}))}/>{{transparent:'반투명',nominal:'정상 윤곽',observed:'관측 형상',contacts:'접촉 영역',risk:'하중 사용률',suction:'흡착 가능 영역',path:'이동 경로',candidates:'탈락 후보'}[key]}</label>)}</div>
 <section className="adaptive-buffer"><h3>현재 도착한 버퍼 <small>미도착 박스는 계획기에 전달되지 않습니다.</small></h3><div>{frame.buffer.length?frame.buffer.map(p=><button key={p.id} onClick={()=>setSelected(p.id)}>{p.id}<small>대기 {p.wait} · 시도 {p.attempts}</small></button>):<p>대기 박스 없음</p>}</div></section>
 <p className="adaptive-note">드래그 회전 · 휠 확대 · 박스 클릭 분석. 실선: 정상 규격 · 적색 윤곽: 관측 · 청록: 접촉/경로 · 황색: 선택 흡착점. 하중 색: 청록 ≤80% / 황토 80% 초과 / 적색 초과 / 회색 강도 미확인(표시용 구간).</p>
 </div>
 <aside className="adaptive-panel adaptive-inspector"><PerformanceDiagnostics history={history} config={config} onJump={jump}/><h2>판단 근거 <small>02</small></h2>
 <label>박스 선택<select aria-label="변형 박스 선택" value={selectedId} onChange={e=>setSelected(e.target.value)}><option value="">박스 선택</option>{boxes.slice(0,frame.arrived).map(b=><option key={b.id} value={b.id}>{b.id} · {damageLabels[b.damage]}</option>)}</select></label>
 {box?<><h3>{box.id} · {damageLabels[box.damage]}</h3><dl>
 <dt>질량 / 마찰계수</dt><dd>{box.mass} kg / {num(box.friction,2)}</dd><dt>정상 규격</dt><dd>{box.nominal.w} × {box.nominal.d} × {box.nominal.h} mm</dd>
 <dt>손상 위치 · 로컬 mm</dt><dd>{box.shapeDamage?.map(d=>[d.region.x,d.region.y,d.region.z].map(v=>num(v,0)).join('/')).join(' · ')||'없음 / 사용자 형상'}</dd><dt>재료 강도 출처</dt><dd>{{assumption:'시뮬레이션 가정',measured:'실측 입력',unknown:'미확인','research-example':'특정 연구 예시'}[box.strength.source]} · 잔여 {pct(box.strength.residual)}</dd>
 <dt>상부하중 / 허용</dt><dd>{load?num(load.aboveKg,2):'—'} / {load?.capacityKg===null||box.strength.topLoadKg===null?'미확인':num((box.strength.topLoadKg||0)*box.strength.residual,2)} kg</dd>
 <dt>자중 포함 반력</dt><dd>{load?num(load.reactionKg,2)+' kg 상당':'—'}</dd>
 <dt>하중 사용률</dt><dd>{load?.capacityKg?pct(load.aboveKg/load.capacityKg):'—'}</dd>
 <dt>실제 지지율</dt><dd>{placed?pct(assess(frame.placed,config,selectedId).supportRatio):'미배치'}</dd>
 <dt>합력 작용점 x/y</dt><dd>{load?num(load.resultant.x)+' / '+num(load.resultant.y)+' mm':'—'}</dd>
 <dt>흡착 기하 후보</dt><dd>{grasps.filter(v=>v.valid).length} / {grasps.length} · 밀봉/진공 미검증</dd>
 <dt>관측 위치 오차</dt><dd>{placed&&observed?num(Math.hypot(placed.position.x-observed.position.x,placed.position.y-observed.position.y,placed.position.z-observed.position.z))+' mm · '+num(observed.yawErrorDeg,2)+'°':'—'}</dd>
 {Object.entries(volumes(box)).filter(([k])=>k!=='method').map(([key,value])=><div className="adaptive-dl-row" key={key}><dt>{{nominalVolume:'정상 부피',occupiedVolume:'외형 점유 부피',envelopeVolume:'경계상자 부피'}[key]}</dt><dd>{num(Number(value)/1e6,2)} L</dd></div>)}
 </dl><p className="adaptive-failure">{(frame.rejected.find(v=>v.id===selectedId)?.reasons||frame.buffer.find(v=>v.id===selectedId)?.reasons||[]).map(r=>labels[r]||r).join(' · ')}</p></>:<p>실행 후 박스를 클릭하면 접촉·하중·흡착 근거를 표시합니다.</p>}
 <h3>배치 후보</h3><select aria-label="변형 배치 후보" value={candidateId||frame.selected?.id||''} onChange={e=>setCandidateId(e.target.value)}><option value="">선택된 후보</option>{frame.candidates.map(v=><option key={v.id} value={v.id}>{v.reasons.length?'탈락':'유효'} {v.id} · z {num(v.position.z,0)}</option>)}</select>
 {chosen&&<><p className={chosen.reasons.length?'adaptive-failure':''}>{chosen.reasons.length?chosen.reasons.map(r=>labels[r]||r).join(' · '):'계획 제약 통과 · 실제 상태에서 다시 판정'}</p><dl><dt>위치 x/y/z</dt><dd>{[chosen.position.x,chosen.position.y,chosen.position.z].map(v=>num(v,0)).join(' / ')} mm</dd><dt>점수</dt><dd>{num(chosen.score,3)} · {chosen.rotation}°</dd>{Object.entries(chosen.terms).map(([key,v])=><div className="adaptive-dl-row" key={key}><dt>{{height:'높이 여유',space:'잔여 공간',support:'지지',load:'하중 여유',path:'경로',suction:'흡착',waiting:'대기',retry:'재시도 비용',foundation:'후속 받침',baseline:'기존 점수'}[key]||key}</dt><dd>{num(v,3)}</dd></div>)}</dl></>}
 <details open><summary>판정 범위</summary><p>정적 비음수 반력·힘/모멘트 평형과 복합 충돌체를 검사합니다. 진공 밀봉·유연 골판지 굽힘·운송 진동·로봇 IK·접촉력 순응은 미검증입니다.</p><p>벽은 경로 장애물입니다. 측면 마찰 지지로 계산하지 않습니다.</p></details>
 </aside></div>
 <PerformanceDetails record={currentRecord} history={visibleHistory} config={config} rows={rows} topic={topic} onTopic={setTopic} boxes={boxes} onJump={jump} onTrial={loadTrial}/>
 <section className="adaptive-comparison adaptive-panel"><details><summary>원자료 · 비교표 · JSON / CSV 내보내기</summary><div className="adaptive-section-title"><h2>재현 가능한 비교 <small>03</small></h2><div><button disabled={!rows.length} onClick={()=>download('adaptive-comparison.json',JSON.stringify({version:1,rows},null,2))}>비교 JSON</button><button disabled={!rows.length} onClick={()=>{const keys=['mode','seed','placed','unplaced','utilization','nominalFulfilled','heightMm','retries','waitTicks','planningMs','modelExecutionSeconds'] as const;download('adaptive-comparison.csv',keys.join(',')+'\n'+rows.map(r=>keys.map(k=>r.metrics[k]).join(',')).join('\n'),'text/csv');}}>비교 CSV</button><button disabled={!history.length} onClick={()=>download('adaptive-stages.csv',['tick,placed,box_id,completion,occupied_utilization,center_x_mm,center_y_mm,center_z_mm,min_margin_mm,tipping_g,plan_ms,model_work_s,path_m,returned_candidates,valid_candidates',...history.map(r=>[r.frame.tick,r.frame.placed.length,r.placedId||'',r.analysis.completion,r.analysis.utilization,r.analysis.center?.x??'',r.analysis.center?.y??'',r.analysis.center?.z??'',r.analysis.minMarginMm??'',r.analysis.tippingG??'',r.planMs,r.workSeconds,r.pathMm===null?'':r.pathMm/1000,r.candidateCount,r.validCandidates].join(','))].join('\n'),'text/csv')}>단계 평가 CSV</button><button onClick={()=>download('adaptive-run.json',JSON.stringify({version:2,config,boxes,frame:liveFrame,history,metrics:metrics(liveFrame,boxes,config),scope:'단계별 기하·정적 근사; 실물 로봇·진공 미검증'},null,2))}>현재 실행 JSON</button></div></div>
 <p>동일 실제 박스·물성·입고 순서·관측 시드·환경·실행 판정. A는 기존 Greedy의 현재 박스 모드이며 전체 미래 재고를 제공하지 않습니다. B는 형상·정적 지지, C는 모든 선택 제약을 사용합니다.</p>
 {rows.length?<div className="adaptive-table-wrap"><table><thead><tr>{['모드 / 시드','배치 / 입력','외형 사용률','정상 부피 완료율','높이 mm','실행 거절','재시도','계획 ms','최종 위반','결과 보기'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.metrics.mode+r.metrics.seed}><td>{r.metrics.mode} / {r.metrics.seed}</td><td>{r.metrics.placed}/{r.metrics.input}</td><td>{pct(r.metrics.utilization)}</td><td>{pct(r.metrics.nominalFulfilled)}</td><td>{num(r.metrics.heightMm,0)}</td><td>{r.metrics.placementFail}</td><td>{r.metrics.retries}</td><td>{num(r.metrics.planningMs,0)}</td><td>{r.metrics.finalViolations.map(v=>labels[v]||v).join(', ')||'없음'}</td><td><button onClick={()=>{loadTrial(r);}}>{r.metrics.mode}/{r.metrics.seed} 3D 보기</button></td></tr>)}</tbody></table></div>:<p className="adaptive-empty">상단의 비교 실행으로 실제 측정값을 생성합니다. 높은 공간 사용률과 안정성, 계산시간이 항상 함께 개선되지는 않습니다.</p>}
 <details><summary>실행 로그 · 미배치 이유</summary>{frame.events.slice(-40).map((e,i)=><p key={i}>{e.tick} · {e.id} · {e.kind} {e.reasons.map(r=>labels[r]||r).join(' / ')}</p>)}{frame.rejected.map(p=><p key={p.id}>{p.id} · 미배치: {p.reasons.map(r=>labels[r]||r).join(' / ')}</p>)}</details>
 </details></section></section>;
}
