import {useEffect,useMemo,useState} from 'react';
import type {Box,Config} from './types';
import {labels} from './types';
import {analyzeFrame,diagnostics,latency,pairedBaseline,robustness,topics,type Topic,type TraceRecord,type Trial} from './performance';
import './performance.css';
const n=(v:number|null|undefined,d=1)=>v===null||v===undefined||!Number.isFinite(v)?'미검증':v.toFixed(d);
const pct=(v:number|null|undefined)=>v===null||v===undefined?'미검증':n(v*100)+'%';
type Common={record:TraceRecord;history:TraceRecord[];config:Config;rows:Trial[];topic:Topic;onTopic:(t:Topic)=>void};
export function PerformanceKpis({record:r,history,config:c,rows,topic,onTopic}:Common){
 const a=r.analysis,l=latency(history,c.timeBudgetMs),rob=robustness(rows,c.mode),gs=history.flatMap(r=>r.analysis.tippingG===null?[]:[r.analysis.tippingG]),g=gs.length?Math.min(...gs):null;
 const robot=r.frame.placed.length?r.frame.executionSeconds/r.frame.placed.length:null;
 const items:[Topic,string,string][]=[['fitness',a.overallStatus,`기하·정적 제약 ${a.geometryStatus} · 위반 ${a.reasons.length}종`],['space',a.reasons.length?'미판정':pct(a.completion),`외형 공간 ${pct(a.utilization)} · ${r.frame.placed.length}개 적재`],['stability',g===null?'미검증':n(g,3)+' g',`기록 최저 · 정적 강체 근사 / 국부 여유 ${n(a.minMarginMm)} mm`],['robot',robot===null?'미검증':n(robot)+' 초/박스','수직 접근 실행 모델 · 실물 로봇 미검증'],['compute',l.p99===null?'미검증':n(l.p99)+' ms',`P99 · 기한 내 유효 후보 ${pct(l.validOnTime)} · n=${l.count}`],['robustness',pct(rob.success),`${c.mode} 모드 ${rob.count}회 · 모델 제약+전량 완료 / 예외 복구 미검증`]];
 return <div className="performance-kpis" aria-label="6개 핵심 성능 지표">{items.map(([key,value,detail],i)=><button key={key} aria-pressed={topic===key} onClick={()=>onTopic(key)} className={key==='fitness'&&value==='실패'?'danger':''}><small>{String(i+1).padStart(2,'0')} · {key==='space'?'적재 성과':topics[key]}</small><strong>{value}</strong><span>{detail}</span></button>)}</div>;
}
export function PerformanceDiagnostics({history,config,onJump}:{history:TraceRecord[];config:Config;onJump:(tick:number,id:string,t:Topic)=>void}){
 const items=useMemo(()=>diagnostics(history,config),[history,config]);
 return <section className="performance-diagnostics"><h2>위험 및 성능 진단</h2><p>위반 → 지지 여유 → 계산 지연 순 · 선택하면 단계와 박스로 이동</p>{items.map((v,i)=><button key={i} onClick={()=>onJump(v.tick,v.id,v.topic)}><span>{i+1}. {v.label}</span><b>{v.value.split(' / ').map(s=>labels[s]||s).join(' · ')}</b><small>판단 {v.tick} {v.id&&'· '+v.id} ↗</small></button>)}{!items.length&&<p>실행하면 기록된 위험 지점이 표시됩니다.</p>}</section>;
}
export function PerformanceTimeline({history,cursor,onJump,onLive}:{history:TraceRecord[];cursor:number|null;onJump:(tick:number,id:string,t?:Topic)=>void;onLive:()=>void}){
 const [replay,setReplay]=useState(false);
 const index=cursor===null?Math.max(0,history.length-1):Math.max(0,history.findIndex(r=>r.frame.tick===cursor)),r=history[index];
 const go=(i:number)=>{const row=history[i];if(row)onJump(row.frame.tick,row.placedId||'');};
 useEffect(()=>{if(!replay)return;if(index>=history.length-1){setReplay(false);return;}const timer=setTimeout(()=>go(index+1),650);return()=>clearTimeout(timer);},[replay,index,history.length]);
 useEffect(()=>{if(cursor===null)setReplay(false);},[cursor]);
 return <div className="performance-timeline"><button disabled={history.length<2} aria-pressed={replay} onClick={()=>{if(!replay&&(cursor===null||index>=history.length-1))go(0);setReplay(v=>!v);}}>{replay?'기록 일시정지':'기록 재생'}</button><button aria-label="이전 기록" disabled={index<=0} onClick={()=>go(index-1)}>◀</button><input aria-label="적재 판단 기록 재생" type="range" min={0} max={Math.max(0,history.length-1)} value={index} disabled={!history.length} onChange={e=>go(Number(e.target.value))}/><button aria-label="다음 기록" disabled={index>=history.length-1} onClick={()=>go(index+1)}>▶</button><span>판단 {r?.frame.tick||0} / {history.at(-1)?.frame.tick||0} · 적재 {r?.frame.placed.length||0}개</span><button aria-pressed={cursor===null} onClick={()=>{setReplay(false);onLive();}}>실시간 보기</button></div>;
}
function Chart({history,value,unit,onJump,deadline}:{history:TraceRecord[];value:(r:TraceRecord)=>number|null;unit:string;onJump:(tick:number,id:string,t?:Topic)=>void;deadline?:number}){
 const rows=history.filter(r=>r.frame.tick>0&&value(r)!==null),max=Math.max(1,deadline||0,...rows.map(r=>Math.abs(value(r)!)));
 return <><div className="performance-chart" aria-label={'단계별 '+unit+' 그래프'}>{rows.map(r=><button key={r.frame.tick} aria-label={`판단 ${r.frame.tick}: ${n(value(r),2)} ${unit}`} title={`판단 ${r.frame.tick} · ${r.placedId||'배치 없음'} · ${n(value(r),2)} ${unit}`} onClick={()=>onJump(r.frame.tick,r.placedId||'')}><i className={value(r)!<0||(deadline!==undefined&&value(r)!>deadline)?'late':''} style={{height:Math.max(2,100*Math.abs(value(r)!)/max)+'%'}}/><small>{r.frame.tick}</small></button>)}{deadline!==undefined&&<span className="performance-deadline" style={{bottom:24+110*deadline/max}}>기한 {deadline} ms</span>}</div><p>가로축: 판단 단계 · 세로축: {unit}. 막대 길이는 절댓값이며 음수 또는 기한 초과는 적색입니다. 선택하면 해당 3D 상태를 재생합니다.{!rows.length&&' 아직 측정 기록이 없습니다.'}</p></>;
}
function CenterMap({r,c}:{r:TraceRecord;c:Config}){const a=r.analysis,w=c.pallet.width,d=c.pallet.depth,pad=40,scale=240/Math.max(w,d),pt=(x:number,y:number)=>`${pad+x*scale},${pad+(d-y)*scale}`;
 return <figure className="performance-figure"><svg viewBox={`0 0 ${80+w*scale} ${80+d*scale}`} role="img" aria-label="실제 바닥 접촉 외곽과 전체 무게중심"><rect x={pad} y={pad} width={w*scale} height={d*scale} className="map-pallet"/>{a.hull.length>2&&<polygon points={a.hull.map(p=>pt(p.x,p.y)).join(' ')} className="map-hull"/>}{a.center&&<circle cx={pad+a.center.x*scale} cy={pad+(d-a.center.y)*scale} r="5" className="map-center"/>}<text x={pad} y={25}>Y ↑</text><text x={pad+w*scale-35} y={pad+d*scale+22}>X →</text></svg><figcaption>청록: 바닥 접촉의 볼록 외곽 · 점: 무게중심<br/>빈틈 자체가 지지되는 면은 아닙니다. 포크·지게차 안정성은 별도 미검증입니다.</figcaption></figure>;}
function DirectionMap({r}:{r:TraceRecord}){const values=r.analysis.directions,max=Math.max(.001,...values.map(v=>v.g)),point=(angle:number,radius:number)=>`${130+Math.cos(angle*Math.PI/180)*radius},${130-Math.sin(angle*Math.PI/180)*radius}`;
 return <figure className="performance-figure"><svg viewBox="0 0 260 260" role="img" aria-label="관성력 방향별 정적 전도한계"><circle cx="130" cy="130" r="85" className="map-pallet"/>{values.map(v=><g key={v.angle}><line x1="130" y1="130" x2={130+Math.cos(v.angle*Math.PI/180)*85} y2={130-Math.sin(v.angle*Math.PI/180)*85} className="map-axis"/><text x={130+Math.cos(v.angle*Math.PI/180)*106} y={134-Math.sin(v.angle*Math.PI/180)*106} textAnchor="middle">{n(v.g,2)}g</text></g>)}{values.length>0&&<polygon points={values.map(v=>point(v.angle,85*v.g/max)).join(' ')} className="map-hull"/>}</svg><figcaption>관성력 방향 0°(+X)부터 45° 간격 · 상대 눈금<br/>적재물 전체가 일체인 강체 가정. 미끄럼·국부 붕괴·동적 인증값이 아닙니다.</figcaption></figure>;}
export function PerformanceDetails({record:r,history,config:c,rows,topic,onTopic,boxes,onJump,onTrial}:{record:TraceRecord;history:TraceRecord[];config:Config;rows:Trial[];topic:Topic;onTopic:(t:Topic)=>void;boxes:Box[];onJump:(tick:number,id:string,t?:Topic)=>void;onTrial:(r:Trial)=>void}){
 const a=r.analysis,l=latency(history,c.timeBudgetMs),rob=robustness(rows,c.mode),center=a.center,paths=history.filter(h=>h.placedId&&h.pathMm!==null),distance=paths.reduce((s,h)=>s+h.pathMm!,0)/1000;
 const hardware=useMemo(()=>({agent:navigator.userAgent,threads:navigator.hardwareConcurrency||'미확인',memory:(navigator as Navigator&{deviceMemory?:number}).deviceMemory}),[]);
 return <section className="performance-details" aria-label="성능 상세 분석"><nav aria-label="성능 분석 항목">{Object.entries(topics).map(([key,label])=><button key={key} aria-pressed={topic===key} onClick={()=>onTopic(key as Topic)}>{label}</button>)}</nav><header><h2>{topics[topic]} <small>판단 {r.frame.tick} · {c.mode} / 시드 {c.seed}</small></h2><p>실제 기록만 표시 · 정적 근사 / 시뮬레이션 가정 / 미검증을 구분합니다.</p></header>
 {topic==='fitness'&&<><div className="performance-facts"><div><small>종합 실행 적합성</small><b>{a.overallStatus}</b></div><div><small>기하·정적 모델</small><b>{a.geometryStatus}</b></div><div><small>적재 상태 위반 종류</small><b>{a.reasons.length}</b></div><div><small>실행 중 거절 시도</small><b>{r.frame.attempts.placementFail}</b></div></div><p>{a.reasons.map(v=>labels[v]||v).join(' · ')||'현재 적재물의 모델 제약 위반 없음. 빈 상태는 검증 통과로 처리하지 않습니다.'}</p><p>경계·관통·지지·합력·누적 하중·회전은 모델에서 검사합니다. 후보/실행 거절은 실제 적재물의 위반과 구분합니다. 로봇 IK·전체 링크 충돌·진공 밀봉·재료 실측 강도·운송 안정성은 미검증이므로 종합 적합성을 ‘통과’로 표시하지 않습니다.</p><p>‘무거운 박스를 가벼운 박스 위에 금지’ 규칙은 이 변형 실험의 별도 제약으로 구현되지 않았습니다. 누적 하중과 입력 상부하중 한도를 검사하며, 두 조건을 같은 것으로 표시하지 않습니다.</p></>}
 {topic==='stability'&&<><div className="performance-stability"><CenterMap r={r} c={c}/><DirectionMap r={r}/><dl><dt>전체 질량중심 X / Y / Z</dt><dd>{center?[center.x,center.y,center.z].map(v=>n(v)).join(' / ')+' mm':'미검증'}</dd><dt>X / Y 편심률 · 중심에서 반폭 대비</dt><dd>{center?pct(Math.abs(center.x-c.pallet.width/2)/(c.pallet.width/2))+' / '+pct(Math.abs(center.y-c.pallet.depth/2)/(c.pallet.depth/2)):'미검증'}</dd><dt>전체 접촉 외곽 최소 여유</dt><dd>{n(a.globalMarginMm)} mm</dd><dt>현재 정적 전도한계 · d / h</dt><dd>{n(a.tippingG,3)} g</dd><dt>최소 국부 합력 여유 / 설계 한도</dt><dd>{n(a.minMarginMm)} / {c.edgeMarginMm} mm</dd><dt>최소 바닥 지지율 / 설계 한도</dt><dd>{pct(a.minSupport)} / {pct(c.supportRatio)}</dd></dl></div><Chart history={history} value={r=>r.analysis.minMarginMm} unit="국부 합력 여유 mm" onJump={onJump}/><div className="performance-table"><table><thead><tr>{['박스','지지면적률','합력 여유 mm','상부 / 허용 kg','사용률','강도 출처','검사'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{a.boxes.map(b=><tr key={b.id}><td><button onClick={()=>onJump(r.frame.tick,b.id,'stability')}>{b.id} ↗</button></td><td>{pct(b.support)}</td><td>{n(b.marginMm)}</td><td>{n(b.aboveKg)} / {n(b.capacityKg)}</td><td>{b.capacityKg===0?'상부 적재 금지':pct(b.loadRatio)}</td><td>{{assumption:'합성 가정',measured:'실측 입력',unknown:'미확인','research-example':'연구 예시'}[b.strengthSource]}</td><td>{b.reasons.map(v=>labels[v]||v).join(' · ')||'국부 모델 통과'}</td></tr>)}</tbody></table></div></>}
 {topic==='space'&&<><div className="performance-facts"><div><small>완료 / 전체 입력</small><b>{r.frame.placed.length} / {boxes.length}</b></div><div><small>정격 공간 활용</small><b>{pct(a.utilization)}</b></div><div><small>최종 높이 / 상한</small><b>{n(a.heightMm,0)} / {c.pallet.maxHeight} mm</b></div><div><small>미배치 / 대기</small><b>{boxes.length-r.frame.placed.length} / {r.frame.buffer.length}</b></div></div><p>외형 복합 충돌체 합집합 {n(a.occupiedVolumeMm3/1e9,3)} m³ ÷ 팔레트 허용 체적. 정상 규격 적재 부피 {n(a.nominalVolumeMm3/1e9,3)} m³와 구분합니다. 동일 입력을 전량 적재하면 활용률은 같아질 수 있습니다.</p><Chart history={history} value={r=>r.analysis.utilization*100} unit="공간 활용률 %" onJump={onJump}/><p>남은 박스의 수용가능률: 미검증. 마지막 반환 후보만으로 전체 잔량의 가능 여부를 단정하지 않습니다.</p></>}
 {topic==='robot'&&<><div className="performance-facts"><div><small>기록된 운반 경로 총 길이</small><b>{paths.length?n(distance,2)+' m':'미검증'}</b></div><div><small>경로 / 기록 박스</small><b>{paths.length?n(distance/paths.length,2)+' m/박스':'미검증'}</b></div><div><small>실행 모델 총시간</small><b>{r.frame.placed.length?n(r.frame.executionSeconds)+' s':'미검증'}</b></div><div><small>실물 로봇 실행</small><b>미검증</b></div></div><p>속도 {c.gripper.speedMmS} mm/s의 수직 접근 운반체 모델. 길이는 기록된 상자 기준점의 궤적이며 TCP 회전 거리와 실제 관절 운동을 대체하지 않습니다. 작업시간은 가정 속도·집기/놓기 지연을 포함한 추정치입니다. 동작별 시간 분해·실물 초/박스·재취급은 미검증입니다.</p><Chart history={history.filter(h=>h.placedId)} value={r=>r.workSeconds} unit="모델 작업시간 s" onJump={onJump}/></>}
 {topic==='compute'&&<><div className="performance-facts">{[['P50',l.p50],['P95',l.p95],['P99',l.p99],['최대',l.max]].map(([key,v])=><div key={key}><small>{key} · 최근접 순위</small><b>{n(v as number|null)} ms</b></div>)}</div><p>표본 {l.count}회 · 설정 기한 {c.timeBudgetMs} ms · 시간 내 반환 {pct(l.onTime)} · 시간 내 유효 후보 반환 {pct(l.validOnTime)}. 후보가 없는 빠른 실패를 유효해로 세지 않습니다. 계획기 호출만 측정하며 렌더·평가/기록 비용은 제외됩니다.</p><Chart history={history} value={r=>r.planMs} unit="계획시간 ms" deadline={c.timeBudgetMs} onJump={onJump}/><p>반환 후보 합계 {history.reduce((n,r)=>n+r.candidateCount,0)}개 / 유효 후보 {history.reduce((n,r)=>n+r.validCandidates,0)}개. 탐색 전체 노드 수와 동일하지 않습니다.</p><p>브라우저 보고 논리 스레드: {hardware.threads} · 메모리 힌트: {hardware.memory?hardware.memory+' GB':'미확인'} · CPU/GPU 기종·전력 설정: 미확인. Worker 1개, 동일 비교 실행 안에서만 HW 조건을 공유합니다.</p><details><summary>측정 브라우저</summary><p>{hardware.agent}</p></details></>}
 {topic==='robustness'&&<><div className="performance-facts"><div><small>현재 모드 완료 시나리오</small><b>{rob.count}회</b></div><div><small>모델 제약 + 전량 적재 성공</small><b>{pct(rob.success)}</b></div><div><small>최악 완료율</small><b>{pct(rob.worst)}</b></div><div><small>하위 5% 완료율</small><b>{pct(rob.p05)}</b></div></div><p>현재 비교는 시드별 박스 세트·관측이 달라지는 합성 실험입니다. 동일 박스의 투입 순서만 바꾸는 시험이나 박스 누락·오인식·파손의 주입 실험은 아니므로 순서 강건성·예외 복구율은 미검증입니다. n=3의 하위 5%는 사실상 최솟값이며 일반 성공 확률로 해석하지 않습니다.</p><div className="performance-trials">{rows.filter(row=>row.config.mode===c.mode).map((row,i)=><button key={i} onClick={()=>onTrial(row)}>{row.config.mode} / 시드 {row.config.seed} · {row.frame.placed.length}/{row.boxes.length}개 · {row.frame.placed.length===row.boxes.length?'전량 적재':'미완료 사례'} 재생 ↗</button>)}</div></>}
 {topic==='comparison'&&<><p>동일 박스·입고 순서·시드·설정의 A 기준과 쌍으로 비교합니다. 행의 차이는 B/C − A이며, 완료율은 %p입니다. 원본 A/B/C는 입력 버퍼 안에서의 선택 정책도 다릅니다. 전역 최적성을 주장하지 않습니다.</p><div className="performance-table"><table><thead><tr>{['모드 / 시드','완료율','완료율 Δ','국부 여유 Δ mm','계획시간 Δ ms','동일 조건','재생'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map((row,i)=>{const base=pairedBaseline(row,rows),v=analyzeFrame(row.frame,row.config,row.boxes.length),b=base?analyzeFrame(base.frame,base.config,base.boxes.length):null;return <tr key={i}><td>{row.config.mode}/{row.config.seed}</td><td>{pct(v.completion)}</td><td>{b?n((v.completion-b.completion)*100)+' %p':'비교 제외'}</td><td>{b&&v.minMarginMm!==null&&b.minMarginMm!==null?n(v.minMarginMm-b.minMarginMm):'미검증'}</td><td>{base?n(row.frame.planningMs-base.frame.planningMs):'미검증'}</td><td>{base?'입력·설정 일치':'짝 없음'}</td><td><button onClick={()=>onTrial(row)}>결과 재생 ↗</button></td></tr>;})}</tbody></table></div></>}
 </section>;
}
