import type { Lab } from '../hooks/useLab';
import { useComparison, type Run } from '../hooks/useComparison';
import { Board } from './Board';
import { Icon } from './Icon';
import { formatScore } from '../engine/evaluate';
import { STRATEGY_LABELS, wellColumn } from '../engine/strategy';
const names=['한 수 선택','2수 완전탐색','빔 탐색'],english=['Greedy','Exhaustive · 2 ply','Beam Search'];
function Chart({runs,metric}:{runs:Run[];metric:'lines'|'holes'}) {
  const maxN=Math.max(1,...runs.map(r=>r.count)),maxY=Math.max(1,...runs.flatMap(r=>r.records.map(p=>p[metric])));
  return <svg className="comparison-chart" viewBox="0 0 600 160" role="img" aria-label={metric==='lines'?'블록 배치 수별 누적 제거 줄 그래프':'블록 배치 수별 현재 구멍 그래프'}>{[0,.5,1].map(t=><g key={t}><line className="chart-grid" x1="35" x2="582" y1={125-t*104} y2={125-t*104}/><text className="chart-label" x="26" y={130-t*104} textAnchor="end">{Math.round(t*maxY)}</text></g>)}{[0,.5,1].map(t=><text key={t} className="chart-label" x={35+t*545} y="149" textAnchor="middle">{Math.round(t*maxN)}</text>)}{runs.map((r,i)=><polyline key={i} className={`chart-line algorithm-${i}`} points={r.records.map(p=>`${35+p.n/maxN*545},${125-p[metric]/maxY*104}`).join(' ')} fill="none" strokeWidth="2"/>)}<text className="chart-label" x="588" y="149">수</text></svg>;
}
export function Comparison({lab}:{lab:Lab}) {
  const compare=useComparison(lab.board,lab.seed,lab.weights,lab.config);
  const viewing=compare.view!==null;
  return <div className="comparison-mode"><div className="compare-toolbar panel"><div><h2>같은 블록, 세 가지 생각</h2><p>동일한 초기 보드 · 시드 {lab.seed} · 공개 NEXT 5개 · HOLD 꺼짐 · {STRATEGY_LABELS[lab.config.strategy??'balanced']}</p></div><div className="compare-controls"><label>상한<select aria-label="비교 블록 상한" disabled={compare.running} value={compare.limit} onChange={e=>compare.setLimit(+e.target.value)}>{[10,25,50,100,200].map(n=><option key={n} value={n}>{n}블록</option>)}</select></label><button className="primary-button" disabled={compare.runs.every(r=>r.ended)} onClick={compare.running?compare.stop:compare.start}><Icon name={compare.running?'stop':'play'} size={16}/>{compare.running?'중지':'비교 실행'}</button><button className="icon-button" aria-label="비교 초기화" onClick={compare.reset}><Icon name="reset"/></button></div></div>
    <div className="compare-status"><span className={compare.running?'status-dot active-dot':'status-dot'}/>{compare.stopReason} · {compare.progress}번째 블록까지 동기화{viewing&&<button className="text-button" onClick={()=>compare.setView(null)}>최신 상태로</button>}</div>
    <div className="compare-boards">{compare.runs.map((run,i)=>{const snapshot=viewing?run.records.find(p=>p.n===compare.view)??run.records.at(-1)!:run.records.at(-1)!;return <section className="compare-board panel" key={i}><div className="section-heading"><h3><span className={`algorithm-mark algorithm-${i}`}/>{names[i]}</h3><span className="tiny-badge">{run.ended==='gameover'?'게임 오버':run.ended==='limit'?'상한 도달':'실행 가능'}</span></div><p className="algorithm-caption">{english[i]}{i===2?` · ${lab.config.depth}수 / K=${lab.config.width}`:''}</p><Board board={snapshot.board} wellColumn={wellColumn(lab.config.strategy)} showCoordinates={false} label={`${names[i]} 비교 보드`}/><div className="compare-metrics"><div><span>배치</span><b>{snapshot.n}<small>블록</small></b></div><div><span>제거</span><b>{snapshot.lines}<small>줄</small></b></div><div><span>구멍</span><b>{snapshot.holes}<small>칸</small></b></div><div><span>최대 높이</span><b>{snapshot.maxHeight}</b></div></div><div className="compare-tetrises">4줄 삭제 <b>{snapshot.tetrises}</b>회</div>{!viewing&&<p className="compare-clear-counts">1줄 {run.clearCounts[1]} · 2줄 {run.clearCounts[2]} · 3줄 {run.clearCounts[3]} · 4줄 {run.clearCounts[4]}회</p>}<div className="compare-cost">{(viewing?snapshot.nodes:run.nodes).toLocaleString()}개 탐색 · {(viewing?snapshot.ms:run.ms).toFixed(1)} ms</div></section>;})}</div>
    <div className="compare-charts"><section className="panel"><h3>누적 제거 줄 수</h3><Chart runs={compare.runs} metric="lines"/></section><section className="panel"><h3>현재 구멍 수</h3><Chart runs={compare.runs} metric="holes"/></section></div>
    <div className="compare-bottom"><div className="chart-legend">{names.map((n,i)=><span key={n}><i className={`algorithm-mark algorithm-${i}`}/>{n}</span>)}</div><button disabled={!compare.divergence} onClick={()=>{compare.stop();compare.setView(Math.max(0,(compare.divergence?.n??1)-1));}}><Icon name="eye" size={15}/>처음 다른 수를 선택한 순간</button></div>
    {viewing&&compare.divergence&&<section className="divergence panel"><h3>{compare.divergence.n}번째 결정 · 같은 상태에서 다른 선택</h3><div className="divergence-boards">{compare.divergence.actions.map((action,i)=><div key={i}><b>{names[i]}</b><Board board={compare.divergence!.board} ghost={action??undefined} mini showCoordinates={false}/><p>{action?`회전 ${action.rotation} · x=${action.x} · 즉시 ${formatScore(compare.divergence!.scores[i])}`:'배치 불가'}</p></div>)}</div></section>}
    {compare.error&&<p className="error" role="alert">{compare.error}</p>}<p className="hint comparison-note">그래프는 실제 실행 기록입니다. 가로축은 배치한 블록 수이며, 한 시드의 결과로 성능 우열을 일반화하지 않습니다. 비교 공급은 시드 기반 7-bag이며, 학습용 고정 NEXT와 별도로 동일하게 세 실행에 공급합니다.</p>
  </div>;
}

