import type { Lab } from '../hooks/useLab';
import { STAGES } from '../engine/narration';
import { Icon } from './Icon';
export function Player({lab}:{lab:Lab}) {
  return <section className="player" aria-label="재생 컨트롤"><div className="player-inner"><div className="player-top"><div className="transport"><button className="icon-button" aria-label="이번 결정 처음으로" title="이번 결정 처음으로" onClick={lab.rewind}><Icon name="reset"/></button><button className="icon-button" aria-label="이전 설명 단계" title="이전 설명 단계" disabled={lab.busy||lab.step===0} onClick={()=>lab.seek(lab.step-1)}><Icon name="back"/></button><button className="play-button" aria-label={lab.playing?'일시정지 Space':'재생 Space'} aria-keyshortcuts="Space" disabled={(lab.busy||!lab.selected)&&!lab.playing||lab.editing} onClick={()=>lab.setPlaying(!lab.playing)}><Icon name={lab.playing?'pause':'play'}/>{lab.playing?'일시정지':'재생'}<kbd>Space</kbd></button><button className="icon-button" aria-label="다음 설명 단계" title="다음 설명 단계" disabled={lab.busy||lab.step===7} onClick={()=>lab.seek(lab.step+1)}><Icon name="next"/></button><button className="next-block" disabled={lab.busy||!lab.selected} onClick={lab.advance}><Icon name="skip" size={16}/>다음 블록까지</button></div>
      <div className="playback-options"><label className="speed-control"><span>배속</span><select aria-label="재생 배속" value={lab.speed} onChange={e=>lab.setSpeed(+e.target.value)}>{[.25,.5,1,2,4].map(v=><option key={v} value={v}>{v}×</option>)}</select></label><label><input type="checkbox" checked={lab.continuous} onChange={e=>lab.setContinuous(e.target.checked)}/>연속 자동 플레이</label><label><input type="checkbox" checked={lab.fast} onChange={e=>lab.setFast(e.target.checked)}/>빠른 적용</label><button className="reset-all" title="전체 초기화" aria-label="전체 초기화" onClick={lab.restore}><Icon name="reset" size={14}/>초기화</button></div></div>
    <div className="timeline">{STAGES.map((name,i)=><button key={name} disabled={lab.busy} className={`${i===lab.step?'active':''} ${i<lab.step?'passed':''} ${i===6?'final-step':''}`} onClick={()=>lab.seek(i)} aria-label={`${i+1} ${name}`} aria-current={i===lab.step?'step':undefined}><span className="timeline-dot">{i<lab.step?<Icon name="check" size={10}/>:i+1}</span><span>{name}</span></button>)}</div>
    <div className="player-foot"><span>설명 단계 {lab.step+1} / 8 <i>·</i> ← → 단계 이동</span><span>탐색 계산 {lab.analysis?.elapsedMs.toFixed(1)??'—'} ms <i>·</i> 설명 재생 {lab.replaySeconds.toFixed(1)} s</span></div>
  </div></section>;
}
