import { useEffect,useMemo,useRef,useState } from 'react';
import PalletScene,{type ViewOptions} from '../PalletScene';
import { algorithmRegistry,getAlgorithm } from '../benchmark/registry';
import { DEFAULT_ROBOT_ARM } from '../robotArm';
import { ROUTES,defaultAlpsConfig,shortlistAlps,summarizeAlps,pairedRoutingEffect,alpsCsv } from './experiment';
import type { AlpsConfig,AlpsTrial,Routing } from './experiment';
import type { Scenario } from '../types';
import './alps.css';

const display=(n:number|null|undefined,decimals=1)=>n===null||n===undefined?'미측정':n.toFixed(decimals);
function save(name:string,value:string){const url=URL.createObjectURL(new Blob([value],{type:name.endsWith('.csv')?'text/csv;charset=utf-8':'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const options:ViewOptions={opacity:1,outlines:true,slice:10000,weight:false,supports:true,center:true,candidates:false,path:false,material:false,explode:false,arm:true,armModel:{...DEFAULT_ROBOT_ARM}};
function TrialReplay({row,fraction,title}:{row?:AlpsTrial;fraction:number;title:string}){
 const [pallet,setPallet]=useState(0),[stage,setStage]=useState<'source'|'destination'>('source');
 const index=row?.trace.length?Math.min(row.trace.length-1,Math.floor(fraction*(row.trace.length-1))):0,step=row?.trace[index];
 const shown=step?.[stage]?.[pallet]??[],groupNames={apparel:'의류',other:'기타'};
 return <section className="alps-replay"><header><div><small>{title}</small><h3>{row?getAlgorithm(row.algorithm).name:'실행 결과 대기'}</h3><p>{row?`${ROUTES[row.route]} · 시드 ${row.seed}`:'동일 조건으로 실험한 기록을 이곳에서 재생합니다.'}</p></div><div className="alps-switch"><button aria-pressed={stage==='source'} onClick={()=>setStage('source')}>입고 팔레트</button><button aria-pressed={stage==='destination'} onClick={()=>setStage('destination')}>출고 팔레트</button><button aria-pressed={pallet===0} onClick={()=>setPallet(0)}>P1</button><button aria-pressed={pallet===1} onClick={()=>setPallet(1)}>P2</button></div></header>
 {row?<PalletScene scenario={row.scenario} placements={shown} selection={step?.boxId} options={options} camera="iso" cameraVersion={0}/>:<div className="alps-empty">실험 실행 또는 저장 결과 불러오기</div>}
 <div className="alps-step"><b>{step?`${index+1}/${row!.trace.length} · ${step.phase==='inbound'?'입고·중앙 지시':'재분배'}`:'기록 없음'}</b><span>{step?`${step.boxId} · ${groupNames[row!.groups[step.boxId]]} · ${step.action}`:row?'이 실행은 요약만 저장되어 있습니다. 같은 조건으로 다시 실행하면 전체 단계를 볼 수 있습니다.':'아직 측정하지 않았습니다.'}</span><span>{step?.reason}</span><span>임시 버퍼: {step?.held.join(', ')||'없음'}</span></div>
 <dl><dt>입고 적재 / 정상 입력</dt><dd>{row?`${row.placed} / ${row.normal}`:'—'}</dd><dt>출고 재적재</dt><dd>{row?.redistributed??'—'}</dd><dt>추가 임시 이동 / 버퍼 최대</dt><dd>{row?`${row.rehandles} / ${row.bufferPeak}`:'—'}</dd><dt>판단 계산 합계</dt><dd>{row?`${display(row.planMs,0)} ms`:'—'}</dd></dl></section>;
}
export default function AlpsLab({sourceScenario}:{sourceScenario:Scenario}){
 const [config,setConfig]=useState(defaultAlpsConfig),[recordConfig,setRecordConfig]=useState<AlpsConfig|null>(null),[rows,setRows]=useState<AlpsTrial[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState('실측 결과는 자동으로 가정하지 않습니다.'),[error,setError]=useState(''),[done,setDone]=useState(0),[total,setTotal]=useState(0),[mode,setMode]=useState<'pair'|'extremes'>('pair'),[algorithm,setAlgorithm]=useState(''),[route,setRoute]=useState<Routing>('dedicated'),[seed,setSeed]=useState(20261010),[fraction,setFraction]=useState(0),[playing,setPlaying]=useState(false);
 const worker=useRef<Worker|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),cancelled=useRef(false);
 useEffect(()=>()=>{cancelled.current=true;worker.current?.terminate();if(timer.current)clearTimeout(timer.current);},[]);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setFraction(f=>{if(f>=1){setPlaying(false);return 1;}return Math.min(1,f+.015);}),350);return()=>clearInterval(id);},[playing]);
 const discovery=useMemo(()=>summarizeAlps(rows,'discovery'),[rows]),holdout=useMemo(()=>summarizeAlps(rows,'holdout'),[rows]),shortlist=useMemo(()=>{
  if(busy||!recordConfig)return [];
  const complete=recordConfig.algorithms.every(a=>(Object.keys(ROUTES) as Routing[]).every(route=>rows.filter(r=>r.algorithm===a&&r.route===route&&r.split==='discovery').length===recordConfig.discovery));
  return complete?shortlistAlps(rows):[];
 },[rows,recordConfig,busy]),paired=useMemo(()=>pairedRoutingEffect(rows,route,'holdout'),[rows,route]);
 const chosen=algorithm||shortlist[0]?.algorithm||rows[0]?.algorithm;
 const candidates=rows.filter(r=>r.seed===seed&&r.trace.length);
 const best=candidates.filter(r=>r.status==='finished'&&!r.violations.length).sort((a,b)=>b.redistributed-a.redistributed||b.placed-a.placed||a.rehandles-b.rehandles||a.planMs-b.planMs);
 const left=mode==='pair'?candidates.find(r=>r.algorithm===chosen&&r.route==='pooled'):best.at(-1),right=mode==='pair'?candidates.find(r=>r.algorithm===chosen&&r.route===route):best[0];
 const change=<K extends keyof AlpsConfig>(key:K,value:AlpsConfig[K])=>setConfig(c=>({...c,[key]:value}));
 const stop=()=>{cancelled.current=true;worker.current?.terminate();worker.current=null;if(timer.current)clearTimeout(timer.current);setBusy(false);setMessage('중단했습니다. 완료된 실험은 보존했습니다.');};
 async function run(){
  if(!config.algorithms.length){setError('비교할 온라인 알고리즘을 하나 이상 선택하세요.');return;}
  const frozen=structuredClone(config);setRecordConfig(frozen);cancelled.current=false;setBusy(true);setPlaying(false);setRows([]);setError('');setDone(0);setFraction(0);setSeed(frozen.seed);setAlgorithm('');
  const jobs=Array.from({length:frozen.discovery+frozen.holdout},(_,i)=>frozen.algorithms.map((_,j)=>frozen.algorithms[(i+j)%frozen.algorithms.length]).flatMap(algorithm=>(Object.keys(ROUTES) as Routing[]).map(route=>({config:frozen,algorithm,route,seed:frozen.seed+i,split:i<frozen.discovery?'discovery' as const:'holdout' as const})))).flat();setTotal(jobs.length);
  try{for(const [i,job] of jobs.entries()){
   if(cancelled.current)break;setMessage(`${i+1}/${jobs.length} · ${getAlgorithm(job.algorithm).name} · ${ROUTES[job.route]} · ${job.split==='discovery'?'선정':'별도 확인'} 시드 ${job.seed}`);
   const result=await new Promise<AlpsTrial>((resolve,reject)=>{const w=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});worker.current=w;timer.current=setTimeout(()=>{w.terminate();reject(Error('개별 계획 호출이 시간 예산을 넘었습니다. 해당 실행은 점수화하지 않았습니다.'));},frozen.trialMs+10000);w.onmessage=e=>{if(timer.current)clearTimeout(timer.current);w.terminate();worker.current=null;e.data.type==='result'?resolve(e.data.row):reject(Error(e.data.message));};w.onerror=e=>{if(timer.current)clearTimeout(timer.current);w.terminate();reject(Error(e.message));};w.postMessage(job);});
   if(cancelled.current)break;setRows(r=>[...r,result]);setDone(i+1);
  }if(!cancelled.current)setMessage('실험 완료 · 별도 확인 시드와 제약 위반을 함께 확인하세요.');}
  catch(e){if(!cancelled.current)setError((e as Error).message);}finally{setBusy(false);}
 }
 async function load(){setLoading(true);setError('');try{const response=await fetch('/alps-results.json');if(!response.ok)throw Error('저장된 실측 보고서를 불러올 수 없습니다.');const data=await response.json();setRows(data.rows);setConfig(data.config);setRecordConfig(data.config);setSeed(data.config.seed);setAlgorithm('');setFraction(.48);setMessage(`저장된 실제 실행 ${data.rows.length}회 · ${data.measuredAt} · ${data.environment.platform} / ${data.environment.node}. 이 브라우저의 측정값은 아닙니다.`);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const numeric=(key:'discovery'|'holdout'|'seed'|'bufferCapacity',label:string,min:number,max:number)=><label>{label}<input type="number" value={config[key]} min={min} max={max} disabled={busy} onChange={e=>change(key,Math.max(min,Math.min(max,Math.round(Number(e.target.value)||min))))}/></label>;
 return <div className="alps-lab" data-state={error?'error':busy||loading?'loading':rows.length?'success':'default'}>
 <header className="alps-heading"><div><small>ALPS / 중앙 오케스트레이션 검증</small><h2>입고부터 재분배까지, 같은 조건으로 비교</h2><p>중앙에서 박스를 분류하고 팔레트를 선택합니다. 각 알고리즘은 현재 도착 박스와 잔여 종류·수량만 봅니다.</p></div><span>2개 입고 → 2개 출고 팔레트 · 분류 효과 / 알고리즘 효과 분리</span></header>
 <section className="alps-controls"><details><summary>실험 조건 편집 · 알고리즘 / 물량 분류 / 출고 우선순위</summary><fieldset disabled={busy||loading}><legend>실험 조건 · 합성 시나리오 / 입력값</legend><div className="alps-fields">{numeric('discovery','선정 시드 수',1,20)}{numeric('holdout','별도 확인 시드 수',1,20)}{numeric('seed','첫 난수 시드',1,2147483000)}{numeric('bufferCapacity','임시 버퍼 개수',0,20)}<label>의류 물량 비율<input type="number" min={0} max={1} step={.1} value={config.apparelShare} onChange={e=>change('apparelShare',Math.max(0,Math.min(1,Number(e.target.value))))}/></label><label>출고 조건<select value={config.shipment} onChange={e=>change('shipment',e.target.value as AlpsConfig['shipment'])}><option value="priority">의류 우선 · 기타는 대기</option><option value="simultaneous">분류별 동시 출고</option></select></label></div><div className="alps-algorithms">{algorithmRegistry().filter(a=>a.scope==='online').map(a=><label key={a.id}><input type="checkbox" checked={config.algorithms.includes(a.id)} onChange={e=>change('algorithms',e.target.checked?[...config.algorithms,a.id]:config.algorithms.filter(id=>id!==a.id))}/>{a.name}</label>)}</div><div className="alps-buttons"><button onClick={()=>change('scenario',structuredClone(sourceScenario))}>현재 시뮬레이터 입력 사용</button><button onClick={()=>setConfig(defaultAlpsConfig())}>합성 기본값 복원</button></div></fieldset></details><p>다음 실행: {config.scenario.name} · 각 팔레트 {config.scenario.pallet.width}×{config.scenario.pallet.depth}×{config.scenario.pallet.maxHeight} mm · 후보 {config.settings.maxCandidates}개 / 팔레트 · 실제 미래 순서 비공개</p><div className="alps-buttons"><button className="pallet-primary" disabled={busy||loading} onClick={run}>동일 조건 비교 실행</button><button disabled={!busy} onClick={stop}>계산 취소</button><button disabled={busy||loading} onClick={load}>{loading?'불러오는 중…':'저장된 실측 결과 보기'}</button><button disabled={!rows.length||busy} onClick={()=>save('alps-experiment.json',JSON.stringify({version:1,config:recordConfig,rows,shortlist,paired},null,2))}>JSON 저장</button><button disabled={!rows.length||busy} onClick={()=>save('alps-experiment.csv',alpsCsv(rows))}>CSV 저장</button></div><p role={error?'alert':'status'}>{error||message}</p>{busy&&<progress aria-label="실험 진행률" max={total} value={done}/>} {recordConfig&&<p>표시 중인 결과 조건: {recordConfig.scenario.name} · 의류 {display(recordConfig.apparelShare*100,0)}% · {recordConfig.shipment==='priority'?'의류 우선 출고':'동시 출고'} · 버퍼 {recordConfig.bufferCapacity}개</p>}
 </section>
 <section className="alps-findings"><div><small>선정 기준 · 안전 위반 / 시간 초과 제외</small><h3>{shortlist.length?`선정 시드의 후보 ${shortlist.length}개 · 확정 아님`:'아직 추천하지 않습니다'}</h3><p>출고 완료율 → 입고 완료율 → 임시 이동 → 계산시간. 기준선도 포함하며, 확인 시드의 순위가 바뀌면 최종 선정을 보류합니다.</p></div>{shortlist.map((r,i)=><article key={r.key}><b>{i+1}. {getAlgorithm(r.algorithm).name}</b><p>{ROUTES[r.route]}</p><p>선정 {r.n}회: 출고 {display((r.redistribution.mean??0)*100)}% / 추가 이동 {display(r.rehandles.mean)}</p><p>별도 확인 {r.holdout?.n??0}회: 출고 {display(r.holdout?.redistribution.mean===null||!r.holdout?null:r.holdout.redistribution.mean*100)}% / 추가 이동 {display(r.holdout?.rehandles.mean)}</p></article>)}</section>
 <section className="alps-player"><div className="alps-buttons"><button aria-pressed={mode==='pair'} onClick={()=>{setMode('pair');setFraction(0);}}>적용 전 / 후 · 같은 알고리즘</button><button aria-pressed={mode==='extremes'} onClick={()=>{setMode('extremes');setFraction(0);}}>이 시드의 낮은 / 높은 성과</button><label>알고리즘<select value={chosen||''} disabled={mode==='extremes'||!rows.length} onChange={e=>{setAlgorithm(e.target.value);setFraction(0);}}>{[...new Set(rows.map(r=>r.algorithm))].map(id=><option key={id} value={id}>{getAlgorithm(id).name}</option>)}</select></label><label>ALPS 분류<select value={route} onChange={e=>{setRoute(e.target.value as Routing);setFraction(0);}}><option value="dedicated">전용 팔레트</option><option value="overflow">용량 부족 시 혼합 허용</option></select></label><label>재생 시드<select value={seed} onChange={e=>{setSeed(Number(e.target.value));setFraction(0);}}>{[...new Set(rows.filter(r=>r.trace.length).map(r=>r.seed))].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div><div className="alps-replay-grid"><TrialReplay row={left} fraction={fraction} title={mode==='pair'?'01 · ALPS 분류 적용 전':'01 · 이 시드에서 성과가 낮은 실행'}/><TrialReplay row={right} fraction={fraction} title={mode==='pair'?'02 · ALPS 중앙 대분류 적용 후':'02 · 이 시드에서 성과가 높은 실행'}/></div><div className="alps-playbar"><button disabled={!left?.trace.length&&!right?.trace.length} onClick={()=>{if(fraction>=1)setFraction(0);setPlaying(p=>!p);}}>{playing?'일시정지':'단계 재생'}</button><button onClick={()=>{setPlaying(false);setFraction(0);}}>처음</button><input aria-label="입고·재분배 상대 진행률" type="range" min={0} max={1} step={.005} value={fraction} onChange={e=>{setPlaying(false);setFraction(Number(e.target.value));}}/><span>{display(fraction*100,0)}%</span></div><p>각 실행의 상대 진행률을 동기화합니다. 재생 속도는 작업시간이 아닙니다. 팔레트·박스 상태는 계산 기록 그대로 표시하며, 재분배 경로는 수직 인출 근사입니다.</p></section>
 <section className="alps-results"><h3>별도 확인 시드 · 평균과 최악 성과</h3><div className="pallet-table-scroll"><table><thead><tr>{['알고리즘 / 정책','유효 / 제외','입고 완료율','출고 완료율 · 최소','공간 활용률','높이 mm','추가 이동','계산 합계 ms','최소 지지율'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{holdout.map(r=><tr key={r.key}><th>{getAlgorithm(r.algorithm).name}<small>{ROUTES[r.route]}</small></th><td>{r.n} / {r.excluded}</td><td>{display(r.completion.mean===null?null:r.completion.mean*100)}%</td><td>{display(r.redistribution.mean===null?null:r.redistribution.mean*100)}% · {display(r.redistribution.min===null?null:r.redistribution.min*100)}%</td><td>{display(r.utilization.mean===null?null:r.utilization.mean*100)}%</td><td>{display(r.height.mean,0)}</td><td>{display(r.rehandles.mean)}</td><td>{display(r.planMs.mean,0)}</td><td>{display(r.support.min===null?null:r.support.min*100)}%</td></tr>)}</tbody></table></div><details><summary>중앙 분류만 바꾼 대응 차이 · 확인 시드</summary><p>동일 알고리즘·동일 시드에서 ALPS − 공용. 이동 차이가 음수면 임시 이동이 줄었습니다. 구간은 표본 대응 차이의 Student-t 95% 신뢰구간이며, 적은 시드에서는 불확실성이 큽니다.</p><div className="pallet-table-scroll"><table><thead><tr><th>알고리즘</th><th>입고 완료율 차이 %p</th><th>출고 완료율 차이 %p</th><th>추가 이동 차이 · 95% 구간</th><th>대응 시드</th></tr></thead><tbody>{paired.map(r=><tr key={r.algorithm}><th>{getAlgorithm(r.algorithm).name}</th><td>{display(r.completion.mean)}</td><td>{display(r.redistribution.mean)}</td><td>{display(r.rehandles.mean)} · {r.rehandles.ci95?.map(n=>display(n)).join(' ~ ')??'표본 부족'}</td><td>{r.rehandles.n}</td></tr>)}</tbody></table></div></details><details><summary>선정 시드의 전체 결과 / 실패 원인</summary><p>{discovery.length}개 조합. 정상 박스 개별 미적재와 안전 제약 위반은 구분합니다.</p>{rows.map(r=><p key={r.id}>{r.seed} · {getAlgorithm(r.algorithm).name} · {ROUTES[r.route]} · {r.status} · 미적재 {r.normal-r.placed} · 재분배 미완료 {r.placed-r.redistributed} · 거절 제안 {r.rejected} · {Object.entries(r.failures).map(([k,v])=>`${k} ${v}`).join(' / ')} {r.reason}</p>)}</details></section>
 <section className="alps-scope"><h3>무엇을 검증했는가</h3><p>분류는 물건별 합성 배송 속성입니다. 같은 크기·재질의 박스도 의류/기타로 나뉘며, 분류 때문에 무게·강도·무게중심을 변경하지 않습니다. 전용 분류는 물량 편중 때 미적재가 늘 수 있으며 혼합 허용은 그 대가로 분류 순도가 낮아집니다.</p><p>기하·정적 지지·입력 허용하중은 기존 확정 검사를 사용합니다. 입력의 재질 예제 강도는 실측 강도가 아닙니다. 실제 로봇 역기구학, 흡착 밀봉, 동적 붕괴, 팔레트 간 전체 운반 경로와 시간은 미검증입니다. 입고/출고 팔레트는 각각 두 개이며 모든 정책이 동일한 공간을 사용합니다.</p><p>이마트 실제 입출고 데이터와 고객 출고 우선순위를 가져온 뒤 같은 절차로 재검증해야 합니다. 현재 결과는 합성 조건의 후보 선정이며 이마트 최적 알고리즘의 증명이 아닙니다. 기존 Future-Aware Hybrid는 여러 휴리스틱을 결합한 후보로 평가하며, 검증 없이 새 알고리즘을 최고라고 표시하지 않습니다.</p></section>
 </div>;
}
