import {useEffect,useMemo,useRef,useState} from 'react';
import PalletScene from '../PalletScene';
import type {Scenario} from '../types';
import {calculateLoads} from '../geometry';
import {boxType,PACKAGE_PRESETS,packagingScenario,sampleSpecs,validateSpec,type BoxSpec} from './spec';
import {METHODS,PACKAGE_SETTINGS,WEIGHT_LABELS,sceneCandidate,type Method,type PackagePlan,type PackageSettings} from './planner';
import {applyEvent,commit,newSession,remainingInventory,summary,type ComparisonRow,type PackageEvent} from './session';
import './packaging.css';
const percent=(v:number)=>`${(v*100).toFixed(1)}%`;
const n=(v:number,d=1)=>Number.isFinite(v)?v.toFixed(d):'—';
function Field({label,value,set,min=0,max=10000,step=1}:{label:string;value:number;set:(v:number)=>void;min?:number;max?:number;step?:number}){return <label className="pkg-field"><span>{label}</span><input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>;}
function location(plan:PackagePlan|null){const c=plan?.candidates.find(v=>v.id===plan.selectedId);return c?`${c.placement.typeId} · (${Object.values(c.placement.position).map(v=>n(v,0)).join(', ')}) mm · ${String(c.placement.orientation)} · ${n(c.score??0)}점`:'배치 후보 없음 / 격리';}
function save(value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='packaging-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function PackagingLab({active,onUseInRelay}:{active:boolean;onUseInRelay:(s:Scenario)=>void}){
 const [session,setSession]=useState(()=>newSession(packagingScenario())),[method,setMethod]=useState<Method>('robust'),[settings,setSettings]=useState(()=>structuredClone(PACKAGE_SETTINGS)),[plan,setPlan]=useState<PackagePlan|null>(null),[busy,setBusy]=useState(false),[auto,setAuto]=useState(false),[error,setError]=useState(''),[debug,setDebug]=useState(false),[selected,setSelected]=useState<string|null>(null),[boxId,setBoxId]=useState<string|null>(null),[camera,setCamera]=useState('iso'),[revision,setRevision]=useState(0),[history,setHistory]=useState<number|null>(null),[rows,setRows]=useState<ComparisonRow[]>([]),[comparing,setComparing]=useState(false),[progress,setProgress]=useState(''),[compareView,setCompareView]=useState<Method|null>(null),[filter,setFilter]=useState('all'),[json,setJson]=useState(()=>JSON.stringify(sampleSpecs(),null,2)),[editor,setEditor]=useState('B'),[seed,setSeed]=useState(42),[diff,setDiff]=useState<{old:string;next:string}|null>(null),[eventKind,setEventKind]=useState('damaged'),[eventWeight,setEventWeight]=useState(45),[eventSize,setEventSize]=useState([600,450,350]),[eventType,setEventType]=useState('H');
 const worker=useRef<Worker|null>(null),comparison=useRef<Worker|null>(null),request=useRef(0),previous=useRef<string|null>(null);
 useEffect(()=>{worker.current?.terminate();setBusy(false);if(!active)return;setPlan(null);setSelected(null);setBoxId(null);setError('');if(session.cursor>=session.items.length){setAuto(false);return;}
  const id=++request.current,w=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});worker.current=w;setBusy(true);
  w.onmessage=e=>{if(e.data.id!==id)return;setBusy(false);if(e.data.kind==='error'){setError(e.data.error);setAuto(false);return;}setPlan(e.data.plan);if(previous.current!==null){setDiff({old:previous.current,next:location(e.data.plan)});previous.current=null;}};
  w.onerror=e=>{setBusy(false);setAuto(false);setError(e.message||'계획 Worker 실행 오류');};w.postMessage({id,kind:'plan',session,method,settings});return()=>w.terminate();
 },[active,session,method,settings]);
 useEffect(()=>{if(active&&auto&&plan&&!busy){const t=setTimeout(()=>{setSession(s=>commit(s,plan));},700);return()=>clearTimeout(t);}},[active,auto,plan,busy]);
 useEffect(()=>()=>comparison.current?.terminate(),[]);
 useEffect(()=>{if(!active){setAuto(false);comparison.current?.terminate();setComparing(false);}},[active]);
 const current=session.items[session.cursor],remaining=remainingInventory(session),metrics=summary(session),record=history===null?null:session.records[history-1],shownPlan=record?.plan??plan??(session.cursor===session.items.length?session.records.at(-1)?.plan:null),chosen=shownPlan?.candidates.find(c=>c.id===(selected??shownPlan.selectedId)),row=rows.find(r=>r.method===compareView),placements=row?.placements??(history===0?[]:record?.placements??session.placements),loads=calculateLoads(placements),selectedBox=placements.find(b=>b.id===boxId),spec=selectedBox?.packaging??(record?session.items[history!-1]?.packaging:current?.packaging),visibleCandidates=(shownPlan?.candidates??[]).filter(c=>filter==='all'||(filter==='valid'?c.valid:!c.valid)),sceneOthers=useMemo(()=>visibleCandidates.slice(0,24).map(sceneCandidate),[shownPlan,filter]),sceneChosen=chosen?sceneCandidate(chosen):null;
 const updateSettings=(fn:(v:PackageSettings)=>void)=>{setAuto(false);setSettings(s=>{const next=structuredClone(s);fn(next);return next;});};
 const reset=(s=session.scenario)=>{setAuto(false);setHistory(null);setCompareView(null);setDiff(null);previous.current=null;setSession(newSession({...s,arrival:{seed,pattern:'random-draw'}},seed));};
 const setRobot=(key:'maxReach'|'minReach'|'approach'|'payload',value:number)=>{setAuto(false);setSession(s=>{const scenario=structuredClone(s.scenario);if(key==='payload')scenario.constraints.gripper.payload=Math.max(1,value);else scenario.constraints.packagingRobot![key]=Math.max(0,value);return {...s,scenario};});};
 const event=()=>{try{let e:PackageEvent=eventKind==='damaged'?{kind:'damaged'}:eventKind==='missing'?{kind:'missing'}:eventKind==='weight'?{kind:'weight',weight:eventWeight}:eventKind==='dimensions'?{kind:'dimensions',length:eventSize[0],width:eventSize[1],height:eventSize[2]}:{kind:'type',typeId:eventType};setAuto(false);previous.current=location(plan);setDiff(null);setSession(s=>applyEvent(s,e));setError('');}catch(e){setError((e as Error).message);}};
 const compare=()=>{setAuto(false);setComparing(true);setProgress('동일 입고 순서로 5개 정책 실행');const w=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});comparison.current?.terminate();comparison.current=w;w.onmessage=e=>{if(e.data.kind==='progress')setProgress(`${METHODS[e.data.algorithm as Method]} · ${e.data.step} / ${e.data.total}`);else if(e.data.kind==='comparison'){setRows(e.data.rows);setComparing(false);setProgress('동일 입력 비교 완료');w.terminate();}else{setError(e.data.error);setComparing(false);w.terminate();}};w.onerror=e=>{setError(e.message);setComparing(false);};w.postMessage({id:1,kind:'compare',session,settings});};
 let specs:BoxSpec[]=[];try{const parsed=JSON.parse(json);if(Array.isArray(parsed))specs=parsed;}catch{/* Keep the user's incomplete JSON editable. */}
 const edited=specs.find(s=>s.id===editor),changeSpec=(patch:Partial<BoxSpec>)=>setJson(JSON.stringify(specs.map(s=>s.id===editor?{...s,...patch}:s),null,2));
 if(!active)return null;
 return <section className="pkg-lab" aria-label="포장 제약 알고리즘 실험">
  <header className="pkg-heading"><div><span className="pallet-eyebrow">PACKAGING × PHYSICS × FUTURE INVENTORY</span><h1>포장 조건이 바꾸는 다음 배치.</h1><p>현재 박스와 남은 수량으로 판단합니다. 실제 미래 순서는 계획기에 전달하지 않습니다.</p></div><span className="pkg-source">산업 시나리오 가정<br/>AI 모델 없이 · 로컬 Worker 계산</span></header>
  <div className="pkg-toolbar"><label>알고리즘<select aria-label="포장 알고리즘" value={method} onChange={e=>{setAuto(false);setMethod(e.target.value as Method);}}>{Object.entries(METHODS).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><Field label="입고 시드" value={seed} set={setSeed} max={2147483647}/><button onClick={()=>reset()}>같은 재고 새 실행</button><button onClick={()=>{const s=packagingScenario();s.arrival.seed=seed;reset(s);}}>A–H 예제</button><button onClick={()=>onUseInRelay(session.scenario)}>4대 공장에 재고 적용</button></div>
  <div className="pkg-stats"><div><small>입고 처리</small><b>{session.cursor}<em> / {session.items.length}</em></b></div><div><small>적재 / 미적재</small><b>{metrics.packed}<em> / {metrics.failed}</em></b></div><div><small>용적 이용률</small><b>{percent(metrics.utilization)}</b></div><div><small>최대 하중 사용</small><b data-warn={metrics.maxLoad>=.8}>{percent(metrics.maxLoad)}</b></div><div><small>결정 계산 시간</small><b>{n(plan?.milliseconds??metrics.planningMs)}<em> ms</em></b></div></div>
  {error&&<p role="alert" className="pkg-error">{error}</p>}
  <div className="pkg-workspace"><section className="pkg-main"><div className="pkg-viewbar"><b role="status">{busy?(previous.current!==null?'REPLANNING…':'후보 · 가상 순서 계산 중…'):history!==null?`기록 ${history} / ${session.records.length}`:current?`입고 ${current.id} · ${current.status==='normal'?'후보 검사 완료':current.status}`:'입고 처리 완료'}</b><div><button onClick={()=>{setCamera('iso');setRevision(v=>v+1);}}>입체</button><button onClick={()=>{setCamera('top');setRevision(v=>v+1);}}>평면</button><label><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/>후보 Debug</label></div></div>
   <PalletScene scenario={session.scenario} placements={placements} current={null} candidate={debug?sceneChosen:null} others={debug?sceneOthers:[]} options={{opacity:.92,outlines:true,slice:session.scenario.pallet.maxHeight,weight:false,supports:!!selectedBox,center:true,candidates:debug,path:false,arm:false,tool:false,candidateLimit:24}} selection={boxId} onSelect={id=>{if(id.startsWith('candidate:')){setSelected(id.slice(10));setBoxId(null);}else setBoxId(id);}} camera={camera} cameraVersion={revision}/>
   <div className="pkg-controls"><button className="pallet-primary" disabled={auto||!current||!!error||history!==null||!!compareView} onClick={()=>setAuto(true)}>▶ 자동 적재</button><button disabled={!auto} onClick={()=>setAuto(false)}>일시정지</button><button disabled={busy||!plan||!current||auto||history!==null||!!compareView} onClick={()=>plan&&setSession(s=>commit(s,plan))}>한 박스 확정</button><button onClick={()=>save({session,settings,method,comparison:rows})}>결과 JSON</button><span>높이 {n(metrics.height,0)} / {session.scenario.pallet.maxHeight} mm</span></div>
   <label className="pkg-timeline">배치 기록<input aria-label="포장 배치 기록" type="range" min={0} max={session.records.length} value={history??session.records.length} onChange={e=>{setAuto(false);setCompareView(null);setHistory(Number(e.target.value));setSelected(null);}}/>{history??session.records.length} / {session.records.length}<button onClick={()=>{setHistory(null);setCompareView(null);setSelected(null);}}>현재로</button></label>
   {shownPlan&&<div className="pkg-diagnostics"><span>생성 <b>{shownPlan.generated}</b></span><span>검사 <b>{shownPlan.checked}</b></span><span>유효 <b>{shownPlan.valid}</b></span><span>회전 사전 제외 <b>{shownPlan.orientationRejected} / {shownPlan.orientationOptions} 자세</b></span>{Object.entries(shownPlan.rejected).filter(([k])=>k!=='orientation').map(([k,v])=><span key={k}>{({boundary:'경계',collision:'충돌',load:'하중',support:'지지',robot:'로봇'} as Record<string,string>)[k]} 탈락 <b>{v}</b></span>)}<small>탈락 사유는 중복 집계됩니다. 탐색 {shownPlan.futureChecks}회 · 캐시 재사용 {shownPlan.cacheHits}회{shownPlan.capped?' · 후보 / 미래 탐색 예산 적용':''}</small></div>}
   <section className="pkg-section"><header><h2>왜 이 위치인가</h2><select aria-label="후보 표시 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 후보</option><option value="valid">유효 후보</option><option value="rejected">탈락 후보</option></select></header><div className="pkg-candidate-list" aria-label="검사된 배치 후보">{visibleCandidates.map(c=><button key={c.id} data-valid={c.valid} aria-pressed={chosen?.id===c.id} onClick={()=>{setSelected(c.id);setBoxId(null);setDebug(true);}}>{c.id.replace('pkg-','#')} · {c.valid?n(c.score??0):'탈락'}</button>)}</div><small>3D에는 목록 앞 24개와 선택한 후보를 표시합니다. 녹색: 통과 · 빨간색: 탈락. 클릭하여 검사 수치를 확인하세요.</small>
    {chosen&&<><dl className="pkg-facts"><dt>위치 / 자세</dt><dd>{Object.values(chosen.placement.position).map(v=>n(v,0)).join(' / ')} mm · {String(chosen.placement.orientation)}</dd><dt>지지 / 최소</dt><dd>{percent(chosen.placement.supportRatio)} / {percent(chosen.placement.packaging?.minSupportRatio??.75)}</dd><dt>최대 하중 / TCP 거리</dt><dd>{percent(chosen.maxLoadUtilization)} · {n(chosen.reach,0)} mm · {chosen.grasp??'파지 불가'}</dd><dt>미래 공간 / 최대 바닥 빈 영역</dt><dd>{percent(chosen.compatibility)} · {n(chosen.regionArea/1e6,3)} m²</dd></dl>{!chosen.valid?<div className="pkg-error"><b>REJECTED · 점수 계산 제외</b><ul>{chosen.reasons.map(r=><li key={r}>{r}</li>)}</ul></div>:<><div className="pkg-score-grid">{Object.entries(chosen.terms).map(([key,value])=><div key={key}><span>{WEIGHT_LABELS[key as keyof typeof WEIGHT_LABELS]}</span><b data-negative={value<0}>{value>=0?'+':''}{n(value)}</b></div>)}<div className="pkg-total"><span>TOTAL</span><b>{n(chosen.score??0)}</b></div></div>{chosen.future?<div className="pkg-future"><span>Expected <b>{n(chosen.future.mean*100)}</b></span><span>하위 10% 평균 <b>{n(chosen.future.worst*100)}</b></span><span>Robust <b>{n(chosen.future.robust*100)}</b></span><small>실행 {chosen.future.samples}순서 · 깊이 {chosen.future.minDepth}–{chosen.future.maxDepth} / 요청 {settings.depth}{chosen.future.capped?' · 예산으로 일부 상태 생략 · 미탐색 깊이는 실패 위험에 포함':''}</small></div>:<p>이 후보는 즉시 점수만 계산했습니다. 미래 탐색은 상위 {settings.rootCandidates}개 후보에 적용합니다.</p>}</>}</>}
   </section>
   <section className="pkg-section"><header><h2>같은 입고 순서, 다섯 가지 판단</h2><button disabled={comparing||busy} onClick={compare}>5개 알고리즘 비교</button>{comparing&&<button onClick={()=>{comparison.current?.terminate();setComparing(false);setProgress('비교 취소');}}>비교 취소</button>}</header><p role="status">{progress||'모든 정책에 동일한 박스·제약·입고 순서와 탐색 예산을 사용합니다.'}</p>{!!rows.length&&<div className="pkg-table-wrap" tabIndex={0}><table><thead><tr><th>정책 / 3D 결과</th><th>용적</th><th>적재 / 실패</th><th>평균 지지</th><th>최대 하중</th><th>CoG 편차 mm</th><th>평균 계산 ms</th><th>로봇 s</th><th>재계획</th></tr></thead><tbody>{rows.map(r=><tr key={r.method}><th><button onClick={()=>{setAuto(false);setCompareView(r.method);}}>{METHODS[r.method]}</button></th><td>{percent(r.metrics.utilization)}</td><td>{r.metrics.packed} / {r.metrics.failed}</td><td>{percent(r.metrics.support)}</td><td>{percent(r.metrics.maxLoad)}</td><td>{n(r.metrics.cogDeviation)}</td><td>{n(r.metrics.planningMs)}</td><td>{n(r.metrics.cycleSeconds)}</td><td>{r.metrics.replans}</td></tr>)}</tbody></table></div>}{compareView&&<p>3D 비교 결과: {METHODS[compareView]} <button onClick={()=>setCompareView(null)}>실험 복귀</button></p>}<small>계산 시간은 이 기기의 실측입니다. Greedy 50 ms / Future 1,000 ms는 목표이며 보장값이 아닙니다. 최적해를 보장하지 않는 제한 탐색입니다.</small></section>
  </section><aside className="pkg-aside"><section><span className="pallet-eyebrow">BOX CONSTRAINTS</span><h2>{selectedBox?selectedBox.id:record?.id??current?.id??'입고 완료'}</h2>{spec?<><h3>{spec.name}</h3><span className="pkg-badge">{spec.dataSource==='REFERENCE_CASE'?'Reference Case':spec.dataSource==='VERIFIED'?'Verified':'Simulation Assumption'}</span>{spec.dataSource==='REFERENCE_CASE'&&<span className="pkg-badge">취급 조건: Simulation Assumption</span>}<dl className="pkg-facts"><dt>Package</dt><dd>{spec.packageType}</dd><dt>치수 / 무게</dt><dd>{spec.length} × {spec.width} × {spec.height} mm<br/>{spec.grossWeight} kg</dd><dt>회전</dt><dd>{spec.allowedOrientations.join(' · ')}</dd><dt>Upright / 적층 가능</dt><dd>{spec.keepUpright?'유지':'자유'} / {spec.stackable?'가능':'위 적재 금지'}</dd><dt>상부 하중 / 허용</dt><dd data-warn={!!selectedBox&&(loads[selectedBox.id]??0)>=spec.maxTopLoad*.8}>{n(selectedBox?loads[selectedBox.id]??0:0)} / {spec.maxTopLoad} kg</dd><dt>최소 지지</dt><dd>{percent(spec.minSupportRatio)}</dd><dt>파손 / 충격 민감</dt><dd>{spec.fragility} / {spec.shockSensitive?'예':'아니오'}</dd><dt>파지 면</dt><dd>{spec.graspableFaces.join(' · ')}</dd><dt>로컬 CoG</dt><dd>{Object.values(spec.centerOfGravity).join(' / ')} mm</dd></dl><p className="pkg-description">{spec.description}</p>{spec.sourceUrl&&<a href={spec.sourceUrl} target="_blank" rel="noreferrer">공개 재게시 Packing List ↗</a>}</>:<p>3D의 박스를 클릭하면 하중과 포장 조건을 확인합니다.</p>}<small>CoG는 원래 자세의 최소 모서리 기준 mm. 상부 하중 80%부터 경고, 100% 초과는 배치에서 제외합니다.</small></section>
   <section><h3>남은 재고</h3><p>현재 박스를 제외한 미입고 수량</p><div className="pkg-inventory">{session.scenario.types.map(t=><span key={t.id}>{t.id}<b>{remaining[t.id]??0}</b></span>)}</div><small>가상 미래 순서는 이 수량에서만 추출합니다.</small></section>
   <section><h3>관측 변경 · 부분 재계획</h3><select aria-label="포장 재계획 이벤트" value={eventKind} onChange={e=>setEventKind(e.target.value)}><option value="damaged">박스 파손</option><option value="missing">박스 누락</option><option value="dimensions">실측 치수 변경</option><option value="weight">실측 무게 변경</option><option value="type">들어온 종류 변경</option></select>{eventKind==='weight'&&<Field label="실측 무게 kg" value={eventWeight} set={setEventWeight} min={.1}/>} {eventKind==='dimensions'&&eventSize.map((v,i)=><Field key={i} label={['실측 길이 mm','실측 폭 mm','실측 높이 mm'][i]} value={v} set={n=>setEventSize(a=>a.map((x,j)=>j===i?n:x))} min={1}/>)}{eventKind==='type'&&<select aria-label="변경된 종류" value={eventType} onChange={e=>setEventType(e.target.value)}>{session.scenario.types.map(t=><option key={t.id} value={t.id}>{t.id} · {t.name}</option>)}</select>}<button disabled={!current||busy||history!==null} onClick={event}>현재 박스 수정 · 재계획</button><small>확정 적재 {session.placements.length}개 유지 · 재계획 {session.replanCount}회</small>{diff&&<div className="pkg-diff"><b>OLD PLAN</b><p>{diff.old}</p><b>NEW PLAN</b><p>{diff.next}</p></div>}</section>
  </aside></div>
  <details className="pkg-section"><summary>탐색 · 로봇 설정 / 점수 가중치</summary><div className="pkg-settings"><label>가상 순서 수<select aria-label="Monte Carlo Count" value={settings.samples} onChange={e=>updateSettings(s=>s.samples=Number(e.target.value) as 20|50|100)}>{[20,50,100].map(v=><option key={v}>{v}</option>)}</select></label><label>탐색 깊이<select aria-label="Lookahead Depth" value={settings.depth} onChange={e=>updateSettings(s=>s.depth=Number(e.target.value) as 3|5|10)}>{[3,5,10].map(v=><option key={v}>{v}</option>)}</select></label><Field label="Beam Width" value={settings.beamWidth} set={v=>updateSettings(s=>s.beamWidth=v)} min={1} max={30}/><Field label="계획 시드" value={settings.seed} set={v=>updateSettings(s=>s.seed=v)} max={2147483647}/><Field label="미래 탐색 후보 수" value={settings.rootCandidates} set={v=>updateSettings(s=>s.rootCandidates=v)} min={1} max={8}/><Field label="미래 후보 검사 예산" value={settings.maxFutureChecks} set={v=>updateSettings(s=>s.maxFutureChecks=v)} min={100} max={100000}/></div><div className="pkg-settings">{Object.entries(settings.weights).map(([key,value])=><Field key={key} label={WEIGHT_LABELS[key as keyof typeof WEIGHT_LABELS]} value={value} set={v=>updateSettings(s=>s.weights[key as keyof typeof WEIGHT_LABELS]=v)} max={100}/>)}</div><p>기본 Beam 10 · 깊이 5 · 20순서. 미래 점수는 0.7 × 평균 + 0.3 × 하위 10% 평균. 미탐색 꼬리는 낙관적으로 성공 처리하지 않습니다.</p><div className="pkg-settings">{(['maxReach','minReach','approach'] as const).map(key=><Field key={key} label={{maxReach:'3D 최대 도달 mm',minReach:'3D 최소 도달 mm',approach:'접근 corridor mm'}[key]} value={session.scenario.constraints.packagingRobot![key]} set={v=>setRobot(key,v)}/>)}<Field label="가반하중 kg (가정)" value={session.scenario.constraints.gripper.payload} set={v=>setRobot('payload',v)}/></div><small>기본 가반 100 kg, TCP 650 mm/s는 이 실험의 가정입니다. 기존 4대 공장에서는 선택한 로봇 문맥의 가반하중(35 / 15 kg)이 적용됩니다. 공장 장식물은 장애물 모델에 포함되지 않습니다.</small></details>
  <details className="pkg-section"><summary>포장 데이터 편집 · Presets / BoxSpec JSON</summary><p>모든 기본 지지·강도·취급 수치는 변경 가능한 Simulation Assumption이며 HD현대 공식 규정이 아닙니다. 이미 적재된 박스를 바꾸지 않도록 아래 적용은 새 실험을 시작합니다.</p><div className="pkg-editor"><div><select aria-label="편집 박스 종류" value={editor} onChange={e=>setEditor(e.target.value)}>{specs.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select>{edited&&<><label>포장 preset<select aria-label="포장 preset" value={edited.packageType} onChange={e=>changeSpec({packageType:e.target.value as BoxSpec['packageType'],...structuredClone(PACKAGE_PRESETS[e.target.value as BoxSpec['packageType']])})}>{Object.keys(PACKAGE_PRESETS).map(p=><option key={p}>{p}</option>)}</select></label><Field label="최소 지지 비율" value={edited.minSupportRatio} min={.01} max={1} step={.01} set={v=>changeSpec({minSupportRatio:v})}/><Field label="상부 허용하중 kg" value={edited.maxTopLoad} set={v=>changeSpec({maxTopLoad:v})}/><Field label="박스 수량" value={edited.quantity} max={120} set={v=>changeSpec({quantity:v})}/><label><input type="checkbox" checked={edited.keepUpright} onChange={e=>changeSpec({keepUpright:e.target.checked})}/>위아래 유지</label><label><input type="checkbox" checked={edited.stackable} onChange={e=>changeSpec({stackable:e.target.checked})}/>상부 적층 가능</label></>}</div><textarea aria-label="BoxSpec JSON" value={json} onChange={e=>setJson(e.target.value)} spellCheck={false}/></div><button onClick={()=>{try{const specs=JSON.parse(json);if(!Array.isArray(specs)||!specs.length||new Set(specs.map((s:BoxSpec)=>s.id)).size!==specs.length)throw Error('고유 ID를 가진 BoxSpec 배열이 필요합니다.');specs.forEach(validateSpec);const total=specs.reduce((n:number,s:BoxSpec)=>n+s.quantity,0);if(total<1||total>120)throw Error('전체 수량 1~120');const s=packagingScenario(specs,seed);s.constraints=session.scenario.constraints;reset(s);setError('');}catch(e){setError((e as Error).message);}}}>검증 후 새 실험에 적용</button></details>
 </section>;
}
