import { useEffect, useState } from 'react';
import { useLab } from './hooks/useLab';
import { Board, PiecePreview } from './components/Board';
import { Sidebar } from './components/Sidebar';
import { Explanation } from './components/Explanation';
import { Candidates } from './components/Candidates';
import { Explorer } from './components/Explorer';
import { Player } from './components/Player';
import { Comparison } from './components/Comparison';
import { StrategyLesson } from './components/StrategyLesson';
import { Icon } from './components/Icon';
import { measure, rotations } from './engine/board';
import { formatScore } from './engine/evaluate';
import { wellColumn } from './engine/strategy';
import { SCENARIOS } from './engine/scenarios';
export default function App() {
  const lab=useLab();
  const [mobileTab,setMobileTab]=useState('board'),[help,setHelp]=useState(false),[clearFlash,setClearFlash]=useState(false),[editX,setEditX]=useState(0),[editY,setEditY]=useState(19);
  useEffect(()=>{if(lab.step===3&&lab.preview?.clearedRows.length){setClearFlash(true);const t=setTimeout(()=>setClearFlash(false),650/lab.speed);return()=>clearTimeout(t);}setClearFlash(false);},[lab.step,lab.preview?.id,lab.speed]);
  const observing=lab.step<2&&!lab.previewId&&!lab.treeNode;
  const virtual=lab.step>=2&&lab.step<7||!!lab.previewId||!!lab.treeNode;
  const base=lab.decision?.board??lab.board;
  const shownBoard=lab.editing?lab.board:lab.treeNode?.board??(observing||lab.step===2||lab.step===6?base:clearFlash?lab.preview?.beforeClear??base:lab.preview?.board??base);
  const ghost=lab.editing||lab.treeNode?undefined:observing?{piece:lab.decision?.current??lab.current,rotation:0,x:3,y:1,cells:rotations(lab.decision?.current??lab.current)[0]}:lab.step===2||lab.step===6?lab.preview?.action:undefined;
  const boardMetrics=measure(shownBoard),appliedLines=lab.history.reduce((total,d)=>total+(d.analysis.candidates.find(c=>c.id===d.analysis.selectedId)?.metrics.lines??0),0);
  const quickCandidates=[lab.selected,lab.analysis?.candidates.find(c=>c.id===lab.events[3]?.candidateId)].filter((c,i,all)=>c&&all.findIndex(other=>other?.id===c.id)===i);
  return <div className="app-shell">
    <header className="app-header"><div className="brand"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span><div><h1>블록 AI 연구실</h1><span>TETRIS AI LAB</span></div><span className="lab-tag">LAB</span></div><nav className="mode-nav" aria-label="학습 모드">{([{id:'anatomy',label:'한 수 해부',icon:'grid'},{id:'free',label:'자유 실험',icon:'flask'},{id:'compare',label:'알고리즘 비교',icon:'chart'}] as const).map(m=><button key={m.id} className={lab.mode===m.id?'active':''} aria-current={lab.mode===m.id?'page':undefined} onClick={()=>{lab.setMode(m.id);setMobileTab('board');}}><Icon name={m.icon} size={17}/>{m.label}</button>)}<button onClick={()=>{window.location.hash="3d";}}><Icon name="cube" size={17}/>3D 시뮬레이터</button></nav><div className="header-status"><span className={`status-dot ${lab.playing?'active-dot':''}`}/><span>{lab.busy?'계산 중':lab.playing?'재생 중':'일시정지'}</span><button className="icon-button" title="도움말" aria-label="도움말" onClick={()=>setHelp(!help)}><Icon name="help" size={20}/></button></div></header>
    <main className="main-content"><div className="lab-heading"><div><div className="breadcrumb"><span>{lab.mode==='anatomy'?'한 수 해부':lab.mode==='free'?'자유 실험':'알고리즘 비교'}</span><Icon name="next" size={11}/><span>실험 {String(SCENARIOS.findIndex(s=>s.id===lab.scenarioId)+1).padStart(2,'0')}</span></div><h2>{lab.mode==='compare'?'같은 조건에서 탐색을 비교하세요':lab.scenario.lesson}</h2></div><div className="rule-badge"><Icon name="info" size={14}/>교육용 수직 낙하 규칙</div></div>
      <nav className="mobile-tabs" aria-label="실험 패널"><button className={mobileTab==='board'?'active':''} onClick={()=>setMobileTab('board')}>보드</button><button className={mobileTab==='explanation'?'active':''} onClick={()=>setMobileTab('explanation')}>해설</button><button className={mobileTab==='settings'?'active':''} onClick={()=>setMobileTab('settings')}>설정</button></nav>
      <div className={`lab-grid mobile-${mobileTab} ${lab.mode==='compare'?'compare-grid':''}`}>
        <Sidebar lab={lab}/>
        {lab.mode==='compare'?<Comparison lab={lab}/>:<><section className="center-stage"><section className="board-panel panel"><div className="board-panel-header"><div><span className={`board-status ${virtual?'virtual':''}`}>{lab.editing?'사용자 정의 실험 상태':virtual?'탐색 중인 가상 보드':lab.decision?.applied&&lab.step<7?'적용 전 보드 · 재생 기록':'실제로 적용된 보드'}</span>{lab.branch&&<span className="branch-badge">새 실험 분기</span>}</div><span className="board-dimensions">10 × 20</span></div><div className="board-workspace"><div className="board-annotation"><div className="decision-count"><span>이번 결정</span><strong>{String((lab.decision?.index??lab.index)+1).padStart(2,'0')}</strong></div><div className="board-instruction"><span className="mini-line"/><p>{observing?'블록이 놓일 자리를 함께 찾아볼까요?':lab.treeNode?`${lab.treeNode.depth}수까지 본 가상 상태`:`회전 ${lab.preview?.action.rotation??0} · x=${lab.preview?.action.x??0}`}</p>{!observing&&<small>{lab.treeNode?'노드 '+lab.treeNode.id:lab.step===7?'이번 결정 적용 완료':'미리보기 · 실제 상태 유지'}</small>}</div>{lab.step<3&&!lab.editing&&<div className="quick-comparison"><span>대표 후보</span>{quickCandidates.map(c=>c&&<button key={c.id} onClick={()=>lab.setPreviewId(c.id)} aria-label={`대표 후보 회전 ${c.action.rotation} x ${c.action.x}`}><Board board={c.board} mini showCoordinates={false}/><span><b>x {c.action.x} · r {c.action.rotation}</b><strong>{formatScore(c.immediate)}</strong><small>구멍 {c.metrics.holes}칸</small></span></button>)}</div>}{lab.step>=3&&lab.preview&&<div className="hole-callout"><span>구멍 패널티</span><b>−{(lab.preview.metrics.holes*lab.weights.holes).toFixed(1)}<small>점</small></b><span>{lab.preview.metrics.holes}칸 × {lab.weights.holes}</span></div>}</div>
          <div className="main-board"><Board board={shownBoard} ghost={ghost} wellColumn={wellColumn(lab.config.strategy)} features={lab.step===3&&!clearFlash&&!lab.treeNode&&!lab.editing} selected={lab.step===6} dropping={lab.step===2&&!lab.previewId} dropDuration={450/lab.speed} clearRows={clearFlash?lab.preview?.clearedRows:[]} editable={lab.editing} onEdit={lab.editBoard}/>{lab.busy&&!lab.editing&&<div className="computing"><span className="loading-bars"><i/><i/><i/></span>후보 계산 중</div>}</div>
          <aside className="piece-queue"><div className="current-piece"><span>현재 블록</span><div><PiecePreview piece={lab.decision?.current??lab.current}/><b>{lab.decision?.current??lab.current}</b></div></div><div className="next-queue"><span>NEXT <small>공개된 5개</small></span>{(lab.decision?.next??lab.next).map((p,i)=><div key={i} className={i===0&&lab.step===5?'next-highlight':''}><small>{i+1}</small><PiecePreview piece={p}/><b>{p}</b></div>)}</div><div className="hold-off">HOLD <span>꺼짐</span></div></aside>
        </div><div className="board-footer"><span><i className="legend-square existing"/>기존 블록</span><span><i className="legend-square preview"/>가상 배치</span><span><i className="legend-square hole"/>구멍</span><div><span>높이 합 <b>{boardMetrics.height}</b></span><span>구멍 <b>{boardMetrics.holes}</b></span></div></div></section>
        {lab.editing&&<div className="keyboard-edit panel"><label>x<input aria-label="편집 셀 x" type="number" min="0" max="9" value={editX} onChange={e=>setEditX(Math.max(0,Math.min(9,+e.target.value)))}/></label><label>y<input aria-label="편집 셀 y" type="number" min="0" max="19" value={editY} onChange={e=>setEditY(Math.max(0,Math.min(19,+e.target.value)))}/></label><button onClick={()=>{const b=lab.board.map(r=>[...r]);b[editY][editX]=b[editY][editX]?0:8;lab.editBoard(b);}}>셀 채우기 / 지우기</button></div>}
        {lab.custom&&<p className="custom-notice">사용자 정의 실험 상태 · 자연 플레이로 만든 보드가 아닐 수 있습니다.</p>}{lab.error&&<p role="alert" className="error">{lab.error}</p>}{!lab.busy&&!lab.selected&&<p className="error">게임 오버 · 현재 탐색 범위에서 배치 가능한 경로가 없습니다.</p>}
        <StrategyLesson lab={lab}/><Candidates lab={lab}/><Explorer lab={lab}/></section><Explanation lab={lab}/></>}
      </div><footer className="lab-footer"><span><span className="status-dot active-dot"/>모든 계산은 이 브라우저 안에서</span><span>시드 {lab.seed} · 실제 배치 {lab.index}블록 · 최근 40결정의 삭제 {appliedLines}줄</span></footer>
    </main>{lab.mode!=='compare'&&<Player lab={lab}/>}
    {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="help-modal panel" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e=>e.stopPropagation()}><div className="section-heading"><h2 id="help-title">선택 과정을 함께 따라가세요</h2><button autoFocus className="icon-button" aria-label="도움말 닫기" onClick={()=>setHelp(false)}><Icon name="close"/></button></div><p>재생을 누르면 후보 생성 → 가상 배치 → 평가 → 미래 탐색 → 선택을 한 단계씩 보여줍니다. 기본은 한 결정 뒤 멈춥니다.</p><p>후보 카드로 다른 착지를 보고, 비교 고정으로 두 보드를 나란히 살펴보세요. 구멍 패널티를 0으로 바꾸면 기본 시나리오에서 선택이 달라집니다.</p><p>Space: 재생·정지 / ← →: 설명 단계 이동<br/>입력창과 버튼을 조작할 때 단축키는 작동하지 않습니다.</p><p>이 앱은 상공에서 회전과 x를 정한 뒤 수직 낙하합니다. 벽차기·슬라이드·T-spin·HOLD·확률 탐색·자동 가중치 학습·강화학습은 구현하지 않았습니다.</p><button className="primary-button" onClick={()=>setHelp(false)}>실험 계속하기</button></section></div>}
  </div>;
}

